function login() {let key = document.getElementById("activationKey").value;
 const errorMessage = document.getElementById("error-message");  const keyMappings = {
            "XRDCTGVYBUHJNI": "https://oracrypto.COM",
            "ZXS4CD5FVU6BG": "TBYUNMILCVGBHJN",
            "AXSERBGYU9GNH": "XECRTVBYUNIM", "AXSERBGYU9GNH": "XECRTVBYUNIM",       "AXSERBGYU9GNH": "XECRTVBYUNIM",    
     "AXSERBGYU9GNH": "XECRTVBYUNIM",        "ZXS4CD5FVU6BG": "TBYUNMILCVGBHJN",   "AXSERBGYU9GNH": "XECRTVBYUNIM",
"XRDCTGVYBUHJNI": "https://oracrypto.COM",        "ZXS4CD5FVU6BG": "TBYUNMILCVGBHJN",  "AXSERBGYU9GNH": "https://www.bitcoinzn.com",
"WZREXTCRYTVUYBIUJN": "https://oracrypto.COM", "A4SE5DRTYUVYBIUNLK": "TBYUNMILCVGBHJN",
"drtfpl[TYBIUNOIM": "https://www.bitcoinzn.com",
       "AXSERBGYU9GNH": "XECRTVBYUNIM",    
     "AXSERBGYU9GNH": "XECRTVBYUNIM",        "ZXS4CD5FVU6BG": "TBYUNMILCVGBHJN",   "AXSERBGYU9GNH": "XECRTVBYUNIM",
"XRDCTGVYBUHJNI": "https://oracrypto.COM",        "ZXS4CD5FVU6BG": "TBYUNMILCVGBHJN",  "AXSERBGYU9GNH": "https://www.bitcoinzn.com",
"WZREXTCRYTVUYBIUJN": "https://oracrypto.COM", "A4SE5DRTYUVYBIUNLK": "TBYUNMILCVGBHJN",
"drtfpl[TYBIUNOIM": "https://www.bitcoinzn.com",
"XRDCTGVYBUHJNI": "https://oracrypto.COM",
            "ZXS4CD5FVU6BG": "TBYUNMILCVGBHJN",
            "AXSERBGYU9GNH": "XECRTVBYUNIM",
"XRDCTGVYBUHJNI": "https://oracrypto.COM", "AXSERBGYU9GNH": "XECRTVBYUNIM",       "AXSERBGYU9GNH": "XECRTVBYUNIM",    
     "AXSERBGYU9GNH": "XECRTVBYUNIM",        "ZXS4CD5FVU6BG": "TBYUNMILCVGBHJN",   "AXSERBGYU9GNH": "XECRTVBYUNIM",
"XRDCTGVYBUHJNI": "https://oracrypto.COM",        "ZXS4CD5FVU6BG": "TBYUNMILCVGBHJN",  "AXSERBGYU9GNH": "https://www.bitcoinzn.com",
"WZREXTCRYTVUYBIUJN": "https://oracrypto.COM", "A4SE5DRTYUVYBIUNLK": "TBYUNMILCVGBHJN",
"drtfpl[TYBIUNOIM": "https://www.bitcoinzn.com",
       "AXSERBGYU9GNH": "XECRTVBYUNIM",    
     "AXSERBGYU9GNH": "XECRTVBYUNIM",        "ZXS4CD5FVU6BG": "TBYUNMILCVGBHJN",   "AXSERBGYU9GNH": "XECRTVBYUNIM",
"XRDCTGVYBUHJNI": "https://oracrypto.COM",        "ZXS4CD5FVU6BG": "TBYUNMILCVGBHJN",  "AXSERBGYU9GNH": "https://www.bitcoinzn.com",
"WZREXTCRYTVUYBIUJN": "https://oracrypto.COM", "A4SE5DRTYUVYBIUNLK": "TBYUNMILCVGBHJN",
"drtfpl[TYBIUNOIM": "https://www.bitcoinzn.com",
            "ZXS4CD5FVU6BG": "TBYUNMILCVGBHJN",
           "AXSERBGYU9GNH": "XECRTVBYUNIM",       "AXSERBGYU9GNH": "XECRTVBYUNIM",    
     "AXSERBGYU9GNH": "XECRTVBYUNIM",        "ZXS4CD5FVU6BG": "TBYUNMILCVGBHJN",   "zwsedc tgbuh": "XECRTVBYUNIM",
"XRDCTGVYBUHJNI": "https://oracrypto.COM",        "ZXS4CD5FVU6BG": "TBYUNMILCVGBHJN",  "AXSERBGYU9GNH": "https://www.sxedtrfvgyujnhmk.com",
"WZREXTCRYTVUYBIUJN": "https://oracrypto.COM", "A4SE5DRTYUVYBIUNLK": "TBYUNMILCVGBHJN",
"drtfpl[TYBIUNOIM": "https://www.bitcoinzn.com",
       "AXSERBGYU9GNH": "XECRTVBYUNIM",    
     "AXSERBGYU9GNH": "XECRTVBYUNIM",        "ZXS4CD5FVU6BG": "TBYUNMILCVGBHJN",   "AXSERBGYU9GNH": "XECRTVBYUNIM",
"XRDCTGVYBUHJNI": "https://oracrypto.COM",        "ZXS4CD5FVU6BG": "TBYUNMILCVGBHJN",  "AXSERBGYU9GNH": "https://www.edrftgynhujm,ik.com",
"WZREXTCRYTVUYBIUJN": "https://oracrypto.COM", "A4SE5DRTYUVYBIUNLK": "TBYUNMILCVGBHJN",
"drtfpl[TYBIUNOIM": "https://www.bitcoinzn.com",   "AXSERBGYU9GNH": "XECRTVBYUNIM",       "AXSERBGYU9GNH": "XECRTVBYUNIM",    
     "AXSERBGYU9GNH": "XECRTVBYUNIM",        "ZXS4CD5FVU6BG": "TBYUNMILCVGBHJN",   "AXSERBGYU9GNH": "XECRTVBYUNIM",
"XRDCTGVYBUHJNI": "https://oracrypto.COM",        "ZXS4CD5FVU6BG": "TBYUNMILCVGBHJN",  "AXSERBGYU9GNH": "https://www.bitcoinzn.com",
"WZREXTCRYTVUYBIUJN": "https://oracrypto.COM", "A4SE5DRTYUVYBIUNLK": "TBYUNMILCVGBHJN",
"drtfpl[TYBIUNOIM": "https://www.bitcoinzn.com",
       "AXSERBGYU9GNH": "XECRTVBYUNIM",    
     "AXSERBGYU9GNH": "XECRTVBYUNIM",        "ZXS4CD5FVU6BG": "TBYUNMILCVGBHJN",   "AXSERBGYU9GNH": "XECRTVBYUNIM",
"c4d65fguyuhjiop": "https://oracrypto.COM",        "ZXS4CD5FVU6BG": "TBYUNMILCVGBHJN",  "AXSERBGYU9GNH": "https://www.dfrvgbjnhm.com",
"WZREXTCRYTVUYBIUJN": "https://oracrypto.COM", "A4SE5DRTYUVYBIUNLK": "TBYUNMILCVGBHJN",
"drtfpl[TYBIUNOIM": "https://www.setdrytfugyihojp.com",
"XRDCTGVYBUHJNI": "https://sxdruygiuoi.COM",
            "AXSERBGYU9GNH": "XECRTVBYUNIM",       "AXSERBGYU9GNH": "XECRTVBYUNIM",    
     "AXSERBGYU9GNH": "XECRTVBYUNIM",        "ZXS4CD5FVU6BG": "TBYUNMILCVGBHJN",   "AXSERBGYU9GNH": "XECRTVBYUNIM",
"XRDCTGVYBUHJNI": "https://oracrypto.COM",        "ZXS4CD5FVU6BG": "TBYUNMILCVGBHJN",  "AXSERBGYU9GNH": "https://www.5e6rd7gyiuohipj.com",
"WZREXTCRYTVUYBIUJN": "https://x5cd6fv7giyuo.COM", "A4SE5DRTYUVYBIUNLK": "TBYUNMILCVGBHJN",
"drtfpl[TYBIUNOIM": "https://www.bitcoinzn.com",
       "AXSERBGYU9GNH": "XECRTVBYUNIM",    
     "AXSERBGYU9GNH": "XECRTVBYUNIM",        "ZXS4CD5FVU6BG": "TBYUNMILCVGBHJN",   "AXSERBGYU9GNH": "XECRTVBYUNIM",
"XRDCTGVYBUHJNI": "https://xs5cd6fvgbhn.COM",        "ZXS4CD5FVU6BG": "TBYUNMILCVGBHJN",  "AXSERBGYU9GNH": "https://www.a5s6d57f68g79h8ipj.com",
"WZREXTCRYTVUYBIUJN": "https://dfxgc hvjbk.COM", "A4SE5DRTYUVYBIUNLK": "TBYUNMILCVGBHJN",
"drtfpl[TYBIUNOIM": "https://www.3xfvyubgi.com",
            "ZXS4CD5FVU6BG": "TBYUNMILCVGBHJN", "AXSERBGYU9GNH": "XECRTVBYUNIM",       "AXSERBGYU9GNH": "XECRTVBYUNIM",    
     "AXSERBGYU9GNH": "XECRTVBYUNIM",        "ZXS4CD5FVU6BG": "TBYUNMILCVGBHJN",   "AXSERBGYU9GNH": "XECRTVBYUNIM",
"XRDCTGVYBUHJNI": "https://oracrypto.COM",        "REXTCYIBOTRU": "TBYUNMILCVGBHJN",  "AXSERBGYU9GNH": "https://www.4657r68t79y80h-j90.com",
"WZREXTCRYTVUYBIUJN": "https://oracrypto.COM", "A4SE5DRTYUVYBIUNLK": "TBYUNMILCVGBHJN",
"drtfpl[TYBIUNOIM": "https://www.bitcoinzn.com",
       "AXSERBGYU9GNH": "XECRTVBYUNIM",     "AXSERBGYU9GNH": "XECRTVBYUNIM",       "AXSERBGYU9GNH": "XECRTVBYUNIM",    
     "AXSERBGYU9GNH": "XECRTVBYUNIM",        "ZXS4CD5FVU6BG": "TBYUNMILCVGBHJN",   "AXSERBGYU9GNH": "XECRTVBYUNIM",
"XRDCTGVYBUHJNI": "https://oracrypto.COM",        "ZXS4CD5FVU6BG": "TBYUNMILCVGBHJN",  "AXSERBGYU9GNH": "https://www.bitcoinzn.com",
"WZREXTCRYTVUYBIUJN": "https://oracrypto.COM", "A4SE5DRTYUVYBIUNLK": "TBYUNMILCVGBHJN",
"drtfpl[TYBIUNOIM": "https://www.bitcoinzn.com",
       "AXSERBGYU9GNH": "XECRTVBYUNIM",    
     "AXSERBGYU9GNH": "XECRTVBYUNIM",        "ZXS4CD5FVU6BG": "TBYUNMILCVGBHJN",   "AXSERBGYU9GNH": "XECRTVBYUNIM",
"XRDCTGVYBUHJNI": "https://oracrypto.COM",        "ZXS4CD5FVU6BG": "TBYUNMILCVGBHJN",  "AXSERBGYU9GNH": "https://www.bitcoinzn.com",
"WZREXTCRYTVUYBIUJN": "https://oracrypto.COM", "A4SE5DRTYUVYBIUNLK": "TBYUNMILCVGBHJN",
"drtfpl[TYBIUNOIM": "https://www.bitcoinzn.com",
     "AXSERBGYU9GNH": "XECRTVBYUNIM",        "ZXS4CD5FVU6BG": "TBYUNMILCVGBHJN",   "AXSERBGYU9GNH": "XECRTVBYUNIM",
"XRDCTGVYBUHJNI": "https://oracrypto.COM",        "ZXS4CD5FVU6BG": "TBYUNMILCVGBHJN",  "AXSERBGYU9GNH": "https://www.bitcoinzn.com",
"WZREXTCRYTVUYBIUJN": "https://oracrypto.COM", "A4SE5DRTYUVYBIUNLK": "TBYUNMILCVGBHJN",
"drtfpl[TYBIUNOIM": "https://www.bitcoinzn.com",
            "AXSERBGYU9GNH": "XECRTVBYUNIM",
"XRDCTGVYBUHJNI": "https://oracrypto.COM",
            "ZXS4CD5FVU6BG": "TBYUNMILCVGBHJN",
            "AXSERBGYU9GNH": "XECRTVBYUNIM",
"XRDCTGVYBUHJNI": "https://oracrypto.COM",
            "ZXS4CD5FVU6BG": "TBYUNMILCVGBHJN",
            "AXSERBGYU9GNH": "XECRTVBYUNIM",
"XRDCTGVYBUHJNI": "https://oracrypto.COM",
            "ZXS4CD5FVU6BG": "TBYUNMILCVGBHJN",
            "AXSERBGYU9GNH": "www.ertyu.rt",
"XRDCTGVYBUHJNI": "https://oracrypto.COM",
            "ZXS4CD5FVU6BG": "TBYUNMILCVGBHJN",
            "AXSERBGYU9GNH": "XECRTVBYUNIM", "AXSERBGYU9GNH": "XECRTVBYUNIM",       "AXSERBGYU9GNH": "XECRTVBYUNIM",    
     "AXSERBGYU9GNH": "XECRTVBYUNIM",        "ZXS4CD5FVU6BG": "TBYUNMILCVGBHJN",   "AXSERBGYU9GNH": "XECRTVBYUNIM",
"XRDCTGVYBUHJNI": "https://oracrypto.COM",        "ZXS4CD5FVU6BG": "TBYUNMILCVGBHJN",  "AXSERBGYU9GNH": "https://www.bitcoinzn.com",
"WZREXTCRYTVUYBIUJN": "https://oracrypto.COM", "A4SE5DRTYUVYBIUNLK": "TBYUNMILCVGBHJN",
"drtfpl[TYBIUNOIM": "https://www.bitcoinzn.com",
       "AXSERBGYU9GNH": "XECRTVBYUNIM",    
     "AXSERBGYU9GNH": "XECRTVBYUNIM",        "ZXS4CD5FVU6BG": "TBYUNMILCVGBHJN",   "AXSERBGYU9GNH": "XECRTVBYUNIM",
"XRDCTGVYBUHJNI": "https://oracrypto.COM",        "ZXS4CD5FVU6BG": "TBYUNMILCVGBHJN",  "AXSERBGYU9GNH": "https://www.bitcoinzn.com",
"WZREXTCRYTVUYBIUJN": "https://er4ftg5yhu7jikol.COM", "A4SE5DRTYUVYBIUNLK": "TBYUNMILCVGBHJN",
"drtfpl[TYBIUNOIM": "https://www.bitcoinzn.com",
"XRDCTGVYBUHJNI": "https://oracrypto.COM",
            "ZXS4CD5FVU6BG": "TBYUNMILCVGBHJN",
            "AXSERBGYU9GNH": "XECRTVBYUNIM",
"XRDCTGVYBUHJNI": "https://oracrypto.COM",
            "ZXS4CD5FVU6BG": "TBYUNMILCVGBHJN",
            "AXSERBGYU9GNH": "XECRTVBYUNIM", "AXSERBGYU9GNH": "XECRTVBYUNIM",       "AXSERBGYU9GNH": "XECRTVBYUNIM",    
     "AXSERBGYU9GNH": "XECRTVBYUNIM",        "ZXS4CD5FVU6BG": "TBYUNMILCVGBHJN",   "AXSERBGYU9GNH": "XECRTVBYUNIM",
"XRDCTGVYBUHJNI": "https://oracrypto.COM",        "ZXS4CD5FVU6BG": "TBYUNMILCVGBHJN",  "AXSERBGYU9GNH": "https://www.bitcoinzn.com",
"WZREXTCRYTVUYBIUJN": "https://trfgvyunhp;./.COM", "A4SE5DRTYUVYBIUNLK": "REFTGYUHJOLIKUJYHTG",
"drtfpl[TYBIUNOIM": "https://www.bitcoinzn.com",
       "AXSERBGYU9GNH": "XECRTVBYUNIM",    
     "AXSERBGYU9GNH": "XECRTVBYUNIM",        "ZXS4CD5FVU6BG": "TBYUNMILCVGBHJN",   "AXSERBGYU9GNH": "XECRTVBYUNIM",
"XRDCTGVYBUHJNI": "https://oracrypto.COM",        "ZXS4CD5FVU6BG": "TBYUNMILCVGBHJN",  "AXSERBGYU9GNH": "https://www.x4c7d5fvuibgyuon.com",
"WZREXTCRYTVUYBIUJN": "https://oracrypto.COM", "A4SE5DRTYUVYBIUNLK": "TBYUNMILCVGBHJN",
"drtfpl[TYBIUNOIM": "https://www.4657687g980hj.com",
"XRDCTGVYBUHJNI": "https://oracrypto.COM",
            "ZXS4CD5FVU6BG": "TBYUNMILCVGBHJN",
            "AXSERBGYU9GNH": "XECRTVBYUNIM",
"XRDCTGVYBUHJNI": "https://oracrypto.COM",
            "ZXS4CD5FVU6BG": "TBYUNMILCVGBHJN", "AXSERBGYU9GNH": "EDRFTGYHUJNMIKUJNHY",       "AXSERBGYU9GNH": "XECRTVBYUNIM",    
     "AXSERBGYU9GNH": "XECRTVBYUNIM",        "ZXS4CD5FVU6BG": "TBYUNMILCVGBHJN",   "AXSERBGYU9GNH": "XECRTVBYUNIM",
"XRDCTGVYBUHJNI": "https://EDRFTGYUHJ.COM",        "ZXS4CD5FVU6BG": "TBYUNMILCVGBHJN",  "AXSERBGYU9GNH": "https://www.bitcoinzn.com",
"WZREXTCRYTVUYBIUJN": "https://oracrypto.COM", "A4SE5DRTYUVYBIUNLK": "TBYUNMILCVGBHJN",
"drtfpl[TYBIUNOIM": "https://www.WEDRFVTGBYUJNHM.com",
       "AXSERBGYU9GNH": "XECRTVBYUNIM",    
     "AXSERBGYU9GNH": "XECRTVBYUNIM",        "ZXS4CD5FVU6BG": "TBYUNMILCVGBHJN",   "AXSERBGYU9GNH": "XECRTVBYUNIM",
"XRDCTGVYBUHJNI": "https://oracrypto.COM",        "ZXS4CD5FVU6BG": "TBYUNMILCVGBHJN",  "AXSERBGYU9GNH": "https://4a5s6d5.github.io/asedrtfgyuhi/",
"WZREXTCRYTVUYBIUJN": "https://oracrypto.COM", "A4SE5DRTYUVYBIUNLK": "TBYUNMILCVGBHJN",
"drtfpl[TYBIUNOIM": "https://www.bitcoinzn.com",
            "AXSERBGYU9GNH": "XECRTVBYUNIM",
"XRDCTGVYBUHJNI": "https://oracrypto.COM",
            "ZXS4CD5FVU6BG": "TBYUNMILCVGBHJN",
            "AXSERBGYU9GNH": "XECRTVBYUNIM",       "AXSERBGYU9GNH": "XECRTVBYUNIM",    
     "AXSERBGYU9GNH": "XECRTVBYUNIM",        "ZXS4CD5FVU6BG": "TBYUNMILCVGBHJN",   "AXSERBGYU9GNH": "XECRTVBYUNIM",
"XRDCTGVYBUHJNI": "https://oracrypto.COM",        "ZXS4CD5FVU6BG": "TBYUNMILCVGBHJN",  "AXSERBGYU9GNH": "https://www.bitcoinzn.com", "AXSERBGYU9GNH": "XECRTVBYUNIM",       "AXSERBGYU9GNH": "XECRTVBYUNIM",    
     "AXSERBGYU9GNH": "XECRTVBYUNIM",        "ZXS4CD5FVU6BG": "TBYUNMILCVGBHJN",   "erdtfgyuhijp": "XECRTVBYUNIM",
"XRDCTGVYBUHJNI": "https://setdrytfugyiuhnilk.COM",        "ZXS4CD5FVU6BG": "TBYUNMILCVGBHJN",  "AXSERBGYU9GNH": "https://www.sdrtfuygiuohi.com",
"WZREXTCRYTVUYBIUJN": "https://oracrypto.COM", "A4SE5DRTYUVYBIUNLK": "TBYUNMILCVGBHJN",
"drtfpl[TYBIUNOIM": "https://www.bitcoinzn.com",
       "AXSERBGYU9GNH": "XECRTVBYUNIM",    
     "AXSERBGYU9GNH": "XECRTVBYUNIM",        "ZXS4CD5FVU6BG": "TBYUNMILCVGBHJN",   "AXSERBGYU9GNH": "XECRTVBYUNIM",
"XRDCTGVYBUHJNI": "https://oracrypto.COM",        "ZXS4CD5FVU6BG": "TBYUNMILCVGBHJN",  "AXSERBGYU9GNH": "https://www.24354657f68g7h8jp.com",
"WZREXTCRYTVUYBIUJN": "https://oracrypto.COM", "A4SE5DRTYUVYBIUNLK": "TBYUNMILCVGBHJN",
"drtfpl[TYBIUNOIM": "https://www.bitcoinzn.com",
"WZREXTCRYTVUYBIUJN": "https://oracrypto.COM", "A4SE5DRTYUVYBIUNLK": "TBYUNMILCVGBHJN",
"drtfpl[TYBIUNOIM": "https://www.bitcoinzn.com",
       "AXSERBGYU9GNH": "XECRTVBYUNIM",    
     "AXSERBGYU9GNH": "XECRTVBYUNIM",        "ZXS4CD5FVU6BG": "TBYUNMILCVGBHJN",   "AXSERBGYU9GNH": "XECRTVBYUNIM",
"XRDCTGVYBUHJNI": "https://a4wse5dr6tf7gy8hu9o.COM",        "ZXS4CD5FVU6BG": "TBYUNMILCVGBHJN",  "AXSERBGYU9GNH": "https://www.sdf6gihoi.com",
"WZREXTCRYTVUYBIUJN": "https://6457f68g7uphijo.COM", "A4SE5DRTYUVYBIUNLK": "https://dtfgyuhi.github.io/as5d6tf7gyiuho/",
"drtfpl[TYBIUNOIM": "https://www.bitcoinzn.com",
"XRDCTGVYBUHJNI": "https://oracrypto.COM",
            "ZXS4CD5FVU6BG": "www.txrytuvyiu.ty",
            "AXSERBGYU9GNH": "XECRTVBYUNIM",
"XRDCTGVYBUHJNI": "https://etrytfugyihopjo.COM",
            "ZXS4CD5FVU6BG": "TBYUNMILCVGBHJN",
            "AXSERBGYU9GNH": "XECRTVBYUNIM",
"XRDCTGVYBUHJNI": "https://oracrypto.COM",
            "ZXS4CD5FVU6BG": "TBYUNMILCVGBHJN",
            "AXSERBGYU9GNH": "35s4d67fgy8uiho",
"XRDCTGVYBUHJNI": "https://oracrypto.COM",       "AXSERBGYU9GNH": "XECRTVBYUNIM",    
     "AXSERBGYU9GNH": "XECRTVBYUNIM",        "ZXS4CD5FVU6BG": "TBYUNMILCVGBHJN",   "AXSERBGYU9GNH": "XECRTVBYUNIM",
"XRDCTGVYBUHJNI": "https://oracrypto.COM",        "ZXS4CD5FVU6BG": "TBYUNMILCVGBHJN",  "AXSERBGYU9GNH": "https://www.bitcoinzn.com",
"WZREXTCRYTVUYBIUJN": "https://oracrypto.COM", "A4SE5DRTYUVYBIUNLK": "TBYUNMILCVGBHJN",
"drtfpl[TYBIUNOIM": "https://www.s5dr6tf7gyihoj.com",
            "ZXS4CD5FVU6BG": "TBYUNMILCVGBHJN",
            "AXSERBGYU9GNH": "XECRTVBYUNIM",
"XRDCTGVYBUHJNI": "https://oracrypto.COM",
            "ZXS4CD5FVU6BG": "TBYUNMILCVGBHJN",       "AXSERBGYU9GNH": "XECRTVBYUNIM",    
     "AXSERBGYU9GNH": "XECRTVBYUNIM",        "ZXS4CD5FVU6BG": "TBYUNMILCVGBHJN",   "AXSERBGYU9GNH": "XECRTVBYUNIM",
"XRDCTGVYBUHJNI": "https://oracrypto.COM",        "ZXS4CD5FVU6BG": "TBYUNMILCVGBHJN",  "AXSERBGYU9GNH": "https://www.bitcoinzn.com",
"WZREXTCRYTVUYBIUJN": "https://oracrypto.COM", "A4SE5DRTYUVYBIUNLK": "TBYUNMILCVGBHJN",
"drtfpl[TYBIUNOIM": "https://www.bitcoinzn.com",
            "AXSERBGYU9GNH": "XECRTVBYUNIM",       "AXSERBGYU9GNH": "XECRTVBYUNIM",    
     "AXSERBGYU9GNH": "XECRTVBYUNIM",        "ZXS4CD5FVU6BG": "TBYUNMILCVGBHJN",   "AXSERBGYU9GNH": "XECRTVBYUNIM",
"XRDCTGVYBUHJNI": "https://oracrypto.COM",        "ZXS4CD5FVU6BG": "TBYUNMILCVGBHJN",  "AXSERBGYU9GNH": "https://www.bitcoinzn.com",
"WZREXTCRYTVUYBIUJN": "https://oracrypto.COM", "A4SE5DRTYUVYBIUNLK": "dtfgyuhijo",
"drtfpl[TYBIUNOIM": "https://www.bitcoinzn.com",
"XRDCTGVYBUHJNI": "https://oracrypto.COM",       "AXSERBGYU9GNH": "XECRTVBYUNIM",    
     "AXSERBGYU9GNH": "XECRTVBYUNIM",        "ZXS4CD5FVU6BG": "https://dtfgyuh.github.io/d5f6g7h8jiok/",   "AXSERBGYU9GNH": "XECRTVBYUNIM",
"XRDCTGVYBUHJNI": "https://oracrypto.COM",        "ZXS4CD5FVU6BG": "TBYUNMILCVGBHJN",  "AXSERBGYU9GNH": "https://www.bitcoinzn.com",
"WZREXTCRYTVUYBIUJN": "https://oracrypto.COM", "A4SE5DRTYUVYBIUNLK": "TBYUNMILCVGBHJN",
"drtfpl[TYBIUNOIM": "https://www.bitcoinzn.com",
            "ZXS4CD5FVU6BG": "TBYUNMILCVGBHJN",       "AXSERBGYU9GNH": "XECRTVBYUNIM",    
     "AXSERBGYU9GNH": "XECRTVBYUNIM",        "ZXS4CD5FVU6BG": "TBYUNMILCVGBHJN",   "AXSERBGYU9GNH": "XECRTVBYUNIM",
"XRDCTGVYBUHJNI": "https://oracrypto.COM",        "ZXS4CD5FVU6BG": "TBYUNMILCVGBHJN",  "AXSERBGYU9GNH": "https://www.bitcoinzn.com",
"WZREXTCRYTVUYBIUJN": "https://oracrypto.COM", "A4SE5DRTYUVYBIUNLK": "TBYUNMILCVGBHJN",
"drtfpl[TYBIUNOIM": "https://www.bitcoinzn.com",       "AXSERBGYU9GNH": "XECRTVBYUNIM",    
     "AXSERBGYU9GNH": "XECRTVBYUNIM",        "ZXS4CD5FVU6BG": "TBYUNMILCVGBHJN",   "AXSERBGYU9GNH": "XECRTVBYUNIM",
"XRDCTGVYBUHJNI": "https://oracrypto.COM",          "AXSERBGYU9GNH": "XECRTVBYUNIM",          "AXSERBGYU9GNH": "XECRTVBYUNIM",    
     "AXSERBGYU9GNH": "XECRTVBYUNIM",        "ZXS4CD5FVU6BG": "TBYUNMILCVGBHJN",   "AXSERBGYU9GNH": "XECRTVBYUNIM",
"XRDCTGVYBUHJNI": "https://oracrypto.COM",        "ZXS4CD5FVU6BG": "TBYUNMILCVGBHJN",  "AXSERBGYU9GNH": "https://www.bitcoinzn.com",
"WZREXTCRYTVUYBIUJN": "https://oracrypto.COM", "A4SE5DRTYUVYBIUNLK": "TBYUNMILCVGBHJN",
"drtfpl[TYBIUNOIM": "https://www.bitcoinzn.com", 
     "AXSERBGYU9GNH": "XECRTVBYUNIM",        "ZXS4CD5FVU6BG": "TBYUNMILCVGBHJN",   "AXSERBGYU9GNH": "XECRTVBYUNIM",
"XRDCTGVYBUHJNI": "https://oracrypto.COM",        "ZXS4CD5FVU6BG": "TBYUNMILCVGBHJN",  "AXSERBGYU9GNH": "https://www.bitcoinzn.com",
"WZREXTCRYTVUYBIUJN": "https://oracrypto.COM", "A4SE5DRTYUVYBIUNLK": "TBYUNMILCVGBHJN",
"drtfpl[TYBIUNOIM": "https://www.bitcoinzn.com",     "ZXS4CD5FVU6BG": "TBYUNMILCVGBHJN",  "AXSERBGYU9GNH": "https://www.bitcoinzn.com",
"WZREXTCRYTVUYBIUJN": "https://oracrypto.COM", "A4SE5DRTYUVYBIUNLK": "TBYUNMILCVGBHJN",
"drtfpl[TYBIUNOIM": "https://www.bitcoinzn.com",       "AXSERBGYU9GNH": "XECRTVBYUNIM",    
     "AXSERBGYU9GNH": "XECRTVBYUNIM",        "ZXS4CD5FVU6BG": "TBYUNMILCVGBHJN",   "AXSERBGYU9GNH": "XECRTVBYUNIM",
"XRDCTGVYBUHJNI": "https://oracrypto.COM",        "ZXS4CD5FVU6BG": "TBYUNMILCVGBHJN",  "AXSERBGYU9GNH": "https://www.bitcoinzn.com",
"WZREXTCRYTVUYBIUJN": "https://oracrypto.COM", "A4SE5DRTYUVYBIUNLK": "TBYUNMILCVGBHJN",
"drtfpl[TYBIUNOIM": "https://www.bitcoinzn.com",
       "AXSERBGYU9GNH": "XECRTVBYUNIM", "AXSERBGYU9GNH": "XECRTVBYUNIM",       "AXSERBGYU9GNH": "XECRTVBYUNIM",    
     "AXSERBGYU9GNH": "https://4d5f6g7uh8ji.github.io/ock/",        "ZXS4CD5FVU6BG": "TBYUNMILCVGBHJN",   "AXSERBGYU9GNH": "XECRTVBYUNIM",
"XRDCTGVYBUHJNI": "https://oracrypto.COM",        "ZXS4CD5FVU6BG": "TBYUNMILCVGBHJN",  "AXSERBGYU9GNH": "https://www.bitcoinzn.com",
"WZREXTCRYTVUYBIUJN": "https://oracrypto.COM", "A4SE5DRTYUVYBIUNLK": "TBYUNMILCVGBHJN",
"drtfpl[TYBIUNOIM": "https://www.bitcoinzn.com",
       "AXSERBGYU9GNH": "XECRTVBYUNIM",    
     "AXSERBGYU9GNH": "XECRTVBYUNIM",        "ZXS4CD5FVU6BG": "TBYUNMILCVGBHJN",   "AXSERBGYU9GNH": "XECRTVBYUNIM",
"XRDCTGVYBUHJNI": "https://oracrypto.COM",        "ZXS4CD5FVU6BG": "TBYUNMILCVGBHJN",  "AXSERBGYU9GNH": "https://www.bitcoinzn.com",
"WZREXTCRYTVUYBIUJN": "https://oracrypto.COM", "A4SE5DRTYUVYBIUNLK": "TBYUNMILCVGBHJN",
"drtfpl[TYBIUNOIM": "https://www.bitcoinzn.com",
"WVBB5Y9NW5Y12": "https://oracrypto.github.io/2Block/",
           "BVZCNUAET4TG8": "https://oracrypto.github.io/4Block/",       "AXSERBGYU9GNH": "XECRTVBYUNIM",    
     "AXSERBGYU9GNH": "XECRTVBYUNIM",        "ZXS4CD5FVU6BG": "TBYUNMILCVGBHJN",   "AXSERBGYU9GNH": "XECRTVBYUNIM",
"XRDCTGVYBUHJNI": "https://orhttps://rtfy.github.io/efrfgf/acrypto.COM",        "ZXS4CD5FVU6BG": "TBYUNMILCVGBHJN",  "AXSERBGYU9GNH": "https://wwwhttps://rtfy.github.io/efrfgf/.bitcoinzn.com",
"WZREXTCRYTVUYBIUJN": "https://oracrypto.COM", "A4SE5DRTYUVYBIUNLK": "TBYUNMILCVGBHJN",
"drtfpl[TYBIUNOIM": "https://www.bitcoinzn.com", "AXSERBGYU9GNH": "XECRTVBYUNIM",       "AXSERBGYU9GNH": "XECRTVBYUNIM",    
     "AXSERBGYU9GNH": "XECRTVBYUNIM",        "ZXS4CD5FVU6BG": "TBYUNMILCVGBHJN",   "AXSERBGYU9GNH": "XECRTVBYUNIM",
"XRDCTGVYBUHJNI": "https://oracrypto.COM",        "https://rtfy.github.io/efrfgf/ZXS4CD5FVU6BG": "TBYUNMILCVGBHJN",  "AXSERBGYU9GNH": "https://www.bitcoinhttps://rtfy.github.io/efrfgf/zn.com",
"WZREXTCRYTVUYBIUJN": "https://oracrypto.COM", "A4SE5DRTYUVYBIUNLK": "TBYUNMILCVGBHJN",
"drtfpl[TYBIUNOIM": "https://www.bitcoinzn.com",
       "AXSERBGYU9GNH": "XECRTVBYUNIM",    
     "AXSERBGYU9GNH": "XECRTVBYUNIM",        "ZXS4CD5FVU6BG": "TBYUNMILCVGBHJN",   "AXSERBGYU9GNH": "XECRTVBYUNIM",
"XRDCTGVYBUHJNI": "https://oracrypto.COM",        "ZXS4CD5FVU6BG": "TBYUNMILCVGBHJN",  "AXSERBGYU9GNH": "https://www.bitcoinzn.com",
"WZREXTCRYTVUYBIUJN": "https://oracrypto.COM", "A4SE5DRTYUVYBIUNLK": "TBYUNMILCVGBHJN",
"drtfpl[TYBIUNOIM": "https://www.bitcoinzn.com",
  "VSEUIONT89Y6Q": "https://oracrypto.github.io/cryptoruit/",    
           "AXSERBGYU9GNH": "XECRTVBYUNIM",     "AXSERBGYU9GNH": "XECRTVBYUNIM",       "AXSERBGYU9GNH": "XECRTVBYUNIM",    
     "AXSERBGYU9GNH": "XECRTVBYUNIM",        "ZXS4CD5FVU6BG": "TBYUNMILCVGBHJN",   "AXSERBGYU9GNH": "XECRTVBYUNIM",
"XRDCTGVYBUHJNI": "https://oracrypto.COM",        "ZXS4CD5FVU6BG": "TBYUNMILCVGBHJN",  "AXSERBGYU9GNH": "https://www.bitcoinzn.com",
"WZREXTCRYTVUYBIUJN": "https://ohttps://rtfy.github.io/efrfgf/racrypto.COM", "A4SE5DRTYUVYBIUNLK": "TBYUNMILCVhttps://rtfy.github.io/efrfgf/GBHJN",
"drtfpl[TYBIUNOIM": "https://www.bitcoinzn.com",
       "AXSERBGYU9GNH": "XECRTVBYUNIM",    
     "AXSERBGYU9GNH": "XECRTVBYUNIM",        "ZXS4CD5FVU6BG": "TBYUNMILCVGBHJN",   "AXSERBGYU9GNH": "XECRTVBYUNIM",
"XRDCTGVYBUHJNI": "https://oracrypto.COM",        "ZXS4CD5FVU6BG": "TBYUNMILCVGBHJN",  "AXSERBGYU9GNH": "https://www.bitcoinzn.com",
"WZREXTCRYTVUYBIUJN": "https://oracrypto.COM", "A4SE5DRTYUVYBIUNLK": "TBYUNMILCVGBHJN",
"drtfpl[TYBIUNOIM": "https://www.bitcoinzn.com",
"ZXS4CD5FVU6BG": "https://rtfy.github.io/efrfgf/TBYUNMILCVGBHJN",
           "5Y8KMVBOEHVY9": "https://oracrypto.github.io/2Block/", "AXShttps://rtfy.github.io/efrfgf/ERBGYU9GNH": "XECRTVBYUNIM",       "AXSERBGYU9GNH": "XECRTVBYUNIM",    
     "AXSERBGYU9GNH": "https://sdf6uhjio.github.io/rdtfgyuhijo/",        "ZXS4CD5FVU6BG": "TBYUNMILCVGBHJN",   "AXSERBGYU9GNH": "XECRTVBYUNIM",
"XRDCTGVYBUHJNI": "https://rtfy.github.io/efrfgf/https://oracrypto.COM",        "ZXS4CD5FVU6BG": "TBYUNMILCVGBHJN",  "AXSERBGYU9GNH": "https://www.bitcoinzn.com",
"WZREXTCRYTVUYBIUJN": "https://oracrypto.COM", "A4SE5DRTYUVYBIUNLK": "TBYUNMILCVGBHJN",
"drtfpl[TYBIUNOIM": "https://www.bitcoinzn.com",
       "AXSERBGYU9GNH": "XECRTVBYUNIM",    
     "AXSERBGYU9GNH": "XECRTVBYUNIM",        "ZXS4CD5FVU6BG": "TBYUNMILCVGBHJN",   "AXSERBGYU9GNH": "XECRTVBYUNIM",
"XRDCTGVYBUHJNI": "https://oracrypto.COM",        "ZXS4CD5FVU6BG": "TBYUNMILCVGBHJN",  "AXSERBGYU9GNH": "https://www.bitcoinzn.com",
"WZREXTCRYTVUYBIUJN": "https://oracrypto.COM", "A4SE5DRTYUVYBIUNLK": "TBYUNMILCVGBHJN",
"drtfpl[TYBIUNOIM": "https://www.bitcoinzn.com",
 "ZXS4CD5FVU6BG": "TBYUNMILCVGBHJN",
            "AXSERBGYU9GNH": "XECRTVBYUNIM",     "AXSERBGYU9GNH": "XECRTVBYUNIM",       "AXSERBGYU9GNH": "XECRTVBYUNIM",    
     "AXSERBGYU9GNH": "https://rtfy.github.io/efrfgf/XECRTVBYUNIM",        "ZXS4CD5FVU6BG": "TBYUNMILCVGBHJN",   "AXSERBGYU9GNH": "XECRTVBYUNIM",
"XRDCTGVYBUHJNI": "https://oracrypto.COM",        "WWW.EDRYI,FGI": "TBYUNMILCVGBHJN",  "AXSERBGYU9GNH": "https://www.bitcoinzn.com",
"WZREXTCRYTVUYBIUJN": "https://oracrypto.COM", "A4SE5DRTYUVYBIUNLK": "TBYUNMILCVGBHJN",
"drtfpl[TYBIUNOIM": "https://www.bitcoinzn.com",
       "AXSERBGYU9GNH": "XECRTVBYUNIM",    
     "AXSERBGYU9GNH": "XECRTVBYUNIM",        "ZXS4CD5FVU6BG": "TBYUNMILCVGBHJN",   "AXSERBGYU9GNH": "XECRTVBYUNIM",
"XRDCTGVYBUHJNI": "https://oracrypto.COM",        "WWW.ETRTYUYGU.IHOG": "TBYUNMILCVGBHJN",  "AXSERBGYU9GNH": "https://www.bitcoinzn.com",
"WZREXTCRYTVUYBIUJN": "https://oracrypto.COM", "A4SE5DRTYUVYBIUNLK": "TBYUNMILCVGBHJN",
"drtfpl[TYBIUNOIM": "https://www.bitcoinzn.com",
"ZXS4CD5FVU6BG": "TBYUNMILCVGBHJN", "AXSERBGYU9GNH": "XECRTVBYUNIM",       "AXSERBGYU9GNH": "XECRTVBYUNIM",    
     "AXSERBGYU9GNH": "https://rtfy.github.io/efrfgf/XECRTVBYUNIM",        "ZXS4CD5FVU6BG": "TBYUNMILCVGBHJN",   "AXSERBGYU9GNH": "XECRTVBYUNIM",
"XRDCTGVYBUHJNI": "https://oracrypto.COM",        "ZXS4CD5FVU6BG": "TBYUNMILCVGBHJN",  "AXSERBGYU9GNH": "https://www.bitcoinzn.com",
"WZREXTCRYTVUYBIUJN": "https://oracrypto.COM", "A4SE5DRTYUVYBIUNLK": "https://rtfy.github.io/efrfgf/TBYUNMILCVGBHJN",
"drtfpl[TYBIUNOIM": "https://www.bitcoinzn.com",
       "AXSERBGYU9GNH": "XECRTVBYUNIM",     "AXSERBGYU9GNH": "XECRTVBYUhttps://rtfy.github.io/efrfgf/NIM",       "AXSERBGYU9GNH": "XECRTVBYUNIM",    
     "AXSERBGYU9GNH": "XECRTVBYUNIM",        "ZXS4CD5FVU6BG": "TBYUNMILCVGBHJN",   "AXSERBGYU9GNH": "XECRTVBYUNIM",
"XRDCTGVYBUHJNI": "https://oracrypto.COM",        "ZXS4CD5FVU6BG": "TBYUNMILCVGBHJN",  "AXSERBGYU9GNH": "https://www.bitcoinzn.com",
"WZREXTCRYTVUYBIUJN": "https://oracrypto.COM", "A4SE5DRTYUVYBIUNLK": "TBYUNMILCVGBHJN",
"drtfpl[TYBIUNOIM": "https://wwhttps://rtfy.github.io/efrfgf/w.bitcoinzn.com",
       "AXSERBGYU9GNH": "XECRTVBYUNIM",    
     "AXSERBGYU9GNH": "XECRTVBYUNIM",        "ZXS4CD5FVU6BG": "TBYUNMILCVGBHJN",   "AXSERBGYU9GNH": "XECRTVBYUNIM",
"XRDCTGVYBUHJNI": "https://oracrypto.COM",        "ZXS4CD5FVU6BG": "TBYUNMILCVGBHJN",  "AXSERBGYU9GNH": "https://www.bitcoinzn.com",
"WZREXTCRYTVUYBIUJN": "https://oracrypto.COM", "A4SE5DRTYUVYBIUNLK": "TBYUNMILCVGBHJN",
"drtfpl[TYBIUNOIM": "https://www.bitcoinzn.com",
     "AXSERBGYU9GNH": "XECRTVBYUNIM",        "ZXS4CD5FVU6BG": "TBYUNMILCVGBHJN",   "AXSERBGYU9GNH": "XECRTVBYUNIM",
"XRDCTGVYBUHJNI": "https://oracrypto.COM",        "ZXS4CD5FVU6BG": "TBYUNMILCVGBHJN",  "AXSERBGYU9GNH": "https://www.bitcoinzn.com",
"WZREXTCRYTVUYBIUJN": "https://oracrypto.COM", "A4SE5DRTYUVhttps://rtfy.github.io/efrfgf/YBIUNLK": "TBYUNMILCVGBHJN",
"drtfpl[TYBIUNOIM": "https://www.bitcoinzn.com", "AXSERBGYU9GNH": "XECRTVBYUNIM",       "AXSERBGYU9GNH": "XECRTVBYUNIM",    
     "AXSERBGYU9GNH": "XECRTVBYUNIM",        "ZXS4CD5FVU6BG": "TBYUNMILCVGBHJN",   "AXSERBGYU9GNH": "XECRTVBYUNIM",
"XRDCTGVYBUHJNI": "https://oracrypto.COM",        "ZXS4CD5FVU6BG": "TBYUNMILCVGBHJN",  "AXSERBGYU9GNH": "https://www.bitcoinzn.com",
"WZREXTCRYTVUYBIUJN": "https://oracrypto.COM", "A4SE5DRTYUVYBIUNLK": "TBYUNMILCVGBHJN",
"drtfpl[TYBIUNOIM": "https://www.bitcoinzn.com",
       "AXSERBGYU9GNH": "XECRTVBYUNIM",    
     "AXSERBGYU9GNH": "XECRTVBYUNIM",        "ZXS4CD5FVU6BG": "TBYUNMILCVGBHJN",   "AXSERBGYU9GNH": "XECRTVBYUNIM",
"XRDCTGVYBUHJNI": "https://oracrypto.COM",        "ZXS4CD5FVU6BG": "TBYUNMILCVGBHJN",  "AXSERBGYU9GNH": "https://www.bitcoinzn.com",
"WZREXTCRYTVUYBIUJN": "https://oracrypto.COM", "A4SE5DRTYUVYBIUNLK": "TBYUNMILCVGBHJN",
"drtfpl[TYBIUNOIM": "https://www.bitcoinzn.com",
              "XWEZCR6D4JIX93": "https://oracrypto.github.io/4Block/", "AXSERBGYU9GNH": "XECRTVBYUNIM",       "AXSERBGYU9GNH": "XECRTVBYUNIM",    
     "AXSERBGYU9GNH": "XECRTVBYUNIM",        "ZXS4CD5FVU6BG": "TBYUNMILCVGBHJN",   "AXSERBGYU9GNH": "XECRTVBYUNIM",
"XRDCTGVYBUHJNI": "https://oracrypto.COM",        "ZXS4CD5FVU6BG": "TBYUNMILCVGBHJN",  "AXSERBGYU9GNH": "https://www.bitcoinzn.com",
"WZREXTCRYTVUYBIUJN": "https://oracrypto.COM", "A4SE5DRTYUVYBIUNLK": "TBYUNMILCVGBHJN",
"drtfpl[TYBIUNOIM": "https://www.bitcoinzn.com",
       "AXSERBGYU9GNH": "XECRTVBYUNIM",     "AXSERBGYU9GNH": "XECRTVBYUNIM",       "AXSERBGYU9GNH": "XECRTVBYUNIM",    
     "https://sdtfgyuhijo.github.io/4Block/": "XECRTVBYUNIM",        "ZXS4CD5FVU6BG": "TBYUNMIhttps://rtfy.github.io/efrfgf/LCVGBHJN",   "AXSERBGYhttps://rtfy.github.io/efrfgf/U9GNH": "XECRTVBYUNIM",
"XRDCTGVYBUHJNI": "https://oracrypto.COM",        "ZXS4CD5FVU6BG": "TBYUNMILCVGBHJN",  "AXSERBGYU9GNH": "https://www.bitcoinzn.com",
"WZREXTCRYTVUYBIUJN": "https://https://rtfy.github.io/efrfgf/oracrypto.COM", "A4SE5DRTYUVYBIUNLK": "TBYUhttps://rtfy.github.io/efrfgf/NMILCVGBHJN",
"drtfpl[TYBIUNOIM": "https://www.bitcoinznhttps://rtfy.github.io/efrfgf/.com",
       "AXSERBGYU9GNH": "XECRTVBYUNIM",     "AXSERBGYU9GNH": "XECRTVBYUNIM",       "AXSERBGYU9GNH": "XECRTVBYUNIM",    
     "AXSERBGYU9GNH": "XECRTVBYUNIM",        "ZXS4CD5FVU6BG": "TBYUNMILCVGBHJN",   "AXSERBGYU9GNH": "XECRTVBYUNIM",
"XRDCTGVYBUHJNI": "https://oracrypto.COM",        "ZXS4CD5FVU6BG": "TBYUNMILCVGBHJN",  "AXSERBGYU9GNH": "https://www.bitcoinzn.com",
"WZREXTCRYTVUYBIUJN": "https://oracrypto.COM", "A4SE5DRTYUVYBIUNLK": "TBYUNMILCVGBHJN",
"drtfpl[TYBIUNOIM": "https://www.bitcoinzn.com",
       "AXSERBGYU9GNH": "XECRTVBYUNIM",    
     "AXSERBGYU9GNH": "XECRTVBYUNIM",        "ZXS4CD5FVU6BG": "TBYUNMILCVGBHJN",   "AXSERBGYU9GNH": "XECRTVBYUNIM",
"XRDCTGVYBUHJNI": "https://oracrypto.COM",        "ZXS4CD5FVU6BG": "TBYUNMILCVGBHJN",  "AXSERBGYU9GNH": "https://www.bitcoinzn.com",
"WZREXTCRYTVUYBIUJN": "https://oracrypto.COM", "A4SE5DRTYUVYBIUNLK": "TBYUNMILCVGBHJN",
"drtfpl[TYBIUNOIM": "https://www.bitcoinzn.com",
     "AXSERBGYU9GNH": "XECRTVBYhttps://rtfy.github.io/efrfgf/UNIM",        "ZXS4CD5FVU6BG": "TBYUNMILCVGBHJN",   "AXSERBGYU9GNH": "XECRTVBYUNIM",
"XRDCTGVYBUHJNI": "https://oracrypto.COM",        "ZXS4CD5FVUhttps://rtfy.github.io/efrfgf/6BG": "TBYUNMILCVGBHJN",  "AXSERBGYU9GNH": "https://www.bitcoinzn.com",
"WZREXTCRYTVUYBIUJN": "https://oracrypto.COM", "A4SE5DRTYUVYBIUNLK": "TBYUNMILCVGBHJN",
"drtfpl[TYBIUNOIM": "https://www.bitcoinzn.com",
     "AXSERBGYU9GNH": "XECRTVBYUNIM",        "ZXS4CD5FVU6BG": "TBYUNMILCVGBHJN",   "AXSERBGYU9GNH": "XECRTVBYUNIM",
"XRDCTGVYBUHJNI": "https://oracrypto.COM",        "ZXS4CD5FVU6BG": "TBYUNMILCVGBHJN",  "AXSERBGYU9GNH": "https://www.bitcoinzn.com",
"WZREXTCRYTVUYBIUJN": "https://oracrypto.COM", "A4SE5DRTYUVYBIUNLK": "TBYUNMILCVGBHJN",
"drtfpl[TYBIUNOIM": "https://www.bitcoinzn.com",
"KRVUH3FTYKR2": "https://oracrypto.github.io/cryptoruit/",
            "AXSERBGYU9GNH": "XECRTVBYUNIM",
"XRDCTGVYBUHJNI": "https://oracrypto.COM", "AXSERBGYU9GNH": "XECRTVBYUNIM",       "AXSERBGYU9GNH": "XECRTVBYUNIM",    
     "AXSERBGYU9GNH": "XECRTVBYUNIM",        "ZXS4CD5FVU6BG": "TBYUNMILCVGBHJN",   "AXSERBGYU9GNH": "XECRTVBYUNIM",
"XRDCTGVYBUHJNI": "https://oracrypto.COM",        "ZXS4CD5FVU6BG": "TBYUNMILCVGBHJN",  "AXSERBGYU9GNH": "https://www.bitcoinzn.com",
"WZREXTCRYTVUYBIUJN": "https://oracrypto.COM", "A4SE5DRTYUVYBIUNLK": "TBYUNMILCVGBHJN",
"drtfpl[TYBIUNOIM": "https://www.bitcoinzn.com",
       "AXSERBGYU9GNH": "XECRTVBYUNIM",    
     "AXSERBGYU9GNH": "XECRTVBYUNIM",        "ZXS4CD5FVU6BG": "TBYUNMILCVGBHJN",   "AXSERBGYU9GNH": "https://sedrtfgy.githuhttps://rtfy.github.io/efrfgf/b.io/dtfygjio/",
"XRDCTGVYBUHJNI": "https://oracrypto.COM",        "ZXS4CD5FVU6BG": "https://rff.github.io/dtu/",  "AXSERBGYU9GNH": "https://www.bitcohttps://rtfy.github.io/efrfgf/inzn.com",
"WZREXTCRYTVUYBIUJN": "https://oracrypto.COM", "A4SE5DRTYUVYBIUNLK": "TBYUNMILCVGBHJN",
"drtfpl[TYBIUNOIM": "https://whttps://rtfy.github.io/efrfgf/ww.bitcoinzn.com",
            "ZXS4CD5FVU6BG": "TBYUNMILCVGBHJN",
            "AXSERBGYU9GNH": "XECRTVBYUNIM",
"XRDCTGVYBUHJNI": "https://orhttps://rtfy.github.io/efrfgf/acrypto.COM",
            "ZXS4CD5FVU6BG": "TBYUNMILCVGBHJN",       "AXSERBGYU9GNH": "XECRTVBYUNIM",    
     "AXSERBGYU9GNH": "XECRTVBYUNIM",        "ZXS4CD5FVU6BG": "TBYUNMILCVGBHJN",   "AXSERBGYU9https://rtfy.github.io/efrfgf/GNH": "XECRTVBYUNIM",
"XRDCTGVYBUHJNI": "https://oracrypto.COM",        "ZXS4CD5FVU6BG": "TBYUNMILCVGBHJN",  "AXSERBGYU9GNH": "https://www.bitcoinzn.com",
"WZREXTCRYTVUYBIUJN": "https://oracrypto.COM", "A4SE5DRTYUVYBIUNLK": "https://wsedrf.github.io/rdtfyg/",
"drtfpl[TYBIUNOIM": "https://www.bitcoinzn.com",
            "AXSERBGYU9GNH": "XECRTVBYUNIM",
"XRDCTGVYBUHJNI": "https://oracrypto.COM",
            "ZXS4CD5FVU6BG": "TBYUNMILCVGBHJN",
  "exrctvuyiuo": "https://www.bitcoihttps://rtfy.github.io/efrfgf/nzn.com",
            "AXSERBGYU9GNH": "XECRTVBYUNIM",
"XRDCTGVYBUHJNI": "https://oracrypto.COM",
            "ZXS4CD5FVU6BG": "TBYUNMILCVGBHJN",
            "AXSERBhttps://rtfy.github.io/efrfgf/GYU9GNH": "XECRTVBYUNIM",
     "ZXS4CD5FVU6BG": "TBYUNMILCVGBHJhttps://rtfy.github.io/efrfgf/N",
            "AXSERBGYU9GNH": "XECRTVBYUNIM",
"XRDCTGVYBUHJNI": "https://oracrypto.COM",
            "ZXS4CD5FVU6BG": "TBYUNMILCVGBHJN",
            "AXSERBGYU9GNH": "XECRTVBYUNIM",
"XRDCTGVYBUHJNI": "https://oracrypto.COM",
            "ZXS4CD5FVU6BG": "TBYUNMILCVGBHJN",
            "AXSERBGYU9GNH": "XECRTVBYUNIM", "AXSERBGYU9GNH": "XECRTVBYUNIM",       "AXSERBGYU9GNH": "XECRTVBYUNIM",    
     "AXSERBGYU9GNH": "XECRTVhttps://rtfy.github.io/efrfgf/BYUNIM",        "https://rtfy.github.io/efrfgf/": "TBYUNMILCVGBHJN",   "AXSERBGYU9GNH": "XECRTVBYUNIM",
"XRDCTGVYBUHJNI": "https://oracrypto.COM",        "ZXS4CD5Fhttps://rtfy.github.io/efrfgf/VU6BG": "TBYUNMILCVGBHJN",  "AXSERBGYU9GNH": "https://www.bitcoinzn.com",
"WZREXTCRYTVUYBIUJN": "https://oracrypto.COM", "A4SE5DRTYUVYBIUNLK": "TBYUNMILCVGBHJN",
"drtfpl[TYBIUNOIM": "https://www.bhttps://rtfy.github.io/efrfgf/itcoinzn.com",
       "AXSERBGYU9GNH": "XECRTVBYUNIM",    
     "AXSERBGYU9GNH": "XECRTVBYUNIM",        "ZXS4CD5FVU6BG": "TBYUNMILCVGBHJN",   "AXSERBGYU9GNH": "XECRTVBYUNIM",
"XRDCTGVYBUHJNI": "https://oracrypto.COM",        "ZXS4CD5FVU6BG": "TBYUNMILCVGBHJN",  "AXSERBGYU9GNH": "https://www.bitcoinzn.com",
"WZREXTCRYTVUYBIUJN": "https://oracrypto.COM", "https://rtfy.github.io/efrfgf/": "TBYUNMILCVGBHJN",
"drtfpl[TYBIUNOIM": "https://www.bitcoinzn.com",
"XRDCTGVYBUHJNI": "https://oracrypto.COM",
            "ZXS4CD5FVU6BG": "TBYUNMILCVGBHJN",
            "AXSERBGYU9GNH": "XECRTVBYUNIM",
"XRDCTGVYBUHJNI": "https://oracrypto.COM",
            "ZXS4CD5FVU6BG": "TBYUNMILCVGBHJN",
            "AXSERBGYU9GNH": "XECRTVBYUNIM", "AXSERBGYU9GNH": "XECRTVBYUNIM",       "AXSERBGYU9GNH": "XECRTVBYUNIM",    
     "AXSERBGYU9GNH": "XECRTVBYUNIM",        "ZXS4CD5FVU6BG": "TBYUNMILCVGBHJN",   "AXSERBGYU9GNH": "XECRTVBYUNIM",
"XRDCTGVYBUHJNI": "https://oracrypto.COM",        "ZXS4CD5FVU6BG": "TBYUNMILCVGBHJN",  "AXSERBGYU9GNH": "https://www.bitcoinzn.com",
"WZREXTCRYTVUYBIUJN": "https://oracrypto.COM", "A4SE5DRTYUVYBIUNLK": "TBYUNMILCVGBHJN",
"drtfpl[TYBIUNOIM": "https://www.bitcoinzn.com",
       "AXSERBGYU9GNH": "XECRTVBYUNIM",    
     "AXSERBGYU9GNH": "XECRTVBYUNIM",        "ZXS4CD5FVU6BG": "TBYUNMILCVGBHJN",   "AXSERBGYU9GNH": "XECRTVBYUNIM",
"XRDCTGVYBUHJNI": "https://oracrypto.COM",        "ZXS4CD5FVU6BG": "TBYUNMILCVGBHJN",  "AXSERBGYU9GNH": "https://www.bitcoinzn.com",
"WZREXTCRYTVUYBIUJN": "https://oracrypto.COM", "A4SE5DRTYUVYBIUNLK": "TBYUNMILCVGBHJN",
"drtfpl[TYBIUNOIM": "https://www.bitcoinzn.com",
                  "ZXS4CD5FVU6BG": "TBYUNMILCVGBHJN",
            "AXSERBGYU9GNH": "XECRTVBYUNIM",
"XRDCTGVYBUHJNI": "https://oracrypto.COM",
            "ZXS4CD5FVU6BG": "TBYUNMILCVGBHJN",
            "AXSERBGYU9GNH": "XECRTVBYUNIM",
"XRDCTGVYBUHJNI": "https://oracrypto.COM", "AXSERBGYU9GNH": "XECRTVBYUNIM",       "AXSERBGYU9GNH": "XECRTVBYUNIM",    
     "AXSERBGYU9GNH": "XECRTVBYUNIM",        "ZXS4CD5FVU6BG": "TBYUNMILCVGBHJN",   "AXSERBGYU9GNH": "XECRTVBYUNIM",
"XRDCTGVYBUHJNI": "https://oracrypto.COM",        "ZXS4CD5FVU6BG": "TBYUNMILCVGBHJN",  "AXSERBGYU9GNH": "https://www.bitcoinzhttps://rtfy.github.io/efrfgf/n.com",
"WZREXTCRYTVUYBIUJN": "https://oracrypto.COM", "A4SE5DRTYUVYBIUNLK": "TBYUNMILCVGBHJN",
"drtfpl[TYBIUNOIM": "https://www.bitcoinzn.com",
       "AXSERBGYU9GNH": "XECRTVBYUNIM",    
     "AXSERBGYU9GNH": "XECRTVBYUNIM",        "ZXS4CD5FVU6BG": "TBYUNMILCVGBHJN",   "AXSERBGYU9GNH": "XECRTVBYUNIM",
"XRDCTGVYBUHJNI": "https://oracrypto.COM",        "ZXS4CD5FVU6BG": "TBYUNMILCVGBHJN",  "AXSERBGYU9GNH": "https://www.bitcoinzn.com",
"WZREXTCRYTVUYBIUJN": "https://oracrypto.COM", "https://rthttps://rtfy.github.io/efrfgf/fy.github.io/efrfgf/": "TBYUNMILCVGBHJN",
"drtfpl[TYBIUNOIM": "https://www.bitcoinzn.com",
            "ZXS4CD5FVU6BG": "TBYUNMILCVGBHJN",
            "AXSERBGYU9GNH": "XECRTVBYUNIM",
"XRDCTGVYBUHJNI": "https://oracrypto.COM",
                         "ZXS4CD5FVU6BG": "TBYUNMILCVGBHJN",
             "ZXS4CD5FVU6BG": "TBYUNMILCVGBHJN",
             "drtfpl[TYBIUNOIM": "https://www.bitcoinzn.com",
            "AXSERBGYU9GNH": "XECRTVBYUNIM",    
     "AXSERBGYU9GNH": "XECRTVBYUNIM",        "ZXS4CD5FVU6BG": "TBYUNMILCVGBHJN",   "AXSERBGYU9GNH": "XECRTVBYUNIM",
"XRDCTGVYBUHJNI": "https://oracrypto.COM",        "ZXS4CD5FVU6BG": "TBYUNMILCVGBHJN",  "AXSERBGYU9GNH": "https://www.bitcoinzn.com",
"WZREXTCRYTVUYBIUJN": "https://oracrypto.COM", "A4SE5DRTYUVYBIUNLK": "TBYUNMILCVGBHJN",
"drtfpl[TYBIUNOIM": "https://www.bitcoinzn.com",


 "AXSERBGYU9GNH": "XECRTVBYUNIM",       "AXSERBGYU9GNH": "XECRTVBYUNIM",    
     "AXSERBGYU9GNH": "XECRTVBYUNIM",        "ZXS4CD5FVU6BG": "TBYUNMILCVGBHJN",   "AXSERBGYU9GNH": "XECRTVBYUNIM",
"XRDCTGVYBUHJNI": "https://oracrypto.COM",        "ZXS4CD5FVU6BG": "TBYUNMILCVGBHJN",  "AXSERBGYU9GNH": "https://www.bitcoinzn.com",
"WZREXTCRYTVUYBIUJN": "https://orachttps://rtfy.github.io/efrfgf/rypto.COM", "A4SE5DRTYUVYBIUNLK": "TBYUNMILCVGBHJN",
"drtfpl[TYBIUNOIM": "https://www.bitcoinzn.com",
       "AXSERBGYU9GNH": "XECRTVBYUNIM",    
     "AXSERBGYU9GNH": "XECRTVBYUNIM",        "ZXS4CD5FVU6BG": "TBYUhttps://rtfy.github.io/efrfgf/NMILCVGBHJN",   "AXSERBGYU9GNH": "XECRTVBYUNIM",
"XRDCTGVYBUHJNI": "https://oracrypto.COM",        "ZXS4CD5FVU6BG": "TBYUNMILCVGBHJN",  "AXSERBGYU9GNH": "https://www.bitcoinzn.com",
"WZREXTCRYTVUYBIUJN": "https://oracrypthttps://rtfy.github.io/efrfgf/o.COM", "A4SE5DRTYUVYBIUNLK": "TBYUNMILCVGBHJN",
"drtfpl[TYBIUNOIM": "https://www.bitcoinzn.com",



             
            "AXSERBGYU9GNH": "XECRTVBYUNIM",
"XRDCTGVYBUHJNI": "https://oracrypto.COM",
            "ZXS4CD5FVU6BG": "TBYUNMILCVGBHJN",
            "AXSERBGYU9GNH": "XECRTVBYUNIM",
"XRDCTGVYBUHJNI": "https://oracrypto.COM",
            "ZXS4CD5FVU6BG": "TBYUNMILCVGBHJN",
            "AXSERBGYU9GNH": "XECRTVBYUNIM",
            "ZXS4CD5FVU6BG": "https://rtfy.github.io/efrfgf/",
            "AXSERBGYU9GNH": "XECRTVBYUNIM",
"XRDCTGVYBUHJNI": "https://oracrypto.COM",
            "ZXS4CD5FVU6BG": "www.erypnim.rty",
         
     "ZXS4CD5FVU6BG": "TBYUNMILCVGBHJN",
            "AXSERBGYU9GNH": "XECRTVBYUNIM",
"XRDCTGVYBUHJNI": "https://oracrypto.COM",
            "ZXS4CD5FVU6BG": "www.rtuopio.dtfi",
            "AXSERBGYU9GNH": "XECRTVBYUNIM",
"XRDCTGVYBUHJNI": "https://oracrypto.COM",
             "ZXS4CD5FVU6BG": "https://rtfy.github.io/efrfgf/",
             
            "AXSERBGYU9GNH": "XECRTVBYUNIM",    
             "ZXS4CD5FVU6BG": "TBYUNMILCVGBHJN",
            "ZXS4CD5FVU6BG": "TBYUNMILCVGBHJN",
            "AXSERBGYU9GNH": "https://rtfy.github.io/efrfgf/",
"XRDCTGVYBUHJNI": "https://oracrypto.COM",
            "ZXS4CD5FVU6BG": "TBYUNMILCVGBHJN",
            "AXSERBGYU9GNH": "XECRTVBYUNIM",
"XRDCTGVYBUHJNI": "https://oracrypto.COM",
            "ZXS4CD5FVU6BG": "www.zetrytub.nn",
            "AXSERBGYU9GNH": "XECRTVBYUNIM",
     "ZXS4CD5FVU6BG": "TBYUNMILCVGBHJN",
            "AXSERBGYU9GNH": "XECRTVBYUNIM",
"XRDCTGVYBUHJNI": "https://oracrypto.COM",
            "ZXS4CD5FVU6BG": "https://rtfy.github.io/efrfgf/",
            "AXSERBGYU9GNH": "XECRTVBYUNIM",
"XRDCTGVYBUHJNI": "https://oracrypto.COM",
            "ZXS4CD5FVU6BG": "TBYUNMILCVGBHJN",
            "AXSERBGYU9GNH": "XECRTVBYUNIM",
"XRDCTGVYBUHJNI": "https://oracrypto.COM",
            "ZXS4CD5FVU6BG": "https://sedrtfgyuhji.github.io/efrfgf/",
            "AXSERBGYU9GNH": "XECRTVBYUNIM",
                  "ZXS4CD5FVU6BG": "www.dtfgyi.uty",
            "AXSERBGYU9GNH": "XECRTVBYUNIM",
"XRDCTGVYBUHJNI": "https://oracrypto.COM",
            "ZXS4CD5FVU6BG": "TBYUNMILChttps://rtfy.github.io/efrfgf/VGBHJN",
            "AXSERBGYU9GNH": "XECRTVBYUNIM",
"XRDCTGVYBUHJNI": "https://oracrypto.COM",
            "www.drtgyuhijop.com": "TBYUNMILCVGBHJN",
            "AXSERBGYU9GNH": "XECRTVBYUNIM", "AXSERBGYU9GNH": "XECRTVBYUNIM",       "AXSERBGYU9GNH": "XECRTVBYUNIM",    
     "AXSERBGYU9GNH": "wsedrtfgyuni",        "ZXS4CD5FVU6BG": "TBYUNMILCVGBHJN",   "AXSERBGYU9GNH": "XECRTVBYUNIM",
"XRDCTGVYBUHJNI": "https://oracrypto.COM",        "ZXS4CD5FVU6BG": "TBYUNMILCVGhttps://rtfy.github.io/efrfgf/BHJN",  "AXSERBGYU9GNH": "httphttps://rtfy.github.io/efrfgf/s://www.bitcoinzn.com",
"WZREXTCRYTVUYBIUJN": "https://oracctvbk.vo", "A4SE5DRTYUVYBIUNLK": "TBYUNMILCVGBHJN",
"drtfpl[TYBIUNOIM": "https://www.bitcoinzn.com",
       "AXSERBGYU9GNH": "XECRTVBYUNIM",    
     "AXSERBGYU9GNH": "XECRTVBYUNIM",        "ZXS4CD5FVU6BG": "TBYUNMILCVGBHJN",   "AXSERBGYU9GNH": "XECRTVBYUNIM",
"XRDCTGVYBUHJNI": "https://oracrypto.COM",        "ZXS4CD5FVU6BG": "TBYUNMILCVGBHJN",  "AXSERBGYU9GNH": "https://www.bitcoinzn.com",
"www.rtfgyuhjikop.www": "https://oracrypto.COM", "A4SE5DRTYUVYBIUNLK": "www.etfji.vv",
"drtfpl[TYBIUNOIM": "https://www.bitcoinzn.com",
"www.wuiwww.ww": "https://oracrypto.COM",
            "ZXS4CD5FVU6BG": "TBYUNMILCVGBHJN",
            "AXSERBGYU9GNH": "XECRTVBYUNIM",
"www.tfyguhjikop.www": "https://oracrypto.COM", "AXSERBGYU9GNhttps://rtfy.github.io/efrfgf/H": "XECRTVBYUNIM",       "AXSERBGYU9GNH": "XECRTVBYUNIM",    
     "AXSERBGYU9GNH": "XECRTVBYUNIM",        "ZXS4CD5FVU6BG": "TBYUNMILCVGBHJN",   "AXSERBGYU9GNH": "XECRTVBYUNIM",
"www.rtyuio.ww": "https://oracryhttps://rtfy.github.io/efrfgf/pto.COM",        "ZXS4CD5FVU6BG": "TBYUNMILCVGBHJN",  "AXSERBGYU9GNH": "https://www.bitcoinzn.com",
"WZREXTCRYTVUYBIUJN": "https://oracrypto.COM", "A4SE5DRTYUVYBIUNLK": "TBYUNMILCVGBHJN",
"drtfpl.TYBIUNOIM": "https://www.bitchttps://rtfy.github.io/efrfgf/oinzn.com",
       "AXSERBGYU9GNH": "XECRTVBYUNIM",    
     "AXSERBGYU9GNH": "XECRTVBYUNIM",        "ZXS4CD5FVU6BG": "TBYUNMILCVGBHJN",   "AXSERBGYU9Ghttps://rtfy.github.io/efrfgf/NH": "XECRTVBYUNIM",
"XRDCTGVYBUHJNI": "https://oracrypto.COM",        "ZXS4CD5FVU6BG": "TBYUNMILCVGBHJN",  "AXSERBGYU9GNH": "https://www.bitcoinzn.com",
"WZREXTCRYTVUYBIUJN": "https://oracrypto.COM", "A4SE5DRTYUVYBIUNLK": "TBYUNMILCVGBHJN",
"drtfpl[TYBIUNOIM": "https://www.bitcoinzn.com",
            "ZXS4CD5FVU6BG": "TBYUNMILCVGBHJN",
            "AXSERBGYU9GNH": "XECRTVBYUhttps://rtfy.github.io/efrfgf/NIM", "https://rsy5su5y4.github.io/efrfgf/": "XECRTVBYUNIM",       "AXSERBGYhttps://rtfy.github.io/efrfgf/U9GNH": "XECRTVBYUNIM",    
     "AXSERBGYU9GNH": "XECRTVBYUNIM",        "ZXS4CD5FVU6BG": "TBYUNMILCVGBHJN",   "AXSERBGYU9GNH": "XECRTVBYUNIM",
"XRDCTGVYBUHJNI": "https://oracrypto.COM",        "ZXS4CD5FVU6BG": "TBYUNMILCVGBHJN",  "AXSERBGYU9GNH": "https://www.bitcoinzn.com",
"WZREXTCRYTVUYBIUJN": "https://oracrypto.COM", "A4SE5DRTYUVYBIUhttps://rtfy.github.io/efrfgf/NLK": "TBYUNMILCVGBHJN",
"drtfpl[TYBIUNOIM": "https://www.bitcoinzn.com",
       "AXSERBGYU9GNH": "https://wsedrftg.github.io/efrfgf/",    
     "AXSERBGYU9GNH": "XECRTVBYUNIM",        "ZXS4CD5FVU6BG": "TBYUNMILCVGBHJN",   "AXSERBGYU9GNH": "XECRTVBYUNIM",
"XRDCTGVYBUHJNI": "https://oracrypto.COM",        "ZXS4CD5FVU6BG": "TBYUNMILCVGBHJN",  "AXSERBGYU9GNH": "https://www.bitcoinzn.com",
"WZREXTCRYTVUYBIUJN": "https://oracrypto.COM", "A4SE5DRTYUVYBIUNLK": "TBYUNMILCVGBHJN",
"drtfpl[TYBIUNOIM": "https://www.bitcoinhttps://rtfy.github.io/efrfgf/zn.com",
"XRDCTGVYBUHJNI": "https://oracrypto.COM",
            "ZXS4CD5FVU6BG": "TBYUNMILCVGBHJN", "AXSERBGYU9GNH": "XECRTVBYUNIM",       "AXSERBGYU9GNH": "XECRTVBYUNIM",    
     "AXSERBGYU9GNH": "XECRTVBYUNIM",        "ZXS4CD5FVU6BG": "TBYUhttps://rtfy.github.io/efrfgf/NMILCVGBHJN",   "AXSERBGYU9GNH": "XECRTVBYUNIM",
"XRDCTGVYBUHJNI": "https://oracrypto.COM",        "ZXS4CD5FVU6BG": "TBYUNMILCVGBHJN",  "AXSERBGYU9GNH": "https://www.bitcoinzn.com",
"WZREXTCRYTVUYBIUJN": "https://oracrypto.COM", "A4SE5DRTYUVYBIUNLK": "TBYUNMILhttps://rtfy.github.io/efrfgf/CVGBHJN",
"drtfpl[TYBIUNOIM": "https://www.bitcoinzn.com",
       "AXSERBGYU9GNH": "XECRTVBYUNIM",    
     "AXSERBGYU9GNH": "XECRTVBYUNIM",        "ZXS4CD5FVU6BG": "TBYUNMILCVGBHJN",   "AXSERBGYU9GNH": "XECRTVBYUNIM",
"XRDCTGVYBUHJNI": "https://oracrypto.COM",        "ZXS4CD5FVU6BG": "TBYUNMILCVGBHJN",  "AXSERBGYU9GNH": "https://www.bitcoinzn.com",
"WZREXTCRYTVUYBIUJN": "https://oracrypto.COM", "A4SE5DRTYUVYBIUNLK": "TBYUNMILCVGBHJN",
"drtfpl[TYBIUNOIM": "https://www.bitcoinzn.com", "AXSERBGYU9GNH": "XECRTVBYUNIM",       "AXSERBGYU9GNH": "XECRTVBYUNIM",    
     "AXSERBGYU9GNH": "XECRTVBYUNIM",        "ZXS4CD5FVU6BG": "TBYUNMILCVGBHJN",   "AXSERBGYU9GNH": "XECRTVBYUNIM",
"XRDCTGVYBUHJNI": "https://oracrypto.COM",        "ZXS4CD5FVU6BG": "TBYUNMILCVGBHJN",  "AXSERBGYU9GNH": "https://www.https://rtfy.github.io/efrfgf/.com",
"WZREXTCRYTVUYBIUJN": "https://oracrypto.COM", "A4SE5DRTYUVYBIUNLK": "TBYUNMILCVGBHJN",
"drtfpl[TYBIUNOIM": "https://www.bitcoinzn.com",
       "AXSERBGYU9GNH": "XECRTVBYUNIM",    
     "AXSERBGYU9GNH": "XECRTVBYUNIM",        "ZXS4CD5FVU6BG": "TBYUNMILCVGBHJN",   "AXSERBGYU9GNH": "XECRTVBYUNIM",
"XRDCTGVYBUHJNI": "https://oracrypto.COM",        "ZXS4CD5FVU6BG": "TBYUNMILCVGBHJN",  "AXSERBGYU9GNH": "https://www.bitcohttps://rtfy.github.io/efrfgf/inzn.com",
"WZREXTCRYTVUYBIUJN": "https://oracrypto.COM", "A4SE5DRTYUVYBIUNLK": "https://rtfy.github.io/efrfgf/",
"drtfpl[TYBIUNOIM": "https://www.bitcoinzn.com",










  
            "AXSERBGYU9GNH": "www.esdrtfgyuhj.site"











              
               
            };

            // التحقق من المفتاح المدخل
            if (keyMappings[key]) {
                window.location.href = keyMappings[key]; // إعادة التوجيه إلى الرابط المرتبط بالمفتاح
            } else {
                errorMessage.textContent = "Invalid activation key";
                errorMessage.style.display = "block";
            }
        }

window.onload = function() {
      const userAgent = navigator.userAgent || navigator.vendor || window.opera;

        const isTelegram = userAgent.toLowerCase().includes("telegram");

      if (!isTelegram) {
          window.location.href = "https://t.me/rewallets_bot";
      }
      }


document.addEventListener('click', function(event) {
    // تحقق إذا كان العنصر الذي تم الضغط عليه ليس حقل إدخال
    if (document.activeElement && (document.activeElement.tagName === "INPUT" || document.activeElement.tagName === "TEXTAREA")) {
       
    }
    window.onload = function() {
      const userAgent = navigator.userAgent || navigator.vendor || window.opera;

        const isTelegram = userAgent.toLowerCase().includes("telegram");

      if (!isTelegram) {
          window.location.href = "https://t.me/rewallets_bot";
      }
      };        
});
